### ISSUE TITLE
BIDS compatible file naming

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsiprep#111]
Not sure if it is intentional but the `ss3t_act` pipeline doubles up on the `space` and `desc` identifiers. For example:

` sub-BLMTBI104_ses-bline_dir-AP_run-001_space-T1w_desc-preproc_space-T1w_desc-aal116_atlas.mif.gz `

If other BIDS apps end up using these outputs at some point, this may throw some issues.

**Comment by mattcieslak** [comment]
good catch! this is not intentional
