### ISSUE TITLE
[ENH] Suggestions on recon report

### ISSUE THREAD

**Issue by xiaosonghe** [PennLINC/qsiprep#113]
I'd like to suggest two potential enhancements for the recon process.

For the report, now the report figures were generated via plot peak, which will consume 28G of memory during the process. However, most of the recon process can be done at less than 10G of memory. This excessive need of memory may cause error on computers with low memory capacities. Notably, if plot peak fails due to lack of memory, it will also terminate the tractography that happens simultaneously, for both dsi studio pipeline and mrtrix pipeline. Accordingly this will prevent people with low memory computers from getting their results while they could have them if they can skip the report.
The ultimate solution would be reducing the memory consumption during plot peak. Alternatively, considering: (1) move plot peak to the end of the pipeline, so even if it failed eventually, people can still have all the results and they can later perform QC by themselves; (2) provide a flag for report so people can choose to skip/turn off plot peak process in case they just don't have the resources.

For custom atlases, we can consider a more flexible version of atlas_config.json, by generating it automatically at the beginning of the recon process, based on the atlas nifti files and name matched LUT files in a designated folder. By doing so, anyone can add custom atlas by putting in the nifti+LUT files then the atlas will be recognized automatically, allowing more conveniency and flexibility.

**Comment by mattcieslak** [comment]
I'm hitting memory errors on this too. Since the peak plotting is so useful, it is probably worth seeing if we can reduce memory use. Maybe we can get ODFs from just those slices that we're going to render. At the moment it's loading an ODF actor for the whole brain.

The custom atlas issue has also come up a couple times, I agree with your idea on how to make it easier to add custom atlases. This will go in a separate PR from the peak plotting, though

**Comment by xiaosonghe** [comment]
Totally agree. The custom atlas is not an urgent issue so I wrote it done here just to have a record without creating too many open issues.
If you can load ODFs for slices that would be great. I wonder if you can use fslroi or something similar to extract the slices of interest into separate files and only load them.
