### ISSUE TITLE
Include fmriprep-like option `--bids-filter-file`

### ISSUE THREAD

**Issue by mkleemeyer** [PennLINC/qsiprep#121]
We have multiple T1w acquisitions (highres for specific regions), where only the one without the acq key specified should be picked for qsiprep. In fmriprep this can be specified in the `--bids-filter-file`. Could this option be added to qsiprep as well? For now, it only works if I delete those files from the anat folder...

**Comment by mattcieslak** [comment]
This has been doable for awhile, sorry for not updating this issue
