### ISSUE TITLE
tck2connectome call

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsiprep#131]
Hi @mattcieslak 

I was working on getting mean FA values for the connectomes and I just wanted to double check what the actual `tck2connectome` call is for the MRtrix MSMT No ACT pipeline. Based on the code, it looks like the basic call is (roughly):

`tck2connectome ***_ifod2.tck <atlas>.mif.gz <atlas_matrix>.csv -assignment_voxel_lookup -assignment_radial_search 2 -tck_weights_in  ***siftweights_ifod2.csv -symmetric -scale_length -stat_edge sum`

Anything I'm missing, particularly for the  streamline assignment options (`-assignment_reverse/forward_search`

**Comment by mattcieslak** [comment]
There are a couple `tck2connectome` calls, each with a different weighting. For mean FA you probably don't want `-scale_length` and would want `-stat_edge mean`

**Comment by araikes** [comment]
For sure. I was just making sure I had the rest of call correct so I could reuse the existing tck file for comparability with (for example) the mean length matrix.

**Comment by araikes** [comment]
One last question and then I'll close this...

Is there a reason for mean length that SIFT weights aren't used?

Thanks for all the help and the tool @mattcieslak

**Comment by xiaosonghe** [comment]
Personally I think you can edit the recon-spec .json file so that you can have mean length weighted output to be generated. I myself prefer to customize those files to output exactly what I want. Just in case you are interested, I found this piece insightful:
https://www.mrtrix.org/2016/05/25/heuristic-scaling-of-connectome-edge-strengths/

**Comment by araikes** [comment]
Hi @xiaosonghe,

You're right, I can definitely submit a custom json recon-spec. The challenge, from my initial question, was that to sample scalar metrics for ROI-to-ROI connections requires A) the scalar map (i.e. FA maps) and B) an extra call to `tcksample` before running `tck2connectome`. So it was simpler to just run that in a script apart from QSIPrep after I created the scalar maps, using the already created tractography and SIFT weights. From that perspective, I just wanted to make sure that my subsequent `tck2connectome` call matched the original so that if I compared streamline counts between ROIs and FA between the same ROIs, both values were generated in the approximately same way.

With respect to my second question, I could obviously use a custom json to get SIFT-weighted mean length. I was just curious if @mattcieslak had a particular theoretical reason for not including it given the other metrics that are produced. I'm definitely aware of Robert Smith's position on using inverse node size and other scaling methods compared to SIFT by itself (hence my question, since QSIPrep gives SIFT-weighted streamline counts and SIFT-weighted inverse node volume scaled counts but not SIFT-weighted length).

**Comment by xiaosonghe** [comment]
@araikes OK, that is way beyond my knowledge of qsiprep and mrtrix so I will let the expert answer :P 
The fact is there are so many options and combinations. I was curious about his choices as well at the very beginning. Then I realize Matt could select them just for some demonstration purpose, or because ppl who work with him rely on those variations more than others, or other reasons. To have all of them produced is simple from his part, i.e., a few extra lines in the specs, but it can be quite confusing for the users to figure out what they want and also time-consuming.
I personally don't remember if he endorses any option in particular, at least not when I was making similar inquiries. I had to find out my own choice by reading Rob Smith and others' posts on the mrtrix website. Essentially, the lack of consensus is a common issue in this community. Hopefully, we will be informed better in the future. Good luck to have your technical question resolved soon!

**Comment by M31glx** [comment]
Hi guys, Just following up on this thread, I was wondering how I can get structural connectome based on mean FA?
In mrtrix3 documentation it is suggested to use the following command line:

$ **tcksample** tracks.tck FA.mif mean_FA_per_streamline.csv -stat_tck mean; **tck2connectome** tracks.tck nodes.mif mean_FA_connectome.csv -scale_file mean_FA_per_streamline.csv -stat_edge mean

But I'm not sure how I can modify the custom recon file! Could anyone help with this?
Here is my current pipeline:

 
{
  "name": "mrtrix_singleshell_ss3_hsvst",
  "space": "T1w",
  "atlases": ["schaefer100x7", "schaefer100x17", "schaefer200x7", "schaefer200x17", "schaefer400x7", "schaefer400x17", "brainnetome246", "aicha384", "gordon333", "aal116", "power264"],
  "anatomical": ["mrtrix_5tt_hsvs"],
  "nodes": [
    {
      "name": "ss3t_csd",
      "software": "MRTrix3",
      "action": "csd",
      "output_suffix": "ss3tcsd",
      "input": "qsiprep",
      "parameters": {
        "mtnormalize": true,
        "response": {
          "algorithm": "dhollander"
        },
        "fod": {
          "algorithm": "ss3t"
        }
      }
    },

    {
      "name": "scalar_export",
      "software": "MRTrix3",
      "action": "export",
      "input": "ss3t_csd",
      "output_suffix": "csdscalar"
    },
    {
      "name": "track_ifod2",
      "software": "MRTrix3",
      "action": "tractography",
      "output_suffix": "ifod2",
      "input": "ss3t_csd",
      "parameters": {
        "use_5tt": true,
        "method_5tt": "hsvs",
        "use_sift2": true,
        "tckgen":{
          "algorithm": "iFOD2",
          "select": 1e7,
          "max_length": 250,
          "min_length": 5,
          "power":0.33,
          "crop_at_gmwmi": true,
          "backtrack": true
        },
        "sift2":{}
      }
    },
    {
      "name": "mrtrix_conn",
      "software": "MRTrix3",
      "action": "connectivity",
      "output_suffix": "dhollanderconnectome",
      "input": "track_ifod2",
      "parameters":{
        "tck2connectome": [
          {
            "zero_diagonal": false,
            "search_radius": 2,
            "scale_invnodevol": true,
            "symmetric": true,
            "use_sift_weights": true,
            "stat_edge": "sum",
            "measure": "sift_invnodevol_radius2_count"
          },
          {
            "zero_diagonal": false,
            "search_radius": 2,
            "scale_invnodevol": false,
            "symmetric": true,
            "length_scale": "length",
            "use_sift_weights": false,
            "stat_edge": "mean",
            "measure": "radius2_meanlength"
          },
          {
            "zero_diagonal": false,
            "search_radius": 2,
            "scale_invnodevol": false,
            "symmetric": true,
            "use_sift_weights": false,
            "stat_edge": "sum",
            "measure": "radius2_count"
          },
          {
            "zero_diagonal": false,
            "search_radius": 2,
            "scale_invnodevol": false,
            "symmetric": true,
            "use_sift_weights": true,
            "stat_edge": "sum",
            "measure": "sift_radius2_count"
          }
        ]
      }
    }
  ]
}
