### ISSUE TITLE
Use previously computed freesurfer output

### ISSUE THREAD

**Issue by eds-slim** [PennLINC/qsiprep#142]
Hi,
is it possible to reuse previously computed freesurfer outputs when specifying `--do-reconall`? I guess it depends on whether FS is run on the original T1w images or after registration to b0 ...
If so, would the location of the FS output just be identified via environment variables passed into singularity?
Thanks!

**Comment by eds-slim** [comment]
Looking through the code, I notice that `recon-all` seems to be called with the ` -sd <output dir>/freesurfer` option, thus overriding the `SUBJECTS_DIR` environmental variable.

Do you think it would be reasonable to not use this option and to thus reuse an existing FS output?

**Comment by ins0mniac2** [comment]
bumping this.

**Comment by mayayab** [comment]
Hi @ins0mniac2 did you end up using the path to the previously computed freesurfer folder? if so, did it work properly?

**Comment by mattcieslak** [comment]
This has been available for a few versions
