### ISSUE TITLE
Calculate mask from DWI data 

### ISSUE THREAD

**Issue by arokem** [PennLINC/qsiprep#155]
This is usually quite thorny. In some cases, maybe this could be done by calculating an anisotropic power map (implemented in DIPY [here](https://dipy.org/documentation/1.1.1./reference/dipy.reconst/#dipy.reconst.shm.anisotropic_power)) and using T1w methods on the resulting image?

**Comment by mattcieslak** [comment]
Using synthstrip for this now, seems to work pretty well
