### ISSUE TITLE
[ENH] Write a report.json derivative that can be loaded in dmriprep-viewer

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/qsiprep#165]
Save this along with the other figures in the derivatives

Tagging @richford

**Comment by mattcieslak** [comment]
Can add a javascript button that will go somwhere here: https://github.com/PennBBL/qsiprep/blob/master/qsiprep/viz/report.tpl#L174

**Comment by richford** [comment]
In addition to the content already in the [example json](https://github.com/nipreps/dmriprep-viewer/blob/master/example/report.json), the json should include the following fields:
- [ ] `subject_id`, let's say with the "sub-" prefix
- [ ] `analysis_level`, whose value should be "participant" or "group"
- [ ] `pipeline`, whose value is "qsiprep"
- [ ] `pipeline_version`, with the version of qsiprep
- [ ] `boilerplate`, with the boilerplate html used in report.html

**Comment by richford** [comment]
Also, after the conversation in our telecon this morning, perhaps we should add a json sidecar to `report.json` the same way we do for nifti files.

**Comment by richford** [comment]
I've made a public S3 bucket at s3://dmriprep-viewer-example-data with a sample layout for these reports. Please use this as a reference spec for the json reports. Things to note:

- All reports have a `dwiqc.json` suffix (and I'm certainly open to discussion on the naming scheme).
- The subject level reports are inside of subject directories but we can place them at any level of the subject dir hierarchy (e.g. in anat or dwi directories if we want).
- The group report has no subject label in its name and is places at the root of the derivative directory (e.g. in `derivatives/qsiprep`)
- The participant reports are as described above.
- The group level report has the following fields
  - `"report_type": "dwi_qc_report"`
  - `"pipeline": "qsiprep"`
  - `"pipeline_version":` version of qsiprep used to generate report
  - `"analysis_level": "group"`
  - `"boilerplate":` any html boilerplate that we want for the entire study
  - `"subjects":` an array described in the next bullet
  - `"metric_explanation:` an object with the same keys found in each element of the subjects array, with values that explain what the metric is
- The subjects array is an array of objects, each of which has the same keys. The only required key is "participant_id." I imagine the other ones will come from the `ImageQc` csv headers.

**Comment by richford** [comment]
Tagging @arokem for visibility of the json report spec.

**Comment by richford** [comment]
BTW, `pandas.DataFrame.to_json(orient="records")` should create the subjects array in exactly the format that I've specified.

**Comment by arokem** [comment]
It's fine for this to be a public S3 bucket, if there's good reason. As an alternative, consider using OSF's storage.

**Comment by richford** [comment]
@arokem, good point. I wanted to include S3 support in dmriprep-viewer so that we could support HBN and any dataset on OpenNeuro. But I opened [an issue](https://github.com/nipreps/dmriprep-viewer/issues/32) on dmriprep-viewer about OSF support.
