### ISSUE TITLE
ValueError: No gradient information available

### ISSUE THREAD

**Issue by 36000** [PennLINC/qsiprep#171]
Thanks for making this software. I am trying to use it to preprocess the ixi-dataset. I am running it on one subject and am getting this error:
![image](https://user-images.githubusercontent.com/9562159/91106682-20b47880-e628-11ea-8262-a0aec420db19.png)

The error gets raised here: https://github.com/PennBBL/qsiprep/blob/dc6759eb3834063858f57ef710677aa1558788e9/qsiprep/interfaces/gradients.py#L304
I tried figuring out where b0_indices or bval_file come from, but got lost.

I am wondering if there is something I need to add to the json file, or if my bval / bvec files are in the wrong place.
I am running qsiprep on my ixi-bids directory, and I put the bval / bvec files here:
![image](https://user-images.githubusercontent.com/9562159/91106767-5c4f4280-e628-11ea-98b7-d745efbb65f7.png)

**Comment by mattcieslak** [comment]
Hi! Have you run the bids validator on your dataset? If you don't have nodejs installed you can use their online checker at https://bids-standard.github.io/bids-validator/

**Comment by 36000** [comment]
Thank you for the quick reply! There are a few warnings:
![image](https://user-images.githubusercontent.com/9562159/91107452-3460de80-e62a-11ea-87dc-55287128f2ac.png)
Do you think that the "Warning 1: [Code 41] NIFTI_UNIT" could be causing the problem?

**Comment by mattcieslak** [comment]
Could you post the bval and bvec file contents? It's also possible that you ran out of space on the disk where your working directory is.

**Comment by 36000** [comment]
Here are the bval and bvec file contents:
![image](https://user-images.githubusercontent.com/9562159/91202939-5b192680-e6b7-11ea-8a79-962dabdf9aa5.png)
Is it possible that I a lack of memory could cause this?

**Comment by 36000** [comment]
I found the report associated with the pipeline it could not run (```could not run node: qsiprep_wf.single_subject_IXI039_wf.dwi_preproc_wf.pre_hmc_wf.merge_and_denoise_wf.dwi_denoise_dwi_wf.get_b0s```):
![image](https://user-images.githubusercontent.com/9562159/91342370-ca624980-e78f-11ea-9371-fbfe2262129f.png)

**Comment by 36000** [comment]
What parameters are required for the json sidecars? My sidecar only includes the PhaseEncodingDirection.
