### ISSUE TITLE
Custom Reconstruction With Other Preprocessing Derivatives 

### ISSUE THREAD

**Issue by tjhendrickson** [PennLINC/qsiprep#173]
Hello,

Perhaps I missed this within the readthedocs page or within the issues raised on GitHub, but I am curious whether qsiprep can accept derivatives from other processing pipelines as input into the reconstruction pipeline. The reason I ask is that a data set that I would like to analyze already has extensively processed diffusion data through the HCP pipeline. If possible I would like to link these outputs directly into the reconstruction pipeline in order to eventually get estimates of structural connectivity based on one of the canned atlases provided. 

Best,

-Tim

**Comment by mattcieslak** [comment]
Hi Tim,
We haven't tried ingressing HCP pipeline output yet, but it sounds like this might be a common use case. The major issue with the connectivity pipelines is that we're expecting ANTs transforms to template space to get atlas regions aligned with the DWI data. Would calculating new registrations to MNI be a dealbreaker for you?

**Comment by tjhendrickson** [comment]
I don't think so!

**Comment by bwinsto2** [comment]
Another option is running hcp2bids on hcp unprocessed data and then running qsiprep and reconstruction on that 🤷‍♂️

**Comment by tjhendrickson** [comment]
Have there been any updates on this? Is there anything I can do to help?

**Comment by mattcieslak** [comment]
Works for UKB now!
