### ISSUE TITLE
[ENH] Figure out QC metrics for reconstruction outputs

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/qsiprep#178]
It would be enormously useful to have QC metrics for reconstruction outputs for sanity checking and pipeline benchmarking.

One great option are some of the fib qc metrics from DSI Studio. @frankyeh are there any of DSI Studio's fib QC measures that can be accessed via the commandline interface?

**Comment by frankyeh** [comment]
There is only one for QSDR reconstructed FIB files: the R squared value
between the subject image and template image. It can be accessed by
unzipping the fib.gz file, renaming it as .mat, and loading it as a MATLAB
file.
Another is the neighboring DWI correlation for SRC files.
Frank

**Comment by mattcieslak** [comment]
What about the algorithm that calculates:

```
Fiber coherence index: 946058
Fiber discoherent index: 115522
```

Would this be suitable as a qc metric?

**Comment by frankyeh** [comment]
Yes, but it may not be as good as NDC. and thus I haven't put it on the
command line yet.
Frank

**Comment by mattcieslak** [comment]
If you're interested, I'd be happy to benchmark this on a lot of data! I really like that it works on any reconstruction

**Comment by frankyeh** [comment]
Sure. I will list it on my higher priority list and should be ready in the
command line in days.
Frank

**Comment by frankyeh** [comment]
updated.
how DSI Studio supports qc on fib
dsi_studio --action=qc --source=my.fib.gz

**Comment by mattcieslak** [comment]
@frankyeh you are amazing! I will get in touch off github about possible benchmarking strategies.

**Comment by mattcieslak** [comment]
@frankyeh did the command line call for calculating QC change with this update?

**Comment by frankyeh** [comment]
Should still be the same. If not, I will fix it.
Frank

**Comment by mattcieslak** [comment]
@frankyeh the directory where the results file is written changed, no need to fix anything. I am noticing some different behavior in how bvecs are read. Is there any reason that the newest DSI Studio might be flipping the y direction even with --check-btable=0?

dsi_studio from January:
![image](https://user-images.githubusercontent.com/170026/95112730-5496b980-070f-11eb-8a4c-04c28a445462.png)

dsi_studio from last week:
![image](https://user-images.githubusercontent.com/170026/95112840-7a23c300-070f-11eb-97cd-641655d6c3cd.png)

**Comment by frankyeh** [comment]
Yes, I received a request to flip y if DSI Studio reads b-table from FSL's
bvec because of the orientation convention differences.
I am sorry that this causes a problem here.
If there is a suggestion for a better solution, I will fix it right away.
Frank

**Comment by mattcieslak** [comment]
would it be possible to revert to the previous behavior? Or add a flag to the commandline to use FSL Mode? The prior behavior was consistent with Dipy and is heavily depended on in qsiprep

**Comment by mattcieslak** [comment]
also, the fiber coherence index picked up a problem with the flipped data right away. Very excited to calculate this by default from now on!

**Comment by frankyeh** [comment]
Just committed a change to revert it.
Sorry for the hassle.
Frank

**Comment by mattcieslak** [comment]
Thanks Frank!!
