### ISSUE TITLE
incorrect biascorrection

### ISSUE THREAD

**Issue by longfangithub** [PennLINC/qsiprep#179]
The dMRI image's uniformity of some data after bias correction is worse. I checked some results and found that it may be caused by the incorrect input mask. The following is an example of the image to be corrected,  its quick-mask and the image before and after bias correction.
![image](https://user-images.githubusercontent.com/32872738/93431320-95f92d80-f8f6-11ea-9133-a7d3a4087a51.png)
![image](https://user-images.githubusercontent.com/32872738/93431441-b7f2b000-f8f6-11ea-9d63-a9ba98009377.png)
![image](https://user-images.githubusercontent.com/32872738/93431578-e83a4e80-f8f6-11ea-8080-a852bac91fff.png)
![image](https://user-images.githubusercontent.com/32872738/93431643-030cc300-f8f7-11ea-8094-52fc2cdfe9aa.png)

**Comment by mattcieslak** [comment]
Hi @longfangithub thanks for reporting this. How does the lowb image look before and after biascorrection? That 's what the bias correction is run on. Would you be willing to share an example dataset?

**Comment by longfangithub** [comment]
The uniformity of lowb images after bias correction also become worse. Here we provide you the b0 image of this example, whose b value is 0 and gradient vector is [0 0 0]. 
[b0.nii.gz](https://github.com/PennBBL/qsiprep/files/5239454/b0.nii.gz)

**Comment by mattcieslak** [comment]
Yea that looks off. You can disable bias correction with `--dwi-no-biascorr` and instead do bias correction during reconstruction. The MRtrix3 workflows include mtnormalize, which will likely do a better job.
