### ISSUE TITLE
--dwi-only doesn't seem to work as intended

### ISSUE THREAD

**Issue by WilliamFCB** [PennLINC/qsiprep#193]
Hi Matthew,

I am trying to run qsiprep (12.2) with the --dwi-only flag on data lacking a T1w. However, as far as I can tell it still searches for T1w data. Below the error message and the singularity command I ran.

Any idea what might go wrong?

Many thanks in advance
William

######## eror messsage:
    Running qsiprep version :
      * BIDS dataset path: /data_in.
      * Participant list: ['004ses01prisma3t'].
      * Run identifier: 20201111-111111_51edfeed-225d-4aac-9863-13a5d9a58e21.
    
201111-11:11:13,257 nipype.workflow INFO:
         Combining all 1 dwis within the single available session
201111-11:11:13,339 nipype.workflow INFO:
         [{'dwi_series': ['/data_in/sub-004ses01prisma3t/dwi/sub-004ses01prisma3t_acq-hardi_run-01_dwi.nii.gz'], 'fieldmap_info': {'suffix': 'epi', 'epi': ['/data_in/sub-004ses01prisma3t/fmap/sub-004ses01prisma3t_acq-hardiref_dir-PA_run-01_epi.nii.gz']}, 'dwi_series_pedir': 'j-', 'concatenated_bids_name': 'sub-004ses01prisma3t_acq-hardi_run-01'}]
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 927, in build_qsiprep_workflow
    force_syn=opts.force_syn
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 269, in init_qsiprep_wf
    force_syn=force_syn)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 647, in init_single_subject_wf
    t1w_source_file=fix_multi_T1w_source_name(subject_data['t1w']),
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/utils/misc.py", line 22, in fix_multi_T1w_source_name
    base, in_file = os.path.split(filename_to_list(in_files)[0])
IndexError: list index out of range
(END)

######### the singularity command I ran:

singularity run --cleanenv --contain \
    -B ${TOOLS_DIR} \
    -B ${BIDS_DIR_TMP}/:/data_in \
    -B ${BIDS_DIR}/:${BIDS_DIR} \
    -B ${SCRIPTS_DIR}/:${SCRIPTS_DIR} \
    -B ${BIDS_DIR}/derivatives/dwi:/data_out \
    -B ${WORK_DIR}:/work \
    -B /tmp:/tmp \
    /bin/qsiprep-0.12.2_fsl-6.0.4-patch.sif \
    /data_in \
    /data_out \
    participant \
    -w /work \
    --participant-label ${sub}${ses/-/} \
    --skip_bids_validation \
    --dwi-only \
    --use-plugin ${SCRIPTS_DIR}/tmp/qsiprep_plugin/${sub}_${ses}_qsiprep_plugin.yml \
    --fs-license-file ${TOOLS_DIR}/freesurfer/freesurfer.6.0.0/license.txt \
    --unringing-method mrdegibbs \
    --dwi-denoise-window 5 \
    --output-resolution 1.8 \
    --hmc-model eddy \
    --eddy_config ${SCRIPTS_DIR}/tmp/eddy_params/${sub}_${ses}_eddy_params.json \
    --nthreads  ${SLURM_CPUS_PER_TASK} \
    -vv

**Comment by mattcieslak** [comment]
thanks for reporting this! It looks like there is a bug and the fix should be quick

**Comment by WilliamFCB** [comment]
Sounds good!
thanks a lot

**Comment by WilliamFCB** [comment]
Super, many thanks
Happy holidays and stay save!

**Comment by mattcieslak** [comment]
Thanks for reporting the issue! You should be able to get the fixed docker image using the :unstable tag. There will be an official release with this in there soon.

**Comment by WilliamFCB** [comment]
great.... many thanks again!

**Comment by pcamach2** [comment]
I'm running into this error with the most recent 0.13.0 build using the following command:

SINGULARITY_CACHEDIR=${scachedir} SINGULARITY_TMPDIR=${stmpdir} singularity run --cleanenv --bind ${IMAGEDIR}:/imgdir,${stmpdir}:/paulscratch,${projDir}:/data ${IMAGEDIR}/qsiprep-v0.13.0.sif --fs-license-file /imgdir/license.txt /data/bids /data/bids/derivatives --output-resolution 2.0 -w /paulscratch participant --participant-label ${subject} --skip_bids_validation --dwi_only


210518-15:37:15,155 nipype.workflow INFO:
Running with omp_nthreads=8, nthreads=24
210518-15:37:15,157 nipype.workflow IMPORTANT:

    Running qsiprep version 0.13.0:
      * BIDS dataset path: /data/bids.
      * Participant list: ['DWI000'].
      * Run identifier: 20210518-153714_a00a19a7-d105-47e3-82ca-dd458a3f836f.
   
210518-15:38:30,876 nipype.workflow INFO:
Combining all dwi files within each available session:
210518-15:38:30,878 nipype.workflow INFO:
- 1 scans in session A
210518-15:38:31,47 nipype.workflow INFO:
[{'dwi_series': ['/data/bids/sub-DWI000/ses-A/dwi/sub-DWI000_ses-A_run-1_dwi.nii.gz'], 'fieldmap_info': {'suffix': 'epi', 'epi': ['/data/bids/sub-DWI000/ses-A/fmap/sub-DWI000_ses-A_acq-dwi_dir-AP_run-1_epi.nii.gz', '/data/bids/sub-DWI000/ses-A/fmap/sub-DWI000_ses-A_acq-dwi_dir-PA_run-2_epi.nii.gz']}, 'dwi_series_pedir': 'j-', 'concatenated_bids_name': 'sub-DWI000_ses-A_run-1'}]
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 934, in build_qsiprep_workflow
    force_syn=opts.force_syn
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 273, in init_qsiprep_wf
    force_syn=force_syn)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 655, in init_single_subject_wf
    t1w_source_file=fix_multi_T1w_source_name(subject_data['t1w']),
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/utils/misc.py", line 22, in fix_multi_T1w_source_name
    base, in_file = os.path.split(filename_to_list(in_files)[0])
IndexError: list index out of range

Any suggestions would be greatly appreciated

**Comment by mattcieslak** [comment]
This bug looks familiar - could you list the contents of this participant's BIDS directory?

**Comment by pcamach2** [comment]
@mattcieslak Thanks for the help! The participant's BIDS directory contains only the four dwi files for one run, the PA and AP fieldmaps for that dwi run (with IntendedFor fields pointing at the .nii.gz in the dwi directory), and the scans .tsv file.
```

$ ls ../testing/DWI/bids/sub-DWI000/ses-A/*
../testing/DWI/bids/sub-DWI000/ses-A/sub-DWI000_ses-A_scans.tsv

../testing/DWI/bids/sub-DWI000/ses-A/dwi:
sub-DWI000_ses-A_run-1_dwi.bval  sub-DWI000_ses-A_run-1_dwi.bvec  sub-DWI000_ses-A_run-1_dwi.json  sub-DWI000_ses-A_run-1_dwi.nii.gz

../testing/DWI/bids/sub-DWI000/ses-A/fmap:
sub-DWI000_ses-A_acq-dwi_dir-AP_run-1_epi.json    sub-DWI000_ses-A_acq-dwi_dir-PA_run-2_epi.json
sub-DWI000_ses-A_acq-dwi_dir-AP_run-1_epi.nii.gz  sub-DWI000_ses-A_acq-dwi_dir-PA_run-2_epi.nii.gz
```

I tried changing both fieldmap filenames to "run-1" and subsequently also running with --ignore fieldmaps, but the error persists.

**Comment by mattcieslak** [comment]
@pcamach2 could you try from the pennbbl/qsiprep:unstable tag?

**Comment by pcamach2** [comment]
@mattcieslak Thanks! I'm rerunning with a singularity container built from pennbbl/qsiprep:unstable and the error has not occurred
