### ISSUE TITLE
Mix of single and multishell data in a session

### ISSUE THREAD

**Issue by ins0mniac2** [PennLINC/qsiprep#197]
If there is a multishell acquisition split into N files, qsiprep by default combines them for a single reconstruction. If, in addition, there is also a single shell acquisition, what will it do ? Do I have control over whether in that case we would like it to 1) either combine them all, or 2) separately process the singleshell data ? To me it seems like the --separate_all_dwis option is all or none ?

**Comment by ajschadler12** [comment]
Although it's been over a year, I'd like to provide an answer.

This might be a simple fix: try to provide an `acq-` label to your dwi file names.

e.g.
for single shell

`sub-001_acq-single_dir-AP_dwi.nii.gz`
`sub-001_acq-b1000_dir-AP_dwi.nii.gz`

for multi shell

`sub-001_acq-multi_dir-AP_dwi.nii.gz`
`sub-001_acq-b1000b2000_dir-AP_dwi.nii.gz`

You might find the `b1000b2000` label a bit more descriptive.

**Comment by mattcieslak** [comment]
It's been much more than a year now, but I might suggest it's not a good idea to combine single and multishell data into a single processing stream.

**Comment by cookpa** [comment]
I think this is another use case for BIDS filters
