### ISSUE TITLE
TotalReadoutTime and --ignore fieldmaps

### ISSUE THREAD

**Issue by ins0mniac2** [PennLINC/qsiprep#198]
If I understand correctly, TotalReadoutTime is needed for distortion correction. If I don't have it and choose to forego SDC with topup or fieldmaps and therefore "--ignore fieldmaps", qsiprep will still throw an error

  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/fmap.py", line 1005, in topup_inputs_from_4d_file
    spec_lookup[unique_dwi] = spec_line % spec['TotalReadoutTime']
TypeError: must be real number, not NoneType

**Comment by bwinsto2** [comment]
Not sure if this is useful for you, but I had to calculate TotalReadoutTime manually. [This link is helpful](https://lcni.uoregon.edu/kb-articles/kb-0003).

**Comment by mattcieslak** [comment]
qsiprep uses TotalReadoutTime for defining distortion groups, which determine which scans can be concatenated. It's a good idea to find out what this value is regardless of whether you're using distortion correction or not, but if you're really sure that it doesn't matter you could put a dummy number in there like 0.1.

**Comment by ins0mniac2** [comment]
Somehow didn't get a notification of replies, thanks both of you guys for responding. That link is indeed helpful but still not enough is available in the legacy data for us to calculate it. @mattcieslak : it's not that it doesn't matter, but I want to be able to process without it. From your suggestion, sounds like I can add a dummy value and still be able to process with "--ignore fieldmaps" so that qsiprep will not throw an error, but will continue to process without SDC.

**Comment by mattcieslak** [comment]
Please reopen if this issue comes up again, I believe it worked?
