### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsiprep#205]
Hi @mattcieslak 

Ran a dataset using the `--dwi-only` flag (QSIPrep 0.12.2) and it appears that everything ran as expected. However, the output naming for the preprocessed files still lists `space-T1w` which probably should be something else (e.g. `space-native` or `space-dwi`) since it is no specifically aligned to the T1.

**Comment by mattcieslak** [comment]
good point. What about space-ACPC?

**Comment by araikes** [comment]
That works for me as long as it works for you.

**Comment by tsalo** [comment]
lol I just noticed this. Looks like space-ACPC has been on the books for a long time now. Should be good to close since I merged #859.
