### ISSUE TITLE
Add DKI, DKI-Micro, MSDKI and SMT2 from DIPY

### ISSUE THREAD

**Issue by ShreyasFadnavis** [PennLINC/qsiprep#206]
It would be great to add Diffusion Kurtosis Imaging (DKI) and its variants from `DIPY`! 
A bunch of different measures can be derived from these models 💯 

@arokem what do you think? I can take the lead on this if that's okay 👍🏽

**Comment by arokem** [comment]
I think that it would be fantastic to have these available to qsiprep users! 

It does add two levels of complexity: the DKI model only works in multi-shell acquisitions (that's probably already sorted out here for other things), and it adds more configuration knobs that need to be set.

**Comment by mattcieslak** [comment]
I like this idea. @arokem or @ShreyasFadnavis do you know of a python-based sampling scheme classifier? 

I was thinking about adding a "ModelMix" reconstruction workflow that would attempt to detect what sampling scheme was used and then calculate an assortment of  scalar values from each.

**Comment by arokem** [comment]
We a couple of functions you could use to classify multi- vs. single-shell [here](https://github.com/dipy/dipy/blob/master/dipy/core/gradients.py#L793) and [here](https://github.com/dipy/dipy/blob/master/dipy/core/gradients.py#L714)

**Comment by mattcieslak** [comment]
these were added!
