### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'resolve'

### ISSUE THREAD

**Issue by AndrewYRevell** [PennLINC/qsiprep#207]
Hello,

Thanks for making qsiprep. I am getting an error message using docker, similar to a closed issue with singularity. However, I am not familiar with singularity enough to debug this issue. There was mention of a -w flag. (https://github.com/PennBBL/qsiprep/issues/62)

qsiprep-docker /media/arevell/sharedSSD/linux/papers/paper005/data/data_raw/imaging /media/arevell/sharedSSD/linux/papers/paper005/data/data_processed/imaging/sub-RID0278/ participant --output-resolution 1.2 --fs-license-file $FREESURFER_HOME/license.txt
['/home/arevell/anaconda3/envs/qsiprep/bin/qsiprep-docker', '/media/arevell/sharedSSD/linux/papers/paper005/data/data_raw/imaging', '/media/arevell/sharedSSD/linux/papers/paper005/data/data_processed/imaging/sub-RID0278/', 'participant', '--output-resolution', '1.2', '--fs-license-file', '/home/arevell/freesurfer/license.txt']
RUNNING: docker run --rm -it -v /home/arevell/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /media/arevell/sharedSSD/linux/papers/paper005/data/data_raw/imaging:/data:ro -v /media/arevell/sharedSSD/linux/papers/paper005/data/data_processed/imaging/sub-RID0278:/out pennbbl/qsiprep:0.12.2 /data /out participant --output-resolution 1.2
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
	1: [WARN] The recommended file /README is missing. See Section 03 (Modality agnostic files) of the BIDS specification. (code: 101 - README_FILE_MISSING)

	Please visit https://neurostars.org/search?q=README_FILE_MISSING for existing conversations about this issue.

        Summary:                Available Tasks:        Available Modalities: 
        98 Files, 1.34GB                                T1w                   
        8 - Subjects                                    dwi                   
        1 - Session                                     fieldmap              
                                                        fieldmap              

	If you have any questions, please post on https://neurostars.org/tags/bids.

Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 739, in build_qsiprep_workflow
    work_dir = opts.work_dir.resolve()
AttributeError: 'NoneType' object has no attribute 'resolve'
qsiprep: Please report errors to https://github.com/pennbbl/qsiprep/issues

**Comment by andyrevell** [comment]
Oh never mind, I'm an idiot. The -w flag is not singularity specific, but a qsiprep flag. It's the working directory for anyone else that comes across this. You may close this issue. It seems to be an "optional" argument like the freesurfer license.txt file path, but they are actually required (or the default location for $FREESURFER_HOME/license.txt is not actually looked up, so I have to manually specify the default it seems).

I just needed to add a -w flag specifying where intermediate files are stored to the end:

qsiprep-docker /media/arevell/sharedSSD/linux/papers/paper005/data/data_raw/imaging /media/arevell/sharedSSD/linux/papers/paper005/data/data_processed/imaging/ participant --output-resolution 1.2 --fs-license-file $FREESURFER_HOME/license.txt -w /media/arevell/sharedSSD/linux/papers/paper005/data/data_processed
