### ISSUE TITLE
Unable to run TOPUP: not enough distortion groups. Check "IntendedFor" fields or consider using --ignore fieldmaps.

### ISSUE THREAD

**Issue by melatonin914** [PennLINC/qsiprep#209]
Hello Happy new Year!

I have a subject with TOPUP and when I run qsiprep, I get the error " Unable to run TOPUP: not enough distortion groups. Check "IntendedFor" fields or consider using --ignore fieldmaps."

This is the error from the log file:
![image](https://user-images.githubusercontent.com/76848190/103444023-be513180-4c32-11eb-8468-068b9707d97f.png)

I have checked the "IntendedFor" fields of the epi.json files, and it seems to be pointing to the correct dwi file. This is the only subject that does not work in a group of subjects with the same imaging sequences.

![image](https://user-images.githubusercontent.com/76848190/103444059-125c1600-4c33-11eb-96eb-fa4ae5f07c00.png)

Would you guys be able to point me in the direction of how to trouble shoot this? It would be great to pinpoint a potential solution because a collaborator at another university is using the same acquisition files in case there is something amiss here. Thanks so much!

**Comment by mattcieslak** [comment]
Happy new year to you too! The first place I usually check is whether the `bids-validator` works. If so, I wonder if your epi fieldmap has the same phase encoding direction as the dwi image?

**Comment by tpatpa** [comment]
Hello!

I am experiencing the same issue.

![image](https://user-images.githubusercontent.com/24300712/134540368-86380287-4a7b-4f5d-8e0e-48e2ec441c6d.png)

@melatonin914, were you able to solve this?

@mattcieslak, I can confirm there are no errors with bids-validator@1.8.2.

Would anyone maybe have any idea what could be the issue?

I really appreciate any help you can provide!

**Comment by mattcieslak** [comment]
this is a very old issue, please reopen if you're still having trouble or would like to revisit
