### ISSUE TITLE
Weird rotation in T1w-space DWI

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsiprep#216]
Hi @mattcieslak,

I was preprocessing a bunch of data (QSIPrep 0.12.2) and ran across an odd issue with one of the subjects. The preprocessed DWI is rotated relative to the T1w (see screenshots below for the images from the report for the mask as well as b0-T1 registration and then screenshots of the preprocessed T1w image and dwiref in Mango). I've tried running through this person twice to no avail. This is the only person in the dataset with this issue.

It looks from the b0-T1 image in the report that they should be properly aligned but the dwiref image (and the full preprocessed dwi image) is clearly not. Any thoughts?

![Picture1](https://user-images.githubusercontent.com/18663624/105537252-e02c5a00-5cae-11eb-9baf-d15810287477.png)
![Picture2](https://user-images.githubusercontent.com/18663624/105537256-e1f61d80-5cae-11eb-97be-9bb2f6ab3e47.png)
![Picture3](https://user-images.githubusercontent.com/18663624/105537368-1073f880-5caf-11eb-926d-9a8e22ad24b8.png)
![preproc_T1w](https://user-images.githubusercontent.com/18663624/105537265-e4587780-5cae-11eb-9fd2-6c4e103903a4.png)
![T1w_dwiref](https://user-images.githubusercontent.com/18663624/105537275-e6223b00-5cae-11eb-8c81-da3fc5f907c0.png)

**Comment by araikes** [comment]
Hi @mattcieslak,

Bump on this just to see if you have a thought for it.

Thanks

**Comment by mattcieslak** [comment]
This looks strange. Are you able to view the two image in itk snap or afni?

**Comment by mattcieslak** [comment]
Please reopen if the issue resurfaces
