### ISSUE TITLE
Use existing PyBIDS Database

### ISSUE THREAD

**Issue by smeisler** [PennLINC/qsiprep#217]
Hello,

I usually run a QSIPrep job individually for each subject (`--participant-label` argument). However, when working with a large HCP dataset (>650 subjects), I find that QSIPrep stalls for a long time (over 24H) making the initial database for each job. Is there a way, similar to fMRIPrep's `--bids-databse-dir` argument, to specify an existing PyBIDS database to cut out the redundancy and increase efficiency on large datasets?

Thanks,
Steven

**Comment by mattcieslak** [comment]
This is definitely a big problem. We've been copying the single subject into a fake bids directory to speed this up, but obviously this is not ideal.
