### ISSUE TITLE
Mean Diffusivity

### ISSUE THREAD

**Issue by FL33TW00D** [PennLINC/qsiprep#221]
Hi there,
We have successfully processed and reconstructed some DSI scans using QSIPrep, so thank you for the great toolbox.

We are looking for a way to compute some structural connectomes with Mean Diffusivity as the metric, it seems all the current connectomes are computed using FA.

Is there anyway we can get this information?

Many Thanks,
Chris

**Comment by mattcieslak** [comment]
Hi Chris,

Glad to hear this is working for you! Which pipelines are you using? If a metric isn't calculated by default on the streamlines, you can usually get it from the reconstruction pipeline's outputs.

Also, if you're interested in trying out something new, you can use the csdsi_3dshore pipeline to get mrtrix metrics out of DSI inputs.

**Comment by FL33TW00D** [comment]
Hi Matt,
Thanks for coming back so quickly. We used 3DShore for the HMC due to our acquisition protocol and we used the `dsi_studio_gqi` for reconstruction.

We will attempt to the the `csdsi_3dshore` pipeline and see what outputs we get from it. We looked through the DSI Studio docs for any more information on the outputs but didn't have much luck.

Many Thanks,
Chris

**Comment by FL33TW00D** [comment]
> Hi Chris,
> 
> Glad to hear this is working for you! Which pipelines are you using? If a metric isn't calculated by default on the streamlines, you can usually get it from the reconstruction pipeline's outputs.
> 
> Also, if you're interested in trying out something new, you can use the csdsi_3dshore pipeline to get mrtrix metrics out of DSI inputs.

Hi @mattcieslak,
We've ran all applicable pipelines for our acquisition protocol, namely:
- dsi_studio_gqi
- dipy_mapmri
- dipy_3dshore
- csdsi_3dshore

All apart from GQI provide the following error:
traits.trait_errors.TraitError: Cannot set the undefined 'output_trk' attribute of a 'DSIStudioAtlasGraphInputSpec' object.

Any ideas on resolution for this? 

Many Thanks,
Chris

**Comment by mattcieslak** [comment]
Which version are you using? This error should be gone in recent versions (eg https://github.com/PennBBL/qsiprep/blob/master/qsiprep/data/pipelines/dsi_studio_gqi.json has no output_trk entry)

**Comment by FL33TW00D** [comment]
> Which version are you using? This error should be gone in recent versions (eg https://github.com/PennBBL/qsiprep/blob/master/qsiprep/data/pipelines/dsi_studio_gqi.json has no output_trk entry)

Hi @mattcieslak ,
We ran with version 12.2.

It seems that all pipelines apart from `dsi_studio_gqi` have an `output_trk `parameter. We have successfully run  `dsi_studio_gqi` but would love to use another to get access to MD metrics. Since all other 3 have the `output_trk` field we receive the same error.

Many Thanks,
Chris

**Comment by mattcieslak** [comment]
There are some updates in 0.13.0RC1 that should fix this problem. You might also want to download one of the current pipeline jsons and supply it as the argument to `--recon-spec`
