### ISSUE TITLE
Unable to run qsiprep in using docker or docker-wrapper

### ISSUE THREAD

**Issue by QuintinFrerichsWUSTL** [PennLINC/qsiprep#222]
After running qsiprep using the command: 
sudo python /home/quintin_frerichs/.local/lib/python3.6/site-packages/qsiprep_docker.py /home/quintin_frerichs/data/ds001590-download  /home/quintin_frerichs/data/qsiprep-output participant --participant_label sub-01 --output-resolution 1.3 --fs-license-file=/home/quintin_frerichs/license.txt

I get the following error:

raceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 739, in build_qsiprep_workflow
    work_dir = opts.work_dir.resolve()
AttributeError: 'NoneType' object has no attribute 'resolve'
qsiprep: Please report errors to https://github.com/pennbbl/qsiprep/issues

**Comment by mattcieslak** [comment]
Could you try adding a -w argument with the working directory? This is a super unhelpful error message on my part, sorry about that

**Comment by QuintinFrerichsWUSTL** [comment]
@mattcieslak thank you!! Was stuck on that for so long.
