### ISSUE TITLE
What would I do with qsiprep-singularity?

### ISSUE THREAD

**Issue by kodiweera** [PennLINC/qsiprep#235]
Hi,
I installed "$ pip install --user --upgrade qsiprep-container" after buildinga singularity box (.sif). How do I use 'qsiprep-singularity' once I have built the singularity box. It's not clear from https://qsiprep.readthedocs.io/en/latest/usage.html#the-singularity-wrapper-cli.

Why there is 'qsiprep-docker' under the singularity-wrapper-cli? Is there a typo?

Thank you.

**Comment by mattcieslak** [comment]
Hi @kodiweera, The singularity and docker wrappers are included in the same python package. You use them in exactly the same way except for `qsiprep-docker` you use `--image /path/to/my_container.sif` to specify where to find the container. That's definitely a typo in the documentation.
