### ISSUE TITLE
Is this just a labeling error in the output html?

### ISSUE THREAD

**Issue by kodiweera** [PennLINC/qsiprep#236]
Hi,
I believe this is just a typo in the output html file. I used **patch2self** as the denoise method. But, in the output html file, it says "MP-PCA denoising".  Is it really a typo? The command used is:

_**"singularity run ~/qsiprep/qsiprep-0.13.0RC1.sif ~/qsiprep/data/ ~/qsiprep/out/ participant -w ~/qsiprep/work/ --output-resolution 1.4 --fs-license-file ~/qsiprep --denoise-method patch2self --unringing-method mrdegibbs --no-b0-harmonization --nthreads 16"**_

Copied from the html:
**Denoising
MP-PCA denoising
Effect of MP-PCA denoising on a low and high-b image.**

Thank you

**Comment by mattcieslak** [comment]
Yes these are also leftovers from when mp-pca was the only denoising option in qsiprep. You definitely got patch2self applied and those images reflect its performance
