### ISSUE TITLE
Reading Transforms output by qsiprep in python

### ISSUE THREAD

**Issue by 36000** [PennLINC/qsiprep#237]
Hi,
    I work on pyAFQ which performs tractometry entirely using python. We want give the user the option to use the transforms generated by QSIprep instead of the transforms generated by pyAFQ. So, I am trying to load and apply the transforms entirely in python.
    In the "..._from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5" file, I see three different mappings: "CompositeTransform", "DisplacementFieldTransform", and "AffineTransform". "CompositeTransform" seems to be empty. I am hoping I can just take the data from the displacement field and affine, apply those in some order using Dipy, and thus it will work all in python.
    I am wondering if anyone has any experience applying these transforms in python, or if anyone could shed some light on what each of these transforms do.

Thank You!

**Comment by 36000** [comment]
I believe I figured out a way to do this, see the linked PR. Still interested in any comments about the 3 transforms (ie, I am still not sure what the "CompositeTransform" does).

**Comment by mattcieslak** [comment]
I think this works now? Please reopen if not!
