### ISSUE TITLE
Why --resample-resolution mandotory?

### ISSUE THREAD

**Issue by kodiweera** [PennLINC/qsiprep#240]
All I want is my dwi are in the T1 space with the same dimensions after preprocessing. With the mandotory flag, --resample-resolution, it's not gonna happen. Am I missing something? How do I trun that flag off? Thank you.

**Comment by mattcieslak** [comment]
What is the critical advantage of having non-isotropic voxels? If the head was rotated during motion correction, which it surely will be, then the signal-by-axis mismatch will be even worse if the images are resampled into another non-isotropic resolution. I agree with 6 and 7 here: https://dipy.org/documentation/1.4.0./faq/.

**Comment by kodiweera** [comment]
I want to use T1 masks with dwi. What's point of resampling dwi after regirtration to T1 space? Maybe, firstly T1 should be resampled to have isotropic voxels and then register dwi to T1-space.

**Comment by kodiweera** [comment]
> What is the critical advantage of having non-isotropic voxels? If the head was rotated during motion correction, which it surely will be, then the signal-by-axis mismatch will be even worse if the images are resampled into another non-isotropic resolution. I agree with 6 and 7 here: https://dipy.org/documentation/1.4.0./faq/.

By the way, my original dwi are isotropic ( 2mm iso)

**Comment by mattcieslak** [comment]
QSIPrep dwi outputs will always have isotropic voxels with the voxel size specified by --output-resolution. They are aligned with the t1w images in world coordinates, not voxels. You can resample the T1w brain mask into the dwi resolution.

**Comment by kodiweera** [comment]
> QSIPrep dwi outputs will always have isotropic voxels with the voxel size specified by --output-resolution. They are aligned with the t1w images in world coordinates, not voxels. You can resample the T1w brain mask into the dwi resolution.

Nice! is there a option in qsiprep to resample back? What do yo suggest for this? Thank you.

**Comment by mattcieslak** [comment]
I would recommend this: https://nilearn.github.io/modules/generated/nilearn.image.resample_to_img.html#nilearn.image.resample_to_img

with interpolation set to "nearest"

**Comment by kodiweera** [comment]
> I would recommend this: https://nilearn.github.io/modules/generated/nilearn.image.resample_to_img.html#nilearn.image.resample_to_img
> 
> with interpolation set to "nearest"

Thank you, Matt.
