### ISSUE TITLE
 Error on "qsirecon_wf.sub-control01_mrtrix_singleshell_ss3t.anat_ingress_wf.create_5tt"

### ISSUE THREAD

**Issue by m-petersen** [PennLINC/qsiprep#246]
Dear Developers,

I am trying to deploy a qsiprep singularity container on our local HPC. Currently, I am stuck with an error regarding 5ttgen.

**Version of qsiprep** 
0.13.0RC2
I also tried containers corresponding with 0.12.2 and 0.13.0RC1 resulting in the same errors.

**Command**
>singularity run --cleanenv --userns -B $proj_dir:/home/qsiprep\
    --home /home/qsiprep\
    -B $env_dir:/mnt \
    -B $bids_dir:/sngl/data \
    -B $deriv_dir:/sngl/out \
    -B $deriv_dir/qsiprep:/sngl/qsiprep-output \
    -B $scratch_dir:/sngl/scratch \
    -B $env_dir:/sngl/env \
    $env_dir/qsiprep-0.13.0RC2 \
    /sngl/data /sngl/qsiprep-output participant \
    -w /sngl/scratch/ \
    --participant-label ${subjs_subarr[@]} \
    --recon_input /sngl/out/qsiprep \
    --recon_spec mrtrix_singleshell_ss3t \
    --nthreads 16 \
    --fs-license-file /sngl/env/freesurfer_license.txt \
    --output-resolution 1.3

$proj_dir, $env_dir, $bids_dir, $deriv_dir relate to directories on a /work partition I have writing permission on
$scratch_dir relates to a /scratch partition mounted temporarily by the compute node.
My inputs are BIDS validated. I use singularity 3.5.2 on a CentOS Cluster

**Traceback**
> [Node] Error on "qsirecon_wf.sub-control01_mrtrix_singleshell_ss3t.anat_ingress_wf.create_5tt" (/sngl/scratch/qsirecon_wf/sub-control01_mrtrix_singleshell_ss3t/anat_ingress_wf/create_5tt)
210421-16:17:53,857 nipype.workflow ERROR:
	 Node create_5tt failed to run on host node139.
210421-16:17:53,885 nipype.workflow ERROR:
	 Saving crash info to /sngl/qsiprep-output/qsirecon/sub-control01/log/20210421-155213_5879dc8f-7f81-4bdd-a663-c33f17dd6bef/crash-20210421-161753-fatx405-create_5tt-b558501f-342a-48c6-8873-7fecb0f5069a.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 829, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 760, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
5ttgen fsl /sngl/out/qsiprep/sub-control01/anat/sub-control01_desc-preproc_T1w.nii.gz sub-control01_desc-preproc_T1w_5tt.mif -mask /sngl/out/qsiprep/sub-control01/anat/sub-control01_desc-brain_mask.nii.gz
Standard output:

> Standard error:
5ttgen: 
5ttgen: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.
5ttgen: 
5ttgen: Generated temporary directory: /sngl/scratch/qsirecon_wf/sub-control01_mrtrix_singleshell_ss3t/anat_ingress_wf/create_5tt/5ttgen-tmp-156GT5/
Command:  mrconvert /sngl/out/qsiprep/sub-control01/anat/sub-control01_desc-preproc_T1w.nii.gz /sngl/scratch/qsirecon_wf/sub-control01_mrtrix_singleshell_ss3t/anat_ingress_wf/create_5tt/5ttgen-tmp-156GT5/input.mif
Command:  mrconvert /sngl/out/qsiprep/sub-control01/anat/sub-control01_desc-brain_mask.nii.gz /sngl/scratch/qsirecon_wf/sub-control01_mrtrix_singleshell_ss3t/anat_ingress_wf/create_5tt/5ttgen-tmp-156GT5/mask.mif -datatype bit -strides -1,+2,+3
5ttgen: Changing to temporary directory (/sngl/scratch/qsirecon_wf/sub-control01_mrtrix_singleshell_ss3t/anat_ingress_wf/create_5tt/5ttgen-tmp-156GT5/)
Command:  mrconvert input.mif T1.nii -strides -1,+2,+3
Command:  mrcalc T1.nii mask.mif -mult T1_masked.nii.gz
Command:  fast T1_masked.nii.gz
Command:  run_first_all -m none -s L_Accu,R_Accu,L_Caud,R_Caud,L_Pall,R_Pall,L_Puta,R_Puta,L_Thal,R_Thal -i T1.nii -o first
5ttgen: Generating partial volume images for SGM structures... [=======================================================]
Command:  mrmath mesh2voxel_L_Accu.mif mesh2voxel_R_Accu.mif mesh2voxel_L_Caud.mif mesh2voxel_R_Caud.mif mesh2voxel_L_Pall.mif mesh2voxel_R_Pall.mif mesh2voxel_L_Puta.mif mesh2voxel_R_Puta.mif mesh2voxel_L_Thal.mif mesh2voxel_R_Thal.mif sum - | mrcalc - 1.0 -min all_sgms.mif
5ttgen: 
5ttgen: [ERROR] Command failed: mrmath mesh2voxel_L_Accu.mif mesh2voxel_R_Accu.mif mesh2voxel_L_Caud.mif mesh2voxel_R_Caud.mif mesh2voxel_L_Pall.mif mesh2voxel_R_Pall.mif mesh2voxel_L_Puta.mif mesh2voxel_R_Puta.mif mesh2voxel_L_Thal.mif mesh2voxel_R_Thal.mif sum - | mrcalc - 1.0 -min all_sgms.mif (fsl.py:175)
5ttgen: Output of failed command:
mrmath: computing sum across 10 images...  [==========]
mrmath: [SYSTEM FATAL CODE: SIGBUS (7)] Bus error: Accessing invalid address (out of storage space?)
mrcalc: [ERROR] Could not interpret string "-" as either an image path or a numerical value
5ttgen: 
5ttgen: Changing back to original directory (/sngl/scratch/qsirecon_wf/sub-control01_mrtrix_singleshell_ss3t/anat_ingress_wf/create_5tt)
5ttgen: Script failed while executing the command: mrmath mesh2voxel_L_Accu.mif mesh2voxel_R_Accu.mif mesh2voxel_L_Caud.mif mesh2voxel_R_Caud.mif mesh2voxel_L_Pall.mif mesh2voxel_R_Pall.mif mesh2voxel_L_Puta.mif mesh2voxel_R_Puta.mif mesh2voxel_L_Thal.mif mesh2voxel_R_Thal.mif sum - | mrcalc - 1.0 -min all_sgms.mif
5ttgen: For debugging, inspect contents of temporary directory: /sngl/scratch/qsirecon_wf/sub-control01_mrtrix_singleshell_ss3t/anat_ingress_wf/create_5tt/5ttgen-tmp-156GT5/
Return code: 1

Thanks in advance for your help. Happy to provide further information.

**Comment by mattcieslak** [comment]
It looks like /sngl/scratch is out of space. Are you able to request an amount of local scratch space per job?

**Comment by m-petersen** [comment]
Hi Matt,

thanks a lot for your reply. 90gb of /scratch space are assigned to every job. I contacted the HPC admins and according to them there is no storage problem with /scratch. Maximally 12gb of the 90gb are occupied when the error occurs.

**Comment by mattcieslak** [comment]
could you try something like
```
mkdir $scratch_dir/tmp

singularity run --cleanenv --userns -B $proj_dir:/home/qsiprep
--home /home/qsiprep
-B $env_dir:/mnt
-B $bids_dir:/sngl/data
-B $deriv_dir:/sngl/out
-B $deriv_dir/qsiprep:/sngl/qsiprep-output
-B $scratch_dir:/sngl/scratch
-B $env_dir:/sngl/env
-B $scratch_dir/tmp:/tmp
$env_dir/qsiprep-0.13.0RC2
/sngl/data /sngl/qsiprep-output participant
-w /sngl/scratch/
--participant-label ${subjs_subarr[@]}
--recon_input /sngl/out/qsiprep
--recon_spec mrtrix_singleshell_ss3t
--nthreads 16
--fs-license-file /sngl/env/freesurfer_license.txt
--output-resolution 1.3
```

It's possible that the /tmp directory on the compute node is being directly mounted in the container and has a smaller capacity than your scratch directory

**Comment by m-petersen** [comment]
Thanks again for your advice. Indeed, only 25mb were assigned to /tmp on the HPC. I solved the problem by setting MRTRIX_TMPFILE_DIR=/scratch during the batchjob.
