### ISSUE TITLE
Rename Denoising in Report Generated

### ISSUE THREAD

**Issue by ShreyasFadnavis** [PennLINC/qsiprep#255]
Hi,

I noticed an issue in the report generated:

This needs to be changed from MP-PCA denoising to "Denoising". For instance, if I use Patch2Self, it still shows MP-PCA denoising:
https://github.com/PennLINC/qsiprep/blob/cd6a9605691d0c66e746b0c36d1e9020ee0bf66d/qsiprep/viz/config.json#L80

I can make a quick PR for this @mattcieslak !

**Comment by mattcieslak** [comment]
Thanks, this is definitely a bug
