### ISSUE TITLE
Eddy Error AcqPara: Unrealistic read-out time(ds002330)

### ISSUE THREAD

**Issue by tatsuya-0623** [PennLINC/qsiprep#260]
Hello all,

I am having an issue of preprocessing DWI data of ds002330(only sub-01) (Neuroimaging predictors of creativity in healthy adults) with QSIprep.

Before preprocessing, I copied “acq-lr_dwi.json” and “acq-rl_dwi.json” in BIDS root folder to sub-01/dwi folder.

HOWEVER, I have an issue in Eddy processing, which claim that EPI total readout time of your data is not “realistic” .

So, I can’t perform preprocessing this data.(can preprocess other data with QSIprep)

“”"
RuntimeError: Command:
eddy_openmp --cnr_maps --field=/scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_wf/hmc_sdc_wf/topup/fieldmap_HZ --field_mat=/scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_wf/hmc_sdc_wf/topup_to_eddy_reg/topup_reg_image_flirt.mat --flm=linear --ff=10.0 --acqp=/scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_wf/hmc_sdc_wf/gather_inputs/eddy_acqp.txt --bvals=/scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_wf/pre_hmc_wf/rpe_concat/merge__merged.bval --bvecs=/scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_wf/pre_hmc_wf/rpe_concat/merge__merged.bvec --imain=/scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_wf/pre_hmc_wf/rpe_concat/merge__merged.nii.gz --index=/scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_wf/hmc_sdc_wf/gather_inputs/eddy_index.txt --mask=/scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_wf/hmc_sdc_wf/pre_eddy_b0_ref_wf/enhance_and_mask_b0/topup_imain_corrected_avg_mask.nii.gz --interp=spline --data_is_shelled --resamp=jac --niter=5 --nvoxhp=1000 --out=/scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_wf/hmc_sdc_wf/eddy/eddy_corrected --repol --slm=linear
Standard output:
EDDY::: AcqPara::AcqPara: Unrealistic read-out time
EDDY::: EddyHelperClasses.cpp::: EDDY::AcqPara::AcqPara(const ColumnVector&, double): Exception thrown
EDDY::: Eddy failed with message EDDY::: ECScanClasses.cpp::: EDDY::ECScanManager::ECScanManager(const string&, const string&, const string&, const string&, const string&, const string&, const string&, const string&, EDDY::ECModel, EDDY::ECModel, const std::vector&, const EDDY::PolationPara&, EDDY::MultiBandGroups, bool): Exception thrown
Standard error:
“”"
For your information, TotalReadoutTime in this data is 0.000910s

Thank you in advance.

**Comment by mattcieslak** [comment]
This seems to be something that's popping up a lot 

 * https://neurostars.org/t/stuck-when-run-qsiprep-on-hcp-data/19599/14
 * https://neurostars.org/t/what-is-the-totalreadouttime-of-hcp-dwi-data/19622

I wonder if we should open a PR on the BIDS spec to better explain what these values should be

**Comment by tatsuya-0623** [comment]
Thank you, I'll refer to your suggestion.
