### ISSUE TITLE
Brain atlases not registering correctly to the MNI brain or T1w brain

### ISSUE THREAD

**Issue by akelkar26** [PennLINC/qsiprep#267]
Hi, 
I had a special case of data for which I used only the dwi-only preprocessing from qsiprep and then wrote my own anat pipeline. I gave them as inputs to the reconstruction workflow. 

I noticed that the brain atlases are misregistered to the MNI brain and the subject T1w brain. 

I found the MNI brain template at:
http://nist.mni.mcgill.ca/icbm-152-nonlinear-atlases-2009/ as mentioned on the QSIPrep help page. 

I used the one mentioned on the help page in nifti format. I used the ICBM 2009c Nonlinear Asymmetric
1×1x1mm template. 

I didn't find an extracted MNI brain so ran ANTsRegistration on the template with the following command:

antsBrainExtraction.sh -d 3 -a /Users/neurouser1/Documents/MNITemplateQSIPrep/mni_icbm152_nlin_asym_09c_nifti/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c.nii -e /Users/neurouser1/Documents/MNITemplateQSIPrep/mni_icbm152_nl
in_asym_09c_nifti/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c.nii -m /Users/neurouser1/Documents/MNITemplateQSIPrep/mni_icbm152_nlin_asym_09c_nifti/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_mask.nii -o /Us
ers/neurouser1/Documents/TMS_Aphasia/ANTsAnatPipeline/sub-${sub}/anat/sub-${sub}_T1w_MNIbrain

I changed the orientation of the extracted MNI brain and brain mask to LPS and then tried to overlay the atlases found on Box to the extracted MNI brain. 

I see that the Aicha or the Brainnetome don't conform as well to the White matter. 
Similarly, the Gordon doesn't conform as well to the Gray matter and the Schaefer to the cortex

Aicha MNI atlas:

![Capture_Aicha_MNI](https://user-images.githubusercontent.com/40644674/124670487-0e2ee080-de82-11eb-9a86-bdb1a031c54f.PNG)

Brainnetome MNI atlas:

![Capture_Brainnetome_MNI](https://user-images.githubusercontent.com/40644674/124670509-1555ee80-de82-11eb-9869-5bee3032058c.PNG)

Gordon MNI atlas:

![Capture_Gordon_MNI](https://user-images.githubusercontent.com/40644674/124670528-1d159300-de82-11eb-97ea-43e1d795b5fe.PNG)

Schaefer MNI atlas:

![Capture_Schaefer_MNI](https://user-images.githubusercontent.com/40644674/124670887-a0cf7f80-de82-11eb-8e6e-4e98d5e3a0d5.PNG)

This is before running the reconstruction pipeline to compute the tractography. 

I had then done the MNI to T1w registration (and also the T1w to MNI registration) with the following commands:

antsRegistrationSyn.sh -d 3 -f /Users/neurouser1/Documents/TMS_Aphasia/DWIPreprocPipeline/sub-${sub}/dwi/sub-${sub}_desc-preproc_T1w.nii.gz -m /Users/neurouser1/Documents/TMS_Aphasia/ANTsAnatPipeline/sub-${sub}/anat/sub-${sub}_T1w_MNIbrainBrainExtractionBrain.nii.gz -o /Users/neurouser1/Documents/TMS_Aphasia/ANTsAnatPipeline/sub-${sub}/anat/space-MNI152NLin2009cAsym_sub-${sub}

I got the .h5 file with the following command  (also for the T1w-MNI registration):

CompositeTransformUtil --assemble /Users/neurouser1/Documents/TMS_Aphasia/ANTsAnatPipeline/sub-${sub}/anat/sub-${sub}_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5 /Users/neurouser1/Documents/TMS_Aphasia/ANTsAnatPipeline/sub-${sub}/anat/space-MNI152NLin2009cAsym_sub-${sub}0GenericAffine.mat /Users/neurouser1/Documents/TMS_Aphasia/ANTsAnatPipeline/sub-${sub}/anat/space-MNI152NLin2009cAsym_sub-${sub}1Warp.nii.gz

After the tractography, the problem seems to persist when the atlas moves to the T1w. 

Aicha T1w atlas:

![Capture_Aicha_T1w](https://user-images.githubusercontent.com/40644674/124671392-63b7bd00-de83-11eb-9e09-30dd516fbb23.PNG)

Gordon T1w atlas:

![Capture_Gordon_T1w](https://user-images.githubusercontent.com/40644674/124671463-81852200-de83-11eb-9274-669933f53d6d.PNG)

Schaefer T1w atlas:

![Capture_Schaefer_T1w](https://user-images.githubusercontent.com/40644674/124671480-8944c680-de83-11eb-9825-3a3b5b3f09ca.PNG)

Could you please inform me what could be causing the issue?
Your help is greatly appreciated.

Thank you
Best,
Apoorva

**Comment by mattcieslak** [comment]
The slight differences in coverage on the template image are expected. Some of these atlases are surfaces parcellations mapped into volumes and others are made on different iterations of the MNI template. As long as there is decent overlap of the regions with the gm/wm interface you will still assign streamlines correctly to the regions, even if they don't cover the entire gm surface.

**Comment by akelkar26** [comment]
Hi Matt,

This makes sense to me now. 
I see the slight differences in my T1w atlas registration as well. Is this expected then or is there something wrong with my MNI to T1w registration step?

Thank you
Best,
Apoorva
