### ISSUE TITLE
QSIprep Mac - nothing happens

### ISSUE THREAD

**Issue by dubergonzoni** [PennLINC/qsiprep#275]
Dear @mattcieslak

I'm trying to run QSIprep with Mac OS High Sierra.
It seems that not is happening after running the code. I have started almost 6 hours ago and there's not going on the terminal and there's no output file. I think I'm doing right based on data preprocessed with QSIprep in my Ubuntu notebook. 

QSIprep generated only tmp files in my Ubuntu and I got an memory failure. For this reason I'm trying with more RAM.

Follow the code an an image of the terminal after running:

docker run -ti --rm -v /Users/brainsmclab/freesurfer/license.txt:/fslicense.txt:ro -v /Users/brainsmclab/Documents/Eduardo/qsiprep:/data:ro -v /Users/brainsmclab/Documents/Eduardo/qsiprep/outputs:/out pennbbl/qsiprep:latest /data /out participant --output-resolution 1.2 --fs-license-file /fslicense.txt -w /out/tmp

![qsiprep_mac](https://user-images.githubusercontent.com/50045444/125611244-1c951e2d-92e8-4452-bf92-5eff1784b329.png)

Sincerely,
Eduardo

**Comment by pcamach2** [comment]
Hi Eduardo,

I'm sure Matt will have better suggestions, but you may want to try the --low-mem option if the RAM is still an issue.

Some issues that resemble memory failures can occur if files are not found in the directories where they are expected. If I understand correctly, the command was intended to run the QSIprep preprocessing routine. Is /Users/brainsmclab/Documents/Eduardo/qsiprep/ the root BIDS directory for this dataset (i.e. contains original converted NIFTIs for sub-ID/ses-ID/dwi anat fmap) or the outputs of a prior preprocessing run? This may not be the source of the issue, but I keep the root BIDS directory labeled bids and place the qsiprep outputs in bids/derivatives/qsiprep; mounting bids to /data and bids/derivatives/qsiprep to /out.

Cheers,
Paul

**Comment by dubergonzoni** [comment]
Dear @pcamach2  and @mattcieslak 
I'm so sorry for the late reply. I will be back to the data in the next week and I will let you know if the suggestions will be successful.

The command is intended to run QSIprep preprocessing. I'm using the root BIDS directory, I just named it in a confusing way. Sorry about that.

Best,
Eduardo

**Comment by mattcieslak** [comment]
you can also see a lot more printed out if you add -v flags. I usually run it with -v -v
