### ISSUE TITLE
Specify a session for QSIPrep to process

### ISSUE THREAD

**Issue by meet10may** [PennLINC/qsiprep#282]
Hi Matt,

I am able to run QSIprep on my dataset and it seems to be work. However, I have subjects with multiple sessions. Is there a way I can specify a session to process while ignoring the other?

Thanks!

**Comment by mattcieslak** [comment]
You can specify a text file as an argument to `--bids-filter-file` that selects for the session you want to process. There is some documentation we're failing to get on readthedocs right now, but you can see it for now [here](https://6820-156589095-gh.circle-artifacts.com/0/tmp/src/qsiprep/docs/_build/html/preprocessing.html#using-bids-filters). We run one session at a time by using one filter file per session.

**Comment by mattcieslak** [comment]
You can specify a text file as an argument to `--bids-filter-file` that selects for the session you want to process. There is some documentation we're failing to get on readthedocs right now, but you can see it for now [here](https://6820-156589095-gh.circle-artifacts.com/0/tmp/src/qsiprep/docs/_build/html/preprocessing.html#using-bids-filters). We run one session at a time by using one filter file per session.
