### ISSUE TITLE
The output FA image shows too many high value spots

### ISSUE THREAD

**Issue by aghayoor** [PennLINC/qsiprep#284]
Hi team,

I ran the qsiprep with `--recon_spec dsi_studio_gqi`.
Here is the full command line:

> qsiprep-docker $datadir/BIDS/ $outdir participant --recon_spec dsi_studio_gqi --participant-label 01 --output-resolution 2 --fs-license-file ./fs_license.txt --verbose --verbose --  stop-on-first-crash

All DTI metrics are generated in `/qsirecon/dwi/` directory.
However, the output FA image shows several high value spots scattered all over the image. A screenshot of all views is attached here.

I appreciate your help and comments here.

Thanks,
Ali

![qsirecon_FA](https://user-images.githubusercontent.com/926354/128264315-20ac00c7-9dde-4c59-afce-28b344d52e32.png)

**Comment by aghayoor** [comment]
Hi @mattcieslak ,

Do you have any idea about the issue reported here?
Also, I am interested to get the colorFA, which of the default `recon_spec`s do you recommend to use?
I have attached the .json file of the raw dwi here.

Thanks,
Ali

[sub-01_run-01_dwi.json.txt](https://github.com/PennLINC/qsiprep/files/6942012/sub-01_run-01_dwi.json.txt)

**Comment by mattcieslak** [comment]
The high values of FA are from poor model fits, I believe. I don't have a recon spec that creates a colorFA file. If you're looking to do DTI-centric analysis, you can use the `--recon-spec reorient_fslstd` and run them through the FSL tools.
