### ISSUE TITLE
cannot track output of --out_assignments in tck2connectome 

### ISSUE THREAD

**Issue by sebnaze** [PennLINC/qsiprep#290]
Hi Matt & al.

First thanks for the effort put to build QSIPrep, it's awesome!

I've been trying to output the track assignment to ROI parcellation in `tck2connectome` using the `--out_assignments assignments.txt` option (via recon json config file), i.e.
```
       "tck2connectome": [
              {
                "use_sift_weights": false,
                "zero_diagonal": false,
                "search_radius": 2.0,
                "symmetric": true,
                "stat_edge": "sum",
                "measure": "count_nosift",
                "nthreads": 32,
                "out_assignments": "assignments.txt"
              }, 
              ...
```
the command is executed and runs fine however I can't find the output text file anywhere (neither in the scratch's calc_connectivity folder, derivatives... home folder, tmp folder,  cwd), it's nowhere.

 I see in the command that the `--out_assignments ` output folder is strictly `assignments.txt` and is missing the scratch path `/sngl/scratch/...`  (I'm running on singularity)
Any hints how to fix this? (I checked the qsiprep.interfaces.mrtrix.py and related nipype Traits and File but couldn't get my head around how to get it to work).
 
 Thanks!

**Comment by mattcieslak** [comment]
hi @sebnaze could you post your singularity command?

**Comment by sebnaze** [comment]
Hi @mattcieslak , 

Following up on that, the singularity command is 
`singularity run --cleanenv -B /software/freesurfer/freesurfer-6.0.1:/mnt -B /mnt/lustre/working/projects/baseline/data/bids:/sngl/data -B /mnt/lustre/working/projects/baseline/docs/code/preprocessing:/sngl/spec -B /mnt/lustre/working/projects/baseline/data/derivatives:/sngl/out -B /mnt/lustre/working/parcellations/:/atlas/qsirecon_atlases -B /mnt/lustre/working/projects/baseline/data/scratch/qsiprep:/sngl/scratch /mnt/lustre/working/qsiprep-0.13.0.sif /sngl/data /sngl/out participant --fs-license-file /mnt/license.txt --recon-spec /sngl/spec/qsiprep_recon_file.json --participant-label sub-control22 --dwi_denoise_window 5 --output-space T1w --output-resolution 2 --hmc-model eddy --mem-mb 48000 --nthreads 32 --verbose -w /sngl/scratch`


From the log, the `tck2connectome` command that ran is:
`tck2connectome -tck_weights_in /sngl/scratch/qsirecon_wf/sub-control22_mrtrix_multishell_msmt_version2020/recon_wf/track_ifod2_dhollander/_dwi_file_..sngl..out..qsiprep..sub-control22..dwi..sub-control22_acq-88_dir-AP_space-T1w_desc-preproc_dwi.nii.gz/tck_sift2/sub-control22_acq-88_dir-AP_space-T1w_desc-preproc_dwi_wm_mtnorm_weights.csv -nthreads 32 -out_assignments tck_assignements.txt -assignment_radial_search 2.000000 -stat_edge sum -symmetric /sngl/scratch/qsirecon_wf/sub-control22_mrtrix_multishell_msmt_version2020/recon_wf/track_ifod2_dhollander/_dwi_file_..sngl..out..qsiprep..sub-control22..dwi..sub-control22_acq-88_dir-AP_space-T1w_desc-preproc_dwi.nii.gz/tractography/tracked.tck /sngl/scratch/qsirecon_wf/sub-control22_mrtrix_multishell_msmt_version2020/recon_wf/_dwi_file_..sngl..out..qsiprep..sub-control22..dwi..sub-control22_acq-88_dir-AP_space-T1w_desc-preproc_dwi.nii.gz/get_atlases/schaefer200x7MNI_lps_to_dwi.mif connectome.csv`

From my understanding, `connectome.csv` and `tck_assignments.txt` are only stored temporarily within the container so I try to understand how could I save them in my workflow directory in scratch (I'm new to nipype and I haven't got my head around the whole wf, interfaces,  traits, etc.)

Thanks for any insight!
Seb

ps: I've also noticed that whether we set the flag "use_sift_weights" to true or false in the config json file, `tck2connectome` seems to always use -tck_weights_in, so even using sift weights when it is actually specified not to.

**Comment by vnckppl** [comment]
I ran into the same issue (not being able to write out the assignments.txt file). You can however mount the container's `/workdir` folder to your local machine. There, I did find the assigments file.

**Comment by mattcieslak** [comment]
Is sounds like the assignments.txt is a file that would be useful to add to the derivatives?

**Comment by vnckppl** [comment]
Yes, as that file is neccesary for extracting individual ROI-to-ROI tracts from the connectome (using `connectome2tck`), which is useful for quality control and creating figures.

**Comment by mattcieslak** [comment]
@vnckppl which version of qsiprep are you using? As of 0.16.0 there is a connectome2tck results directory included in the mrtrix outputs

**Comment by mattcieslak** [comment]
they're archived in `sub-TEST_space-T1w_desc-preproc_desc-exemplarbundles_dhollanderconnectome.zip`!

**Comment by vnckppl** [comment]
Thanks, that helps. I do think it would be helpful to save the assignments.txt file to this archive.
