### ISSUE TITLE
Gradients or original files don't match 

### ISSUE THREAD

**Issue by hchen115** [PennLINC/qsiprep#292]
Hi @mattcieslak,

I got the following crash report when running qsiprep 0.14.2 for dsi data collected with two runs and a fieldmap:

> Node: qsiprep_wf.single_subject_BR371_wf.dwi_preproc_ses_1_dir_AP_wf.confounds_wf.concat
Working directory: /tmp/work/qsiprep_wf/single_subject_BR371_wf/dwi_preproc_ses_1_dir_AP_wf/confounds_wf/concat
>
>Node inputs:
>
>denoising_confounds = /tmp/work/qsiprep_wf/single_subject_BR371_wf/dwi_preproc_ses_1_dir_AP_wf/pre_hmc_wf/merge_and_denoise_wf/merge_dwis/dwi_denoise_ses_1_dir_AP__merged_confounds.csv
fd = /tmp/work/qsiprep_wf/single_subject_BR371_wf/dwi_preproc_ses_1_dir_AP_wf/confounds_wf/fdisp/fd_power_2012.txt
motion = /tmp/work/qsiprep_wf/single_subject_BR371_wf/dwi_preproc_ses_1_dir_AP_wf/confounds_wf/add_motion_headers/eddy_correctedspm_rp_motion.tsv
original_bvals = ['/tmp/work/qsiprep_wf/single_subject_BR371_wf/dwi_preproc_ses_1_dir_AP_wf/pre_hmc_wf/merge_and_denoise_wf/merge_dwis/dwi_denoise_ses_1_dir_AP__merged.bval']
original_bvecs = ['/tmp/work/qsiprep_wf/single_subject_BR371_wf/dwi_preproc_ses_1_dir_AP_wf/pre_hmc_wf/merge_and_denoise_wf/merge_dwis/dwi_denoise_ses_1_dir_AP__merged.bvec']
original_files = ['/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-1_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz', '/data/sub-BR371/ses-1/dwi/sub-BR371_ses-1_dir-AP_run-2_dwi.nii.gz']
sliceqc_file = /tmp/work/qsiprep_wf/single_subject_BR371_wf/dwi_preproc_ses_1_dir_AP_wf/hmc_sdc_wf/eddy/eddy_corrected.eddy_outlier_n_sqr_stdev_map
>
>Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/confounds.py", line 61, in _run_interface
    newpath=runtime.cwd,
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/confounds.py", line 171, in _gather_confounds
    raise Exception("Gradients or original files don't match. File a bug report!")
Exception: Gradients or original files don't match. File a bug report!

This is the command I used to run qsiprep: 
`#Run qsiprep
qsiprep-docker $bids_root_dir $bids_root_dir/derivatives \
  participant \
  --participant-label $subj \
  --skip_bids_validation \
  --fs-license-file $HOME/BRAINY_BIDS/derivatives/license.txt \
  --output-resolution 1.2 \
  --nthreads $nthreads \
  --stop-on-first-crash \
  --mem_mb $mem_mb
`

Please let me know your thoughts on how best to proceed, thank you!

**Comment by hchen115** [comment]
Yes. I checked again, and our data passed the BIDS validator.

Isaac

**Comment by smeisler** [comment]
Hi, I wanted to say that I had the same issue. I had to rotate my original files to get the labels (e.g. L/R, A/P, I/S) to appear right, but before running QSIPrep, I used MrTrix `dwigradcheck` to produce new bvec/bvals, so in theory the gradients should match the niftis. I was left with a preprocessed image, but QC metrics (and the brain mask, but might be unrelated) were not produced.

**Comment by mattcieslak** [comment]
Hi @smeisler, are you describing changing the orientation of data that was input to qsiprep? That's the appropriate time to use dwigradcheck.

**Comment by smeisler** [comment]
Yes, I reoriented the raw data, used dwigradcheck, and used fed the outputting bvals/bvecs from dwigradcheck into qsiprep.

**Comment by smeisler** [comment]
I used `dwi-only` since I'm working with macaque images. Good to know about the orientation, I'll see if it's correct.

**Comment by hchen115** [comment]
> That should be fine as long as the RL axis is consistent with the T1w. Also, mrtrix uses the strict FSL interpretation of bvecs, so unless the orientation you landed on is "RPI"/LAS+ there may be issues inside of qsiprep.
> 
> @hchen115 I think you're trying to use eddy on DSI data, which will not work. If you want to process DSI data in qsiprep you need to use `--hmc-model 3dSHORE`. Please try this and let me know how it goes

Got it, I appreciate the advice. I will use `--hmc-model 3dSHORE` and report back on how it went, thanks again!
Isaac

**Comment by smeisler** [comment]
In my case, using the properly oriented images still results in the same error. Using the images before undergoing rotation (that is, directly from the scanner), QSIPrep completed without errors. However, the brain mask was still wrong (image is 1 everywhere), but I imagine that could be due to using macaque data and not using the anatomical workflow. Would it be valid to rotate the images and correct the bval/vecs after QSIPrep?

**Comment by hchen115** [comment]
Hi @mattcieslak,

This time I got a different error:
> Node: qsiprep_wf.single_subject_BR371_wf.dwi_preproc_dir_AP_wf.hmc_sdc_wf.summarize_motion
Working directory: /tmp/work/qsiprep_wf/single_subject_BR371_wf/dwi_preproc_dir_AP_wf/hmc_sdc_wf/summarize_motion
>
>Node inputs:
>
>ref_file = <undefined>
>source_files = <undefined>
>transform_files = <undefined>
>
>Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/gradients.py", line 235, in _run_interface
    get_fsl_motion_params(motion_file, src_file, ref_file, runtime.cwd))
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/gradients.py", line 623, in get_fsl_motion_params
    rotation = get_measures(lines[6]) * flip
>IndexError: list index out of range

I scrolled through the log and found some feedback that I hope provides more context: 
![QSIPrep_error_1](https://user-images.githubusercontent.com/90048265/135903275-3e830b84-195e-43c9-9e69-55d48b4875d1.PNG)
![QSIPrep_error_2](https://user-images.githubusercontent.com/90048265/135903328-fc38ae68-b6bf-411d-b10b-4c144d1c2c0d.PNG)

Here is what my output folder structure looks like:
![QSIPrep_output_1](https://user-images.githubusercontent.com/90048265/135903657-7c0e16a3-19d0-406a-a8b3-4926e8a2cc3a.PNG)

In my earlier attempt when I had sessions in my BIDS dataset, the output folder structure didn't seem correct. Would you recommend using the `--bids-filter-file` tag to solve this issue? 
![QSIPrep_output_2](https://user-images.githubusercontent.com/90048265/135903993-bde1de04-eeba-4b49-a92a-ba201238ff53.PNG)

Thanks again for taking time to help us troubleshoot this issue.

**Comment by mattcieslak** [comment]
I'm working on this bug here #301, should have a release soon

**Comment by mattcieslak** [comment]
> In my case, using the properly oriented images still results in the same error. Using the images before undergoing rotation (that is, directly from the scanner), QSIPrep completed without errors. However, the brain mask was still wrong (image is 1 everywhere), but I imagine that could be due to using macaque data and not using the anatomical workflow. Would it be valid to rotate the images and correct the bval/vecs after QSIPrep?

Could you open a new issue for this? the --dwi-only workflow isn't heavily tested with nonhuman brains

**Comment by hchen115** [comment]
> I'm working on this bug here #301, should have a release soon

Thank you @mattcieslak! I appreciate your help!

I wanted to follow-up with 2 quick questions: 
1) Our collected DSI data unfortunately did not use a biopolar pulse to handle eddy currents at the sequence level. We were wondering if the SHORELine algorithm would be able to correct for eddy current artifacts. If not, do you have any recommendations regarding how we can correct for those artifacts?
2) Is the okay that there were no files found when running enhance b0?

**Comment by mattcieslak** [comment]
>     1. Our collected DSI data unfortunately did not use a biopolar pulse to handle eddy currents at the sequence level. We were wondering if the SHORELine algorithm would be able to correct for eddy current artifacts. If not, do you have any recommendations regarding how we can correct for those artifacts?

This is something we're benchmarking now. I think your best bet will be to run 3dSHORE and see how it looks. There are two variations on it that you can specify with the `--hmc-transform` flag. If you use `--hmc-transform Rigid` only 6DOF will be used for motion correction. If you use `--hmc-transform Affine`, you'll get a full 12DOF transform during motion correction. I think Affine *might* help with eddy currents, but it will not be as good as the linear or quadratic transforms in eddy.

Did your study include fieldmaps? If so, a lot of the distortion will be corrected using these.

> 
>     2. Is the okay that there were no files found when running enhance b0?

Yes, this is the expected behavior here. It's an expected warning message from ANTs.

**Comment by hchen115** [comment]
Thank you for your feedback!

Earlier scans in our study didn't have fieldmaps, it was something we incorporated later. However, our current plan is to use Synb0-DISCO to create undistorted b0 images from our earlier scans for TOPUP.
