### ISSUE TITLE
T1 Mask not at the same resolution of DWI

### ISSUE THREAD

**Issue by ShreyasFadnavis** [PennLINC/qsiprep#295]
Hi!

I noticed that the resolution of the T1w mask is not the same as the DWI. While I do agree that they are not supposed to be the same, it might be very useful to have the T1w mask resampled to the DWI resolution. 

This is generally required for across-session/ longitudinal studies or test-retest types of analyses. 

A simple `mri_vol2vol` or `dipy_reslice` should be very fast and simple to implement!

**Comment by mattcieslak** [comment]
@ShreyasFadnavis could you take a look [here](https://qsiprep.readthedocs.io/en/latest/reconstruction.html#anatomical-data-for-reconstruction-workflows) and let me know if this clears up how the DWI masking is done for reconstruction workflows?
