### ISSUE TITLE
[FEATURE REQUEST] Saving Eddy-outputs in output folder for use in EddyQC

### ISSUE THREAD

**Issue by ajschadler12** [PennLINC/qsiprep#298]
In order to use FSL's EddyQC with data preprocessed using qsiprep, I need to save the working directory locally using `-w WORK_DIR`.

Is there an option to save the necessary eddy files (e.g. index.txt, acqparams.txt, etc.) to a folder in a subject's output directory?

**Comment by julfou81** [comment]
Hi @mattcieslak, I just tried qsiprep for the first time, it is a great tool! Thank you for providing it to the community.  I would be interested to try the `qsiprep_group_report` functionality. How do you launch this command?
 Is it possible to use it via a singularity image of qsiprep? Sorry if it is a silly question!

**Comment by CaitlinLloyd** [comment]
Hi @mattcieslak, thanks again for this great pipeline!
I am struggling a little bit to produce the eddy files, and wondered what I might be doing wrong? We have a nipype file that sets remove_unnecessary_outputs to false, and placed in the root directory, but still cannot produce the eddy files. Do you have any thoughts? Is there an additional argument we should be using to run qsiprep? The --config flag does not seem to be recognised.

**Comment by rwmair** [comment]
Hi @CaitlinLloyd, the nippy.cfg file with remove_unnecessary_outputs = false retains all the unnecessary outputs in the working directory where qsiprep is running. But depending on your computing architecture (eg HPC cluster with job sumibbsion) this may get automatically deleted when the qsiprep job finishes. I had to string together commands to copy the entire working directory from the scratch space on our cluster back to my local directory, after which I could copy out the eddy output files. This working directory is 5-10GB depending on the size of your dataset - which I guess is why qsiprep by default doesn't retain all this stuff. So you may have to watch your own storage quota if running a lot of them.

**Comment by rwmair** [comment]
I should have added - once you've saved the working directory, you'll find the eddy output in:
`<workdir_name>/qsiprep_wf/single_subject_<subjID>_wf/dwi_preproc_<scan_ID>_wf/hmc_sdc_wf/eddy`
In addition to that entire folder I copy these additional files from the working directory to run eddy_quad:
`<workdir_name>/qsiprep_wf/single_subject_<subjID>_wf/dwi_preproc_<scan_ID>_wf/hmc_sdc_wf/gather_inputs/eddy*.txt
<workdir_name>/qsiprep_wf/single_subject_<subjID>_wf/dwi_preproc_<scan_ID>_wf/hmc_sdc_wf/pre_eddy_b0_ref_wf/enhance_and_mask_b0/topup_imain_corrected_avg_mask.nii.gz
<workdir_name>/qsiprep_wf/single_subject_<subjID>_wf/dwi_preproc_<scan_ID>_wf/hmc_sdc_wf/topup_to_eddy_reg/topup_reg_image_flirt.mat
<workdir_name>/qsiprep_wf/single_subject_<subjID>_wf/dwi_preproc_<scan_ID>_wf/hmc_sdc_wf/topup/fieldmap_HZ.nii.gz`
as well as the bvals from qsiprep output and the slspec file from a common location.

**Comment by CaitlinLloyd** [comment]
Thank you for this! I am still not seeing anything other than these files in the eddy subfolder within qsiprep workingdir:
_inputs.pklz
 _node.pklz
_report
command.txt
eddy_corrected.eddy_command_txt
eddy_corrected.eddy_post_eddy_shell_PE_translation_parameters
eddy_corrected.eddy_values_of_all_input_parameters

As far as I can tell nothing is being removed automatically. I think maybe we have the cfg file set up incorrectly or not visible to the container somehow? Would you mind sharing an example of the nipype.cfg file, just so I can rule that out?

**Comment by mattcieslak** [comment]
Are you running this via docker or singularity? I wonder if the nipype config isn't visible inside the container

**Comment by CaitlinLloyd** [comment]
docker, here is command in case you see anything odd!

nohup /usr/bin/docker service create --constraint 'node.hostname==gpu' --replicas 1 --reserve-cpu 8 --reserve-memory 16g --mode replicated --restart-condition none --name=qsi_`id -un`$qpath --mount type=bind,source=$indir,destination=/input,readonly=true --mount type=bind,source=$outdir,destination=/output --mount type=bind,source=$workdir,destination=/workdir --mount type=bind,source=/DATA /bin/freesurferlicense.txt,destination=/opt/freesurfer/license.txt,readonly=true --mount type=bind,source=/DATA/testing/nipype.cfg,destination=/home/root/.nipype/nipype.cfg pennbbl/qsiprep /input /output participant -w /workdir $addarg > $log 2>&1 &

**Comment by mattcieslak** [comment]
I've actually never seen a docker service being used for qsiprep. What happens if you mount the config file at `/root/.nipype/nipype.cfg`?

**Comment by CaitlinLloyd** [comment]
Sadly that does not work either :/ we have tried a few different locations without too much luck

**Comment by mattcieslak** [comment]
It looks like you can set where nipype will look for the config file with the [`NIPYPE_CONFIG_DIR`](https://github.com/nipy/nipype/blob/28d424f5dda3a23b01227379d91a825b0932efae/nipype/utils/config.py#L94) environment variable. If you set this in your container and mount the config file at `${NIPYPE_CONFIG_DIR}/nipype.cfg` then it should work regardless of which user you're running qsiprep as

**Comment by rwmair** [comment]
It must be that your qsiprep job is not seeing the nipype config file. Here's what the eddy sub-folder in the working directory contained on one of my recent runs:
_0x13da34fc6dfdee0ae211ccc7f4259587.json
command.txt
eddy_corrected.eddy_cnr_maps.nii.gz
eddy_corrected.eddy_command_txt
eddy_corrected.eddy_mbs_first_order_fields.nii.gz
eddy_corrected.eddy_movement_over_time
eddy_corrected.eddy_movement_rms
eddy_corrected.eddy_outlier_free_data.nii.gz
eddy_corrected.eddy_outlier_map
eddy_corrected.eddy_outlier_n_sqr_stdev_map
eddy_corrected.eddy_outlier_n_stdev_map
eddy_corrected.eddy_outlier_report
eddy_corrected.eddy_parameters
eddy_corrected.eddy_post_eddy_shell_alignment_parameters
eddy_corrected.eddy_post_eddy_shell_PE_translation_parameters
eddy_corrected.eddy_residuals.nii.gz
eddy_corrected.eddy_restricted_movement_rms
eddy_corrected.eddy_rotated_bvecs
eddy_corrected.eddy_values_of_all_input_parameters
eddy_corrected.nii.gz
_inputs.pklz
_node.pklz
_report
result_eddy.pklz

I am running eddy with just about everything - cuda, slice-to-vol correction with mporder=8, cnr maps and residuals on, movement-by-susceptability correction, so that adds to the plethora of files. Your eddy job may not be generating all of these.
