### ISSUE TITLE
schaefer200x7_sift_radius2_count_connectivity and schaefer200x7_radius2_count_connectivity of the resulting mat-file contain identical matrices

### ISSUE THREAD

**Issue by m-petersen** [PennLINC/qsiprep#307]
Hi Matt,

I am aiming for a graph theoretical analysis of qsiprep outputs.

After application of qsiprep/qsirecon with the "mrtrix_singleshell_ss3t" pipeline schaefer200x7_sift_radius2_count_connectivity and schaefer200x7_radius2_count_connectivity of the resulting mat-file contain identical matrices. I expected integers representing the streamline count in schaefer200x7_radius2_count_connectivity but both matrices contain floats like "1.431591663834453e+04" looking more like weighted streamline counts as expected after application of SIFT.

Am I misunderstanding something? Was looking for some hints in the documentation and code base but without luck.

Best,
Marvin

**Comment by mattcieslak** [comment]
this is fixed in `unstable` and will be included in 0.15.
