### ISSUE TITLE
HCP-MMP1 atlas

### ISSUE THREAD

**Issue by dkp** [PennLINC/qsiprep#312]
Thanks for creating QSIprep!  I am hoping you can add the HCP-MMP1 atlas to the mix.

Thank you!

Dianne

**Comment by pcamach2** [comment]
If you have the HCP-MMP1 atlas in the correct format, it is possible to use it for QSIPrep:
[https://qsiprep.readthedocs.io/en/latest/reconstruction.html#using-custom-atlases](https://qsiprep.readthedocs.io/en/latest/reconstruction.html#using-custom-atlases)

**Comment by dkp** [comment]
Thanks
