### ISSUE TITLE
QSIPrep derivative datasets are not (py)BIDS compliant

### ISSUE THREAD

**Issue by arokem** [PennLINC/qsiprep#318]
See https://github.com/yeatmanlab/pyAFQ/issues/765, where @smeisler has been trying to run pyAFQ on a qsiprep-processed dataset (an openneuro dataset;  see https://github.com/yeatmanlab/pyAFQ/issues/765#issuecomment-964435356) and pybids validation fails, because of issues apparently related to the `PipelineDescription` field of the dataset_description.json. 

Does 

```
import bids
bids_path = $PATH_TO_BIDS
layout =  bids.BIDSLayout(bids_path, derivatives=True)
```

generally work with QSIPrep derivatives out of the box?

**Comment by mattcieslak** [comment]
It does, but you have to specify that pybids shouldn't try to validate the file names

**Comment by arokem** [comment]
Just making sure that I understand this: do you mean that we should not validate at all at initialization of the BIDSLayout object? Something like the following?

```

layout =  bids.BIDSLayout(bids_path, derivatives=True, validate=False)

```
