### ISSUE TITLE
Standalone SHORELine motion correction

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsiprep#323]
Hi @mattcieslak,

I'm working on a mouse brain dataset that has some substantial motion issues related to scanner bed vibration. So far `eddy` works on the data but doesn't mitigate all of the motion corruption. I'm curious if SHORELine based motion correction would improve outcomes above and beyond what I've been able to accomplish so far.

I've tried running QSIPrep using the `--dwi-only` flag for these mouse brains but, unsurprisingly, the data do not produce outputs. I'm curious if the SHORELine HMC workflow would somehow be accessible as a stand-alone call.

Just musing and brainstorming what to do with these data while we try to address the motion at the scanner.

Thanks

**Comment by mattcieslak** [comment]
We don't have a standalone cli tool for shoreline, but if you've worked with nipype before you should be able to get shoreline run on your mouse data. Let me know if you're up for trying this out and I can point you to the relevant functions
