### ISSUE TITLE
fs-license error when running qsiprep

### ISSUE THREAD

**Issue by andrew-yian-sun** [PennLINC/qsiprep#325]
I am new to qsiprep. I ran the following code:
```
sudo docker run -ti --rm 
--volume /blc/NIA_R21/data_mri/dataOLD_BIDS_test_0061:/data:ro 
--volume /blc/NIA_R21/data_mri/dataOLD_qsiprep_test:/out 
pennbbl/qsiprep:latest 
/data 
/out 
participant 
--output_resolution 0.95 
--skip_bids_validation 
--fs-license-file $FREESURFER_HOME/license.txt
```
However, I get the following error message:
```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 578, in main
    set_freesurfer_license(opts)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 539, in set_freesurfer_license
    (for free) by registering at https://surfer.nmr.mgh.harvard.edu/registration.html""")
RuntimeError: ERROR: a valid license file is required for FreeSurfer to run. fMRIPrep looked for an existing license file at several paths, in this order: 1) command line argument ``--fs-license-file``; 2) ``$FS_LICENSE`` environment variable; and 3) the ``$FREESURFER_HOME/license.txt`` path. Get it (for free) by registering at https://surfer.nmr.mgh.harvard.edu/registration.html
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```
The license.txt file exists in `$FREESURFER_HOME`. I even replaced it with a new one thinking maybe the old one was for the wrong OS, but still got the same error message. I get the same error message whether I specify the license file with the `--fs-license-file` or not.

Details:
```
sudo docker version
Client: Docker Engine - Community
 Version:           19.03.5
```
OS: CentOS 7

Can anyone help me with this issue?

**Comment by cookpa** [comment]
One thing to check is if your OS is in FIPS mode. FreeSurfer will not recognize its license files on a system with FIPS, because its encryption algorithm doesn't work in such environments.

**Comment by andrew-yian-sun** [comment]
Thanks for the fast reply. 
I used `cat /proc/sys/crypto/fips_enabled` and the output was `0`, so I don't think FIPS is enabled.

**Comment by pcamach2** [comment]
Hi Andrew,

I think the issue is that the license.txt on your host machine is not
visible to the docker container. You can mount a volume containing the
license.txt and specify the fs-license-file using the corresponding
location in the container.

sudo docker run -ti --rm
--volume /blc/NIA_R21/data_mri/dataOLD_BIDS_test_0061:/data:ro
--volume /blc/NIA_R21/data_mri/dataOLD_qsiprep_test:/out
--volume ${FREESURFER_HOME}:/opt/licenseDir
pennbbl/qsiprep:latest
/data
/out
participant
--output_resolution 0.95
--skip_bids_validation
--fs-license-file /opt/licenseDir/license.txt

Cheers,
Paul

**Comment by andrew-yian-sun** [comment]
Thank you so much! That seems to have done the trick.
