### ISSUE TITLE
Mrtrix3 sift weights applied even in connectivity outputs with "use_sift_weights": false

### ISSUE THREAD

**Issue by kjamison** [PennLINC/qsiprep#330]
When running the "mrtrix_singleshell_ss3t_noACT.json" pipeline, I noticed that the connectivity matrices with and without "use_sift_weights" have identical values:

ie: "schaefer100x17_radius2_count_connectivity" and "schaefer100x17_sift_radius2_count_connectivity"

According to the json, these should have `"use_sift_weights": false`, and `"use_sift_weights": true`, respectively
They are both floating point, non-integer values, and thus seem to be both sift-weighted. I don't know where this issue might arise in the overall workflow, but it's obviously not the desired behavior.

**Comment by mattcieslak** [comment]
This is the same bug as #307, planning on fixing this in the next release. Those are both the SIFT weighted connectivity values

**Comment by mattcieslak** [comment]
this is fixed in `unstable` and will be included in 0.15.
