### ISSUE TITLE
Bad slices in qsiprep processed data

### ISSUE THREAD

**Issue by WilliamFCB** [PennLINC/qsiprep#339]
Hi 

I successfully ran qsiprep. However, in one particular data set, in contrast with other data sets, I found in many cases bad slices after correction (t1_num_bad_slices)
For example, one subject without raw_bad_slices and a fd_mean of .65 with apparent visually nice raw data, had 20 bad slices after correction. 

It appears that a stripped pattern has been introduced (see image)
![image](https://user-images.githubusercontent.com/34677306/152530811-60a2b760-cf13-4c91-b647-12ccb1890cb8.png)

Any idea what might have caused this? Interpolation error, overcorrection?
See qsiprep singularity and eddy parameter settings below.

Thanks 
William

singularity run --cleanenv --contain \
    -B ${TOOLS_DIR} \
    -B ${BIDS_DIR_TMP}:/data_in \
    -B ${BIDS_DIR}:${BIDS_DIR} \
    -B ${SCRIPTS_DIR}:${SCRIPTS_DIR} \
    -B ${OUTPUT_DIR}:/data_out \
    -B ${WORK_DIR}:/work \
    -B /tmp:/tmp \
    /mrhome/wimb/qsiprep/qsiprep-0.12.2_fsl-6.0.4-patch.sif \
    /data_in \
    /data_out \
    participant \
    -w /work \
    --participant-label ${sub}${ses/-/} \
    --skip_bids_validation \
    --use-plugin ${SCRIPTS_DIR}/tmp/qsiprep_plugin/${sub}_${ses}_qsiprep_plugin.yml \
    --fs-license-file ${TOOLS_DIR}/freesurfer/freesurfer.6.0.0/license.txt \
    --unringing-method mrdegibbs \
    --dwi-denoise-window 5 \
    --output-resolution 2 \
    --hmc-model eddy \
    --eddy_config ${SCRIPTS_DIR}/tmp/eddy_params/${sub}_${ses}_eddy_params.json \
    --output-space T1w \
    --nthreads  ${SLURM_CPUS_PER_TASK} \
    -vv

Eddy param:

{
  "flm": "quadratic",
  "slm": "SLM_REPLACE",
  "fep": false,
  "interp": "spline",
  "nvoxhp": 1000,
  "fudge_factor": 10,
  "dont_sep_offs_move": false,
  "dont_peas": false,
  "niter": 8,
  "method": "jac",
  "repol": true,
  "num_threads": NUM_THREADS_REPLACE,
  "is_shelled": false,
  "use_cuda": USE_CUDA_OPTION,
  "cnr_maps": true,
  "residuals": false,
  "output_type": "NIFTI_GZ",
  "args": "--very_verbose --fwhm=10,6,4,2,0,0,0,0 --ol_type=both --mporder=8 --s2v_niter=8 --slspec=SLSPEC_FILE_REPLACE --estimate_move_by_susceptibility"
}

**Comment by mattcieslak** [comment]
Hi @WilliamFCB, this is the most advanced eddy setup I've seen! Do you still see the striping artifact without adding the extra args?

**Comment by WilliamFCB** [comment]
Hi Matt,
Would have to check that ..... However, might be something with the particular data sets. I haven't seen it before in other large data sets I processed with the same settings. I was just wondering if you had encountered this at some point or might have an idea in which direction to look .... I will keep you posted
Thanks!

**Comment by cookpa** [comment]
Hi @WilliamFCB , what is the multi-band acceleration factor for your data? The eddy user guide says mporder should be at most N-1, where N is the multiband excitation factor.

**Comment by WilliamFCB** [comment]
Thanks @cookpa, I would have to look it up. By the way, I haven't had the time to look more into this issue, but I found out that the image I uploaded was due to issues with fsleyes. Of course, this does not change the fact I have a lot to bad slices after running qsiprep. Hope to have some time to look at it today. Thanks!

**Comment by WilliamFCB** [comment]
No multiband. In this case the number of excitations equals the number of slices (N = 66). Thus the number of mporder=8 used, is still lower than  N/4  ~ 16

**Comment by ShreyasFadnavis** [comment]
Hi @WilliamFCB ! Is this striped pattern consistent across all gradient directions? Or just a few of them? If inconsistent, you can try using 'denoise_method patch2self'-- it should help get rid of it. 

@mattcieslak -- this reminds me, we should at some point add capability to apply P2S at any point of the pipeline!

**Comment by WilliamFCB** [comment]
Hi @mattcieslak  is there some way to identify the slices that represent "t1_num_bad_slices". The "raw_num_bad_slices" generally fit nicely with the heatmap/carpet plot.
Cheers

**Comment by mattcieslak** [comment]
These are calculated in DSI Studio - I don't believe there's a way to see which slices got flagged, but it would be worth asking Frank just to be sure

**Comment by WilliamFCB** [comment]
Is this something you intend to pursue, to get this functionality integrated into qsiprep?
