### ISSUE TITLE
eddy throw exception

### ISSUE THREAD

**Issue by BNU-liuzhenzhao** [PennLINC/qsiprep#358]
When I ran qsiprep, exception raised while excuting node eddy. The property **use_cuda** was true in my **eddy_config.json** file.My qsiprep docker image version is **pennbbl/qsiprep:unstable** and my GPU was **NVIDIA Corporation GA102 [GeForce RTX 3090]**. The **cuda9** in pennbbl/qsiprep:0.14.3 cannot run eddy successfully because my GPU only supports cuda version>=10. How can I run qsiprep with **cuda10** in docker container? 
My command was:
docker run -ti --rm \
	-v /home/shulab/data2/liuzhenzhao/qsiprep/qsiprep-in/HCP-A:/data:ro \
	-v /home/shulab/data2/liuzhenzhao/qsiprep/qsiprep-out:/out \
	-v /home//shulab/data2/liuzhenzhao/qsiprep/qsiprep-work:/work \
	-v /home/shulab/data2/liuzhenzhao/qsiprep/qsiprep-conf:/qsiconfig \
	pennbbl/qsiprep:unstable \
	/data /out participant \
	--participant_label [ '6148668' ] \
	--output-resolution 1.5 \
	--skip_bids_validation \
	--eddy-config /qsiconfig/eddy_config.json \
	--fs-license-file /qsiconfig/license.txt \
	--recon_spec /qsiconfig/mrtrix_msmt_csd.json \
	--recon-input /out \
	--work_dir /work \
	--unringing-method mrdegibbs \
	--b0-to-t1w-transform Affine \
	--distortion-group-merge average \
	--nthreads 12 \
	--low-mem 
Here are the logs:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'out_corrected' trait of an ExtendedEddyOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/work/qsiprep_wf/single_subject_6148668_wf/dwi_preproc_wf/hmc_sdc_wf/eddy/eddy_corrected.nii.gz' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 401, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/work/qsiprep_wf/single_subject_6148668_wf/dwi_preproc_wf/hmc_sdc_wf/eddy/eddy_corrected.nii.gz' for output 'out_corrected' of a ExtendedEddy interface

**Comment by mattcieslak** [comment]
Could you try adding `--gpus all` to the docker arguments?

**Comment by BNU-liuzhenzhao** [comment]
> Could you try adding `--gpus all` to the docker arguments?

Appreciations to your help!
