### ISSUE TITLE
DKI Setup

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/qsiprep#367]
@arokem Opening an issue on this, I have a couple DKI questions for you too.

I currently only have the min and max clip values for mkt, etc enabled as options for the user. Are there other options that would be useful to expose in the json file?

For DKI do people ever make ODFs? I didn't see a direct ODF method in the Dipy DKI class, but if there is another way, we could write the ODFs in mrtrix and dsi studio format for visualization/tractography.

Are there other scalars you'd recommend writing from the DKI fit?

Thanks in advance!

TODO:

 - [x] Fix Kurtisis typo
 - [x] Remove extra copy of TensorReconstruction

**Comment by arokem** [comment]
> Are there other options that would be useful to expose in the json file?

The only other thing I can think of is if you want to expose different fitting methods.

> For DKI do people ever make ODFs? 

There is some work on this, and we even have a WIP PR on this in DIPY: https://github.com/dipy/dipy/pull/2304, but that implementation is still rather slow, and I have not had time and strong motivation to complete that PR. For now, the ODF that you get out of the DIPY DKI implementation is the DTI ODF for the tensor that is enclosed in the DKI model.

>  Are there other scalars you'd recommend writing from the DKI fit?

One extension you might want to consider as future work is [Fieremans et al.'s WMTI model](https://pubmed.ncbi.nlm.nih.gov/21699989/) implemented in https://github.com/dipy/dipy/blob/master/dipy/reconst/dki_micro.py, but that's probably a separate interface anyway.
