### ISSUE TITLE
QSIPrep does distortion correction with different PE directions?

### ISSUE THREAD

**Issue by akelkar26** [PennLINC/qsiprep#369]
Hi, 
I am opening this issue to confirm qsiprep does distortion correction correctly on my data. I have two datasets I am working with

Dataset 1: patient data (stroke) where I use dwi-only flag.
We collect the following scans:
Multi-shell DTI data: 
Echo time = 82ms; TotalReadout time = 0.0644004 sec, PE direction: A>>P

Blip-up scan:
Echo time = 96ms; TotalReadout time = 0.106945 sec, PE direction: R>>L

I am using version 0.13.0RC1
I was unsure from documentation, can PEPOLAR use R>>L PE direction for distortion correction? I get no error or no crash log. 

However, from documentation it says: Currently, different phase encoding dimension in the target file and the ‘_epi’ file(s) (for example ‘i’ and ‘j’) is not supported.

The output however, seems fine. 

![sub-TMSA02_ses-BRAINRESEARCHCOSLETT_desc-sdc_b0](https://user-images.githubusercontent.com/40644674/156835898-9006ad63-3293-4450-838f-39083451633a.svg)

I also have a second dataset conforming to the conventional PE directions

Dataset 2: entire anat and dwi pipeline run
Multi-shell DTI data: 
Echo time = 82ms; TotalReadout time = 0.0644004 sec, PE direction: A>>P

Blip-up scan:
Echo time = 82ms; TotalReadout time = 0.0644004 sec, PE direction: A>>P

Blip-down scan:
Echo time = 82ms; TotalReadout time = 0.0644004 sec, PE direction: P>>A

From documentation it seems like it takes the blip-up and blip-down scan for susceptibility distortion correct. Is that correct?
Here is the output from that data. It also looks good.

![sub-DHTY_ses-PrismPilot_desc-sdc_b0](https://user-images.githubusercontent.com/40644674/156836968-c9248fe3-ce64-47f1-8bd1-77328e1b5afc.svg)

Could you please confirm the PEPOLAR Pipeline can handle both these use cases?

Thank you so much
Best,
Apoorva

**Comment by mattcieslak** [comment]
Hi Apoorva, I can't tell from the static image if it's working or not. For your AP/PA data you will get distortion correction applied as long as the BIDS is configured correctly. I've never tried AP/RL before, but I think if you have the IntendedFor set in the sidecar of the RL file it may work
