### ISSUE TITLE
Qsiprep recon mrtrix seeding

### ISSUE THREAD

**Issue by pandyasneha** [PennLINC/qsiprep#370]
Hello,

I am trying to run recon workflow on qsiprep preprocessed images. We want to create a custom workflow based on mrtrix_singleshell_ss3t_noACT template as we plan to use a deterministic algorithm and a different seeding option. Swapping tractography algorithm seems straightforward, however there seems to be no option to pass a parameter for seeding mechanism. Looking at the workflow in more [detail](https://github.com/PennLINC/qsiprep/blob/master/qsiprep/workflows/recon/mrtrix.py), it seems that dynamic seeding is ingrained within the workflow. Is there a way we can pass a parameter that may overwrite this? We have a diseased cohort and there might be issue with tissue damage hence dynamic seeding may do more harm than good. I am planning to modify tckgen node as follow, please advice if I can add a suitable parameter to disable dynamic seeding.

```
{
      "name": "track_SD_STREAM",
      "software": "MRTrix3",
      "action": "tractography",
      "output_suffix": "sdstream",
      "input": "ss3t_csd",
      "parameters": {
        "use_5tt": false,
        "use_sift2": true,
        "tckgen":{
          "algorithm": "SD_STREAM",
          "select": 5e6,
          "downsample": 3,
          "max_length": 250,
          "min_length": 30,          
        },
        "sift2":{}
  }
}
```

Also, with the above, I am getting an error with downsample parameter for tckgen. I have tried entering it in different ways, but tckgen still does not like it. Is downsample a valid parameter that qsiprep can accept for mrtrix’s tckgen?

`tckgen: [ERROR] incomplete use of string “3.000000” in conversion to type “l”`

`"downsample": 3`

or

`"downsample": 3e0`

or

`"downsample": 3.0`

Thank you,
Sneha

**Comment by mattcieslak** [comment]
The downsample argument isn't used for SD_STREAM https://mrtrix.readthedocs.io/en/dev/reference/commands/tckgen.html
