### ISSUE TITLE
Question about Preprocessing HCP-style

### ISSUE THREAD

**Issue by andrew-yian-sun** [PennLINC/qsiprep#375]
I have a dataset that has full dwi scans in both AP and PA directions. My understanding is that I should be including the `--distortion-group-merge average` option in command line, per the "Preprocessing HCP-style" section. The documentation here suggests I should be including the `--combine-all-dwis` option as well, but I believe that flag has been removed (and is the default option?).

However, in terms of setting up the BIDS-valid dataset, am I right in thinking that I should put both of these scans (AP and PA) in the dwi folder? Also, is there any metadata field that needs to be added? I have tried a couple different options but kept running into errors.

Thanks,
Andrew

**Comment by arokem** [comment]
We've also run into issues with this setting and HCP-style data. In particular we're running this command line call: 

```
docker run -ti --rm   -v /<path to data>/:/data:ro   -v /<path to data>/derivatives/:/out   pennbbl/qsiprep:0.15.3   /data /out participant --fs-license-file /data/fs_license.txt --output-resolution 1.5 --dwi-only --distortion-group-merge average
```

And we're running into this error: 

```
ValueError: Field of view of image #1 is different from reference FOV.
Reference affine:
array([[-1.48667288e+00,  1.99421033e-01,  5.91740012e-03,
         9.18560028e+01],
       [ 1.86300784e-01,  1.40355873e+00, -4.95292544e-01,
        -8.66671829e+01],
       [ 7.13847876e-02,  4.90157068e-01,  1.41585684e+00,
        -1.19574066e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])
Image affine:
array([[-1.49594903e+00,  1.06968507e-01, -2.63520107e-02,
         1.02660027e+02],
       [ 1.08431503e-01,  1.36621404e+00, -6.09673440e-01,
        -7.02401581e+01],
       [ 1.94755811e-02,  6.09931827e-01,  1.37025690e+00,
        -1.36695358e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])
Reference shape:
(140, 140, 92)
Image shape:
(140, 140, 92, 100)
```

Is that also the error you are seeing @andrew-yian-sun? Should we be using a different setting for distortion-group-merge? Or is something wrong with the data?

**Comment by cookpa** [comment]
In terms of how to set it up, @andrew-yian-sun I think the `dwi` directory needs to include:

* DWI data (_dwi.nii.gz)
* bvec / bval (_dwi.bv[ec,al])
* BIDS sidecars (_dwi.json)

For example,

sub-999999_ses-MR1_acq-98dir_dir-AP_dwi.bval
sub-999999_ses-MR1_acq-98dir_dir-AP_dwi.bvec
sub-999999_ses-MR1_acq-98dir_dir-AP_dwi.json
sub-999999_ses-MR1_acq-98dir_dir-AP_dwi.nii.gz

sub-999999_ses-MR1_acq-98dir_dir-PA_dwi.bval
sub-999999_ses-MR1_acq-98dir_dir-PA_dwi.bvec
sub-999999_ses-MR1_acq-98dir_dir-PA_dwi.json
sub-999999_ses-MR1_acq-98dir_dir-PA_dwi.nii.gz

To work properly, these files must contain the same measurements (same bvecs and bvals) with opposite phase encodings. For example, for AP we should see in the JSON

```
    "PhaseEncodingDirection": "j-",
```

and for PA

```
    "PhaseEncodingDirection": "j",
```

This also works for LR / RL pairs (eg WashU HCP sequences).

The error that @arokem has is more complicated, and happens if the FOV is not consistent among the scans to be merged. This is a really tricky question to deal with (see https://github.com/PennLINC/qsiprep/issues/273). If the rotation is small and the translation is fairly small, in my opinion it's safe to copy the header transforms from the first image to the second one.

**Comment by andrew-yian-sun** [comment]
@arokem No, that is not the same error that we are getting. What happens is that if we simply put both the AP and PA in the dwi folder:

> dwi/
> > sub-01_ses-1_dir-AP_dwi.bval
> > sub-01_ses-1_dir-AP_dwi.bvec
> > sub-01_ses-1_dir-AP_dwi.json
> > sub-01_ses-1_dir-AP_dwi.nii.gz
> > sub-01_ses-1_dir-PA_dwi.bval
> > sub-01_ses-1_dir-PA_dwi.bvec
> > sub-01_ses-1_dir-PA_dwi.json
> > sub-01_ses-1_dir-PA_dwi.nii.gz

and AP and PA jsons have `j-` and `j`, respectively, in their `"PhaseEncodingDirection"` fields, we get a `packet_write_wait: Connection to 138.23.190.43 port 22: Broken pipe`. After this, we have to manually restart our Linux machine to be able to access it again.

We've successfully run the same version of QSIprep on the same computer, but on another dataset where opposite encoding fieldmap was collected (B0_PA in fmap, `IntendedFor` field set to the AP files in dwi). 

Forgot to mention this as well but here are the software details:
QSIprep version: 0.14.3
OS: Centos 7

**Comment by cookpa** [comment]
> and AP and PA jsons have j- and j, respectively, in their "PhaseEncodingDirection" fields, we get a packet_write_wait: Connection to 138.23.190.43 port 22: Broken pipe. After this, we have to manually restart our Linux machine to be able to access it again.

I think this is only indirectly related to the data.

By manually restart, do you mean the machine becomes unresponsive, and you have to physically reset it? Could it be that qsiprep is using all the resources? How much RAM is on the machine?

**Comment by andrew-yian-sun** [comment]
> By manually restart, do you mean the machine becomes unresponsive, and you have to physically reset it? Could it be that qsiprep is using all the resources? How much RAM is on the machine?

Yup, everyone who has ssh'ed into the machine lose connection, and are unable to ssh back in until the machine is physically reset. The RAM is 92 GB.

**Comment by arokem** [comment]
@cookpa : Thanks for pointing out that issue! 🤔

**Comment by cookpa** [comment]
@andrew-yian-sun Are you limiting the parallel threads? When your jobs start, you should see something like

```
220314-13:35:46,286 nipype.workflow INFO:
         Running with omp_nthreads=3, nthreads=4
220314-13:35:46,288 nipype.workflow IMPORTANT:
    Running qsiprep version 0.14.3:
      * BIDS dataset path: /data/input.
```

what does it say?

**Comment by andrew-yian-sun** [comment]
No, I haven't been adding `--nthreads` or `--omp-nthreads` options. Here's what I see when my jobs start:
```
220315-01:07:35,441 nipype.workflow INFO:
	 Running with omp_nthreads=8, nthreads=32
220315-01:07:35,454 nipype.workflow IMPORTANT:
	 
    Running qsiprep version 0.14.3:
      * BIDS dataset path: /data.
```

**Comment by cookpa** [comment]
This might help then, add `--nthreads 4 --omp-nthreads 3` to the call. It will take longer but may avoid locking up the system. If that works, you can try increasing to `--nthreads 8 --omp-nthreads 7`. 

The idea of setting omp threads to (nthreads-1) comes from [a discussion about fmriprep](https://neurostars.org/t/fmriprep-v1-5-4-runtime-paradoxes-and-omp-threads/5647), I've not tested it on qsiprep specifically, and it might be more efficient to run with the same number for both. But you will use more RAM and may see diminishing returns past 8 threads.

**Comment by mattcieslak** [comment]
@cookpa is right, you should definitely limit omp_nthreads and nthreads to prevent your computer from crashing.

**Comment by andrew-yian-sun** [comment]
@cookpa Thanks! That seems to have worked. However, we're now running into another issue:
```
The b-table /work/qsiprep_wf/single_subject_01_wf/sub_01_ses_1_final_merge_wf/distortion_merger/averaged_pairs.bval and /work/qsiprep_wf/single_subject_01_wf/sub_01_ses_1_final_merge_wf/distortion_merger/averaged_pairs.bvec do not match each other
mismatch between bvec file and the loaded images
```
Here is the full crash file:
[crash-20220318-061132-root-raw_src-1cc8a703-6744-41fc-8606-2fd088416bba.txt](https://github.com/PennLINC/qsiprep/files/8307961/crash-20220318-061132-root-raw_src-1cc8a703-6744-41fc-8606-2fd088416bba.txt)

And here relevant bval and bvec files that aren't matching.
[averaged_pairs.bval.txt](https://github.com/PennLINC/qsiprep/files/8307979/averaged_pairs.bval.txt)
[averaged_pairs.bvec.txt](https://github.com/PennLINC/qsiprep/files/8307980/averaged_pairs.bvec.txt)

 I see that the bvec has nans while the bval has 0's - is this an issue?

**Comment by cookpa** [comment]
Hmm, do your input bvecs have zeros corresponding to bval = 0? If so, that might be the source of the NaN.

**Comment by andrew-yian-sun** [comment]
Yes the input bvecs haves zeros corresponding to where bval = 0, but shouldn't that be the case? 

Here are the input bval and bvec files:
[sub-01_ses-1_dir-AP_dwi.bval.txt](https://github.com/PennLINC/qsiprep/files/8354089/sub-01_ses-1_dir-AP_dwi.bval.txt)
[sub-01_ses-1_dir-AP_dwi.bvec.txt](https://github.com/PennLINC/qsiprep/files/8354090/sub-01_ses-1_dir-AP_dwi.bvec.txt)
[sub-01_ses-1_dir-PA_dwi.bval.txt](https://github.com/PennLINC/qsiprep/files/8354091/sub-01_ses-1_dir-PA_dwi.bval.txt)
[sub-01_ses-1_dir-PA_dwi.bvec.txt](https://github.com/PennLINC/qsiprep/files/8354092/sub-01_ses-1_dir-PA_dwi.bvec.txt)

**Comment by cookpa** [comment]
Yes, a zero b-value has an undefined gradient direction. But wherever I see a "nan" I think of where a division by zero may have crept in. This sounds like a bug, but one we've probably not encountered before because we don't typically see zero b-vectors.

Modern data, at least for Siemens scanners, don't have true zeros because they record all the gradients in play at the time of acquisition, not just the diffusion-sensitizing gradients. So the bvecs are always a unit vector, and the bvals are off by some small amount from their nominal value.

Just curious - are these bval.txt and bvec.txt files produced from dcm2niix? Or are they they nominal bvecs and bvals programmed into the sequence?
