### ISSUE TITLE
Question about connectivity matrix

### ISSUE THREAD

**Issue by sreekarchigurupati** [PennLINC/qsiprep#376]
Hello,
This is my first time running qsiprep. I am trying to run mrtrix_singleshell_ss3t_noACT on a single subject. I want to generate a connectivity matrix out of this. The command generates a file named `sub-10506_space-T1w_desc-preproc_dhollanderconnectome.mat` inside the folder out/qsirecon/dwi. Is this the connectivity matrix? If not, how do we get it? This is not visualized in the HTML report. Is there anyway to include this in the report?

Command Used:
`qsiprep-singularity ~/data ~/out --output-resolution 1.2  --fs-license-file ~/license.txt -w ~/data/working --use-syn-sdc --force-syn --denoise-method patch2self --unringing-method mrdegibbs --no-b0-harmonization --nthreads 60 --recon_spec mrtrix_singleshell_ss3t_noACT`

Thanks
Sreekar

**Comment by sreekarchigurupati** [comment]
qsiprep version used: v0.15.3

**Comment by pcamach2** [comment]
Hi @sreekarchigurupati,

The .mat file is a MATLAB file that should contain the NxN connectivity matrices for the parcellations and edge-weighting schemes associated with the mrtrix_singleshell_ss3t_noACT workflow. You can open them in MATLAB or use a package for your programming language of choice (e.g. scipy.io for python). 

Cheers,
Paul

**Comment by sreekarchigurupati** [comment]
Thank you
