### ISSUE TITLE
SNR/CNR map dimensions reduced from 4 down to 3

### ISSUE THREAD

**Issue by psadil** [PennLINC/qsiprep#379]
I think there may be a bug in the [cnr_tfm](https://github.com/PennLINC/qsiprep/blob/429afc60781b74f58aa0e5d1eb9ab7433edc14bd/qsiprep/workflows/dwi/resampling.py#L176-L179) node of the `dwi_trans_wf` workflow. As I understand it, the image that is input `cnr_tfm` will have either 3 or 4 dimensions, depending on how many bvals are in the image being processed. For example, I'm working with an image that has bvals 0, 500, 1000, 2000, 3000, and the input map is 4d with one volume for each bval. But the output -- the file deposited as sub-[subid]_ses-[sesid]_space-T1w_desc-eddy_cnr -- lost the fourth dimension. 

The command is recorded in the node's working directory as. 

```
antsApplyTransforms --default-value 0 --float 1 \
--input <removed>/dwi_preproc_ses_V1_wf/hmc_sdc_wf/cnr_lps/eddy_corrected.eddy_cnr_maps_LPS.nii.gz \
--interpolation LanczosWindowedSinc --output eddy_corrected.eddy_cnr_maps_LPS_trans.nii.gz \
--reference-image <removed>/anat_preproc_wf/output_grid_wf/resample_to_voxel_size/mni_1mm_t1w_lps_autobox_warp_resample.nii.gz \
--transform <removed>/dwi_preproc_ses_V1_wf/b0_anat_coreg/b0_to_anat/transform0GenericAffine.mat
```

I'm not sure how this ends up combining the five volumes into one, but it would be helpful to access each of the SNR/CNR maps.

Thanks for making qsiprep available! Let me know if I can provide more info

**Comment by cookpa** [comment]
I can reproduce this with 0.14.3. Strangely, `desc-eddy_cnr.nii.gz` is still a 4D image, but dim[4] == 1. I think it's getting condensed to a single value before the call to `antsApplyTransforms` above.

I agree it would be valuable to have SNR / CNR for all the shells.

**Comment by psadil** [comment]
@cookpa , why do you think it's before the call to `antsApplyTransforms`? In my case, the dimensions of the input and output are as follows and which are why I thought it was this node specifically (this is all with version 0.14.2)

input
```
$ fslinfo eddy_corrected.eddy_cnr_maps_LPS.nii.gz 
data_type	FLOAT32
dim1		140
dim2		140
dim3		81
dim4		5
datatype	16
pixdim1		1.714290
pixdim2		1.714290
pixdim3		1.700000
pixdim4		8.000000
cal_max		0.000000
cal_min		0.000000
file_type	NIFTI-1+
```

output
```
$ fslinfo eddy_corrected.eddy_cnr_maps_LPS_trans.nii.gz 
data_type	FLOAT32
dim1		115
dim2		136
dim3		116
dim4		1
datatype	16
pixdim1		1.700000
pixdim2		1.700000
pixdim3		1.700000
pixdim4		0.000000
cal_max		0.000000
cal_min		0.000000
file_type	NIFTI-1+
```

**Comment by cookpa** [comment]
Thanks for this, I see the problem now. I thought the call to nipype's ApplyTransforms was auto-detecting the file type, but now I see it's not.

**Comment by mattcieslak** [comment]
This should be fixed in qsiprep:unstable. Please repoen this issue if it's still reducing the dimensionality of your image
