### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by sreekarchigurupati** [PennLINC/qsiprep#380]
Hi,
Is there a progress bar flag available? I am running qsiprep with tractography enabled for multiple subjects. It has been running for quite sometime. I would like to know the status when running for multiple subjects

Thanks
Sreekar

**Comment by sreekarchigurupati** [comment]
I am using 100 threads. 32 cores and 70GB RAM. It completed running but took a day for 5 subjects. Is there any way to make it faster?

Command used:
```
qsiprep-singularity ~/control_data ~/output_data --output-resolution 1.2  --fs-license-file ~/Desktop/license.txt -w ~/working --use-syn-sdc --force-syn --denoise-method patch2self --unringing-method mrdegibbs --no-b0-harmonization --nthreads 100 --recon_spec mrtrix_singleshell_ss3t_noACT
```
Are there any other cli parameters to improve parallelism. Can we increase threads per process? Will that help?

Is there something in the command line output that displays the number of nodes completed vs. number of nodes yet to be run / completed.

**Comment by mattcieslak** [comment]
ah! this may be the issue. Performance is hurt if you run more threads than you have cpus. I suggest changing to 

`--nthreads 4 --omp-nthreads 8` 

this will let run 4 instances of tckgen simultaneously, each with 8 cpus apiece, which will keep all 32 of your cpus busy. omp-nthreads controls the max number of cpus assigned to an individual computation, so your current command was running at most 32 single-cpu tckgens at the same time.

**Comment by sreekarchigurupati** [comment]
I have used --nthreads 4 --omp-nthreads 8. The CPU utilization is not optimal. This is what the average CPU utilization looks like. Are tasks apart from tracking parallelized?
<img width="685" alt="image" src="https://user-images.githubusercontent.com/13794515/159140393-9ea2fb3c-2e56-45e1-a2f0-8264a65f7c6f.png">

**Comment by sreekarchigurupati** [comment]
Shouldn't the --nthreads be 32 as it is the number of threads across all processes?

**Comment by mattcieslak** [comment]
oops, yes you're right. nthreads 32, omp-nthreads 8
