### ISSUE TITLE
Reconstruction only runs on one DWI if multiple present.

### ISSUE THREAD

**Issue by smeisler** [PennLINC/qsiprep#381]
Hello,

I have ses-pre/ses-post DWI data for a single subject that I tried running qsiprep/recon 0.15.3 on. QSIPrep preprocessed both images images fine, but only did reconstruction for a single session. After running "calc_connectivity" for one session, qsirecon stalls and does not begin processing the other session. I am running the mrtrix ss3t HSVS option on a singularity container on CentOs 7.6. 40GB of memory, 8 cores for the job. The one tractogram that was created looks fine. Happy to provide more info as needed.

Thanks,
Steven

**Comment by mattcieslak** [comment]
Hi Steven, I wonder if the ODF plotting is causing silent errors again. Are you using `--skip-odf-reports`?

**Comment by smeisler** [comment]
I am skipping the odf plots.

**Comment by mattcieslak** [comment]
I think @hamsiradhakrishnan just replicated this bug here.

**Comment by mattcieslak** [comment]
This should be fixed in 0.16.0RC3, please reopen if it persists!
