### ISSUE TITLE
Boilerplate question

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsiprep#388]
Hi @mattcieslak,

I got reviews back on manuscript using QSIPrep v. 0.12.2. In the description is the following line referring to Eddy's outlier replacement:

"Data were grouped by slice, only including values from slices determined to contain at least 250 intracerebral voxels. Groups deviating by more than 4 standard deviations from the prediction had their data replaced with imputed values."

The reviewer wants to know: "In terms of percentage, how much of the data was imputed."

Does Eddy report that anywhere that may be accessible in QSIPrep outputs? I don't recall that being reported anywhere, even from Eddy.

**Comment by mattcieslak** [comment]
For the record this is the default setting for eddy, not something unique to qsiprep. You can find the eddy info in the `desc-SliceQC_dwi.json` file in the results.

**Comment by araikes** [comment]
Hi @mattcieslak,

I know it's a default for Eddy and I've never had a reviewer ask for reporting about how much data was imputed. 

Just want to makes sure I understand the `desc-SliceQC_dwi.json` file. Is it an accurate interpretation anywhere the value is e.g. > 4, then data from that slice was imputed and so, if calculating the percentage, this is:

`(# of values > 4)/(# of slices * # of non-bzero gradients) * 100`

**Comment by araikes** [comment]
Hi @mattcieslak,

Just a bump on this to make sure I'm interpreting the data that you're putting in the SliceQC JSON correctly and then I'll close it.

**Comment by mattcieslak** [comment]
This should be correct. I don't change any of the values before putting them into the json
