### ISSUE TITLE
DWIs not found for dHCP data

### ISSUE THREAD

**Issue by alexamousley** [PennLINC/qsiprep#390]
Hi all,

I am aiming to use --recon-only to preform tractography on preprocessed neonatal data from dHCP. I am using version 0.15.3. I believe dHCP is correctly in bids for preprocessed data but I keep getting the error that no dwi files are found. I have also tried renaming the files to a simpler version of bids naming structure (e.g sub-NDARINV_ses-15102_dwi.nii.gz) since I am only preforming reconstruction and thus know the data is preprocessed but I continued to get the same error.

Here is my function call:
`run bids_path,out_path,license_path /imaging/local/software/singularity_images/qsiprep/qsiprep-0.15.3.simg bids_path out_path participant --participant-label %s --recon-spec dsi_studio_gqi --recon-only --recon-input bids_path --infant --nthreads 16 --output-resolution 1 --fs-license-file license_path`

Here is the .out file:
[33mWARNING: Underlay of /etc/hosts required more than 50 (102) bind mounts
[0mMatplotlib created a temporary config/cache directory at /tmp/matplotlib-hcp_a8lx because the default path (/home/qsiprep/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
220404-13:04:46,593 nipype.workflow IMPORTANT:
	 
    Running qsirecon version 0.15.3:
      * BIDS dataset path: /imaging/astle/am11/dHCP/bids.
      * Participant list: ['NDARINV'].
      * Run identifier: 20220404-130446_35244ba7-450b-4881-b926-cb86fe41634e.
    
220404-13:04:46,781 nipype.workflow INFO:
	 found [] in /imaging/astle/am11/dHCP/bids
220404-13:04:46,781 nipype.workflow INFO:
	 No dwi files found for NDARINV
220404-13:04:47,43 nipype.workflow IMPORTANT:
	 Works derived from this qsiprep execution should include the following boilerplate:

Reconstruction was
performed using *QSIprep* 0.15.3,
which is based on *Nipype* 1.7.0
(@nipype1; @nipype2; RRID:SCR_002502).

Many internal operations of *qsiprep* use
*Nilearn* 0.9.0 [@nilearn, RRID:SCR_001362] and
*Dipy* 1.4.1[@dipy].
For more details of the pipeline, see [the section corresponding
to workflows in *qsiprep*'s documentation](https://qsiprep.readthedocs.io/en/latest/workflows.html "qsiprep's documentation").

### References
    
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'CITATION'
QSIPrep failed: Graph has no nodes or edges
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 659, in main
    qsiprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 121, in run
    self._generate_dependency_list(graph)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 437, in _generate_dependency_list
    self.depidx = nx.to_scipy_sparse_matrix(
  File "/usr/local/miniconda/lib/python3.8/site-packages/networkx/convert_matrix.py", line 855, in to_scipy_sparse_matrix
    raise nx.NetworkXError("Graph has no nodes or edges")
networkx.exception.NetworkXError: Graph has no nodes or edges
Sentry is attempting to send 4 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

The file structure looks as follows:
```
bids/
    dataset_description.json
    from-dwi_to-extdhcp40wk_mode-image.json
    from-dwi_to-T2w_mode-image.json
    from-T2w_to-dwi_mode-image.json
    from-template40wk_to-dwi_mode-image.json
    participants.tsv
    sub-NDARINV/
        sub-NDARINV_sessions.tsv
        .DS_Store
        ses-15102/
            .DS_Store
            dwi/
                sub-NDARINV_ses-15102_model-DKI_MK.nii.gz
                sub-NDARINV_ses-15102_model-DTI_MD.nii.gz
                sub-NDARINV_ses-15102_model-DTI_diffmodel.nii.gz
                sub-NDARINV_ses-15102_desc-preproc_dwi.nii.gz
                sub-NDARINV_ses-15102_desc-preproc_dwi.bval
                sub-NDARINV_ses-15102_model-DTI_EVECS.nii.gz
                sub-NDARINV_ses-15102_desc-preproc_dwi.bvec
                sub-NDARINV_ses-15102_model-DTI_FA.nii.gz
                sub-NDARINV_ses-15102_desc-brain_mask.nii.gz
                sub-NDARINV_ses-15102_desc-preproc_dwi.json
                sub-NDARINV_ses-15102_desc-brain_mask.json
            fmap/
                sub-NDARINV_ses-15102_fieldmap.json
                sub-NDARINV_ses-15102_fieldmap.nii.gz
            xfm/
                sub-NDARINV_ses-15102_from-extdhcp40wk_to-dwi_mode-image.nii.gz
                sub-NDARINV_ses-15102_from-dwi_to-T2w_mode-image.mat
                sub-NDARINV_ses-15102_from-dwi_to-extdhcp40wk_mode-image.nii.gz
                sub-NDARINV_ses-15102_from-T2w_to-dwi_mode-image.mat
            qc/
                sub-NDARINV_ses-15102_qc.json
                sub-NDARINV_ses-15102_qc.pdf
```

Any thoughts on why the dwis are not being found? Thanks!

**Comment by alexamousley** [comment]
This seems to be an issue specific to using --recon-only and/or --recon-input. I tested this with other data that I previously processed with QSIprep and it had the same issue of not finding the DWIs.

**Comment by mattcieslak** [comment]
Did this turn out to be a singularity issue?

**Comment by alexamousley** [comment]
I believe this was happening because I was trying to user dHCP preprocessed data. So it was in bids but not in the exact same format as data preprocessed with qsiprep.
