### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.metrics.regression'

### ISSUE THREAD

**Issue by bern-maciel** [PennLINC/qsiprep#395]
Hey developers! Thanks for all your work.

I updated to version 0.15.2, which I run using singularity with the following command:

`singularity run --cleanenv 
-B /data/KNW/b.maciel/data/Glioma_Subs/ 
-B /mnt/resource/b.maciel/qsiprep-workdir/ 
-B /data/KNW/b.maciel/setup/license.txt /data/KNW/b.maciel/setup/qsiprep-0.15.2.sif
/data/KNW/b.maciel/data/Glioma_Subs/ /data/KNW/b.maciel/data/Glioma_Subs/derivatives/
participant
 --nthreads 8
 --skip_bids_validation
--output-space T1w
--template MNI152NLin2009cAsym
--output-resolution 2
--unringing-method mrdegibbs 
--dwi-denoise-window 5
--recon-spec mrtrix_singleshell_ss3t_ACT-hsvs
--fs-license-file /data/KNW/b.maciel/setup/license.txt
-w /mnt/resource/b.maciel/qsiprep-workdir/
--participant_label 0090`

And when QSIPrep is initialising I get the error on the title of this issue. Any ideas?

**Comment by mattcieslak** [comment]
This is probably fixed in 0.15.3, but I'd recommend waiting for the next major release as it looks like the 0.15 series introduced some problems
