### ISSUE TITLE
Reorienting to FSL

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsiprep#411]
I know it's fairly trivial to do so outside of QSIPrep, but what's the potential for reorienting the anatomical images to FSL when running the reorient_fsl pipeline? Generating a study-specific template from the T1s has merit for analyses but currently the reorientation only deals with the DWI/Bvec/Bvals.

Thanks

**Comment by mattcieslak** [comment]
Definitely open for a PR on this one. It should be really easy to reorient the T1ws since they don't have and extra orientation-dependent data

**Comment by mattcieslak** [comment]
There is a reorient_fslstd workflow now!
