### ISSUE TITLE
QSIprep recon_only is stuck at "plot_connectivity" 

### ISSUE THREAD

**Issue by dyhan316** [PennLINC/qsiprep#412]
When I ran the following QSIprep code, `time qsiprep-docker /scratch/connectome/dyhan316/dwMRI/UKB_sample/sub_02_INPUT_4/ /scratch/connectome/dyhan316/dwMRI/time_it/outputs/recon_variety/multi_msmt_noACT/ participant --output_resolution 1.2 --recon_only --recon_input /scratch/connectome/dyhan316/dwMRI/UKB_sample/sub_02_INPUT_4/ --recon_spec mrtrix_multishell_msmt_noACT --fs-license-file /scratch/connectome/dyhan316/dwMRI/license.txt --skip_bids_validation --nthreads 48 --omp_nthreads 24 --stop_on_first_crash` to only do reconstruction using data that was already preprocessed, I got stuck at the following step: 

`
220512-07:17:53,274 nipype.workflow INFO:
         [Node] Finished "schaefer400x17_sift_radius2_count", elapsed time 25.947571s.
220512-07:17:53,282 nipype.workflow INFO:
         [Node] Setting-up "mrtrix_atlasgraph.merge_mats" in "/tmp/work/qsirecon_wf/sub-02_mrtrix_multishell_msmt_noACT/sub_02_space_T1w_desc_preproc_recon_wf/mrtrix_conn/calc_connectivity/mrtrix_atlasgraph/merge_mats".
220512-07:17:53,309 nipype.workflow INFO:
         [Node] Executing "merge_mats" <nipype.interfaces.utility.base.Merge>
220512-07:17:53,310 nipype.workflow INFO:
         [Node] Finished "merge_mats", elapsed time 0.00035s.
220512-07:17:53,431 nipype.workflow INFO:
         [Node] Finished "calc_connectivity", elapsed time 981.023065s.
220512-07:17:56,336 nipype.workflow INFO:
         [Node] Setting-up "qsirecon_wf.sub-02_mrtrix_multishell_msmt_noACT.sub_02_space_T1w_desc_preproc_recon_wf.mrtrix_conn.plot_connectivity" in "/tmp/work/qsirecon_wf/sub-02_mrtrix_multishell_msmt_noACT/sub_02_space_T1w_desc_preproc_recon_wf/mrtrix_conn/plot_connectivity".
220512-07:17:56,338 nipype.workflow INFO:
         [Node] Executing "plot_connectivity" <qsiprep.interfaces.reports.ConnectivityReport>
220512-07:17:57,233 nipype.workflow INFO:
         [Node] Finished "plot_connectivity", elapsed time 0.876184s.`

With the following recon folder tree structure 
![image](https://user-images.githubusercontent.com/34816251/168055967-c0255b1b-7363-495a-8911-6d0d26afd62d.png)

This was also true for when I tried another reconstruction method, `dsi_studio_gqi`. Could anyone tell me what might've gone wrong? Thank yiou!

**Comment by araikes** [comment]
@dyhan316, what version of QSIPrep are you running?

**Comment by bdeck8317** [comment]
@araikes @dyhan316  I am also having this same issue, using singularity v  0.15.4

**Comment by mattcieslak** [comment]
This should be fixed, or at least have a more helpful error message in 0.20.0
