### ISSUE TITLE
matrix files - missing data 

### ISSUE THREAD

**Issue by hbyrne17** [PennLINC/qsiprep#415]
Hello, 

We have recently run QSIrecon on our dataset using the mrtrix_multishell_msmt_ACT-hsvs pipeline, specifying only the Brainnetome atlas. However, in approx. half of the connectivity matrix files there is data missing. For the most part this seems to be occurring within three regions - A4t_L (area 4, precentral gyrus), A7r_R (rostral area 7, superior parietal) and A9l_L (lateral area 9, superior frontal gyrus). One way we thought to troubleshoot this would be to overlay the atlas parcellation over the tractogram to see where the streamlines are terminating (in case these labels do not fully extend into WM), but there is no copy of the registered atlas/parcellation in the output files. Is there a way that we can check the parcellations, or do you have any other suggestions for why this might be happening? I should also note that visual inspection suggests this does not seem to be an issue with the raw DWI data or the tractography. 

Thank you for any help you can provide!

**Comment by araikes** [comment]
Hi @student846,

This is an existing issue with the reconstruction in 0.15.3. See the on-going discussion in #404 (among others).

**Comment by student846** [comment]
Thank you for bringing this to my attention @araikes - much appreciated!

**Comment by mattcieslak** [comment]
This has been fixed for awhile, sorry for not closing
