### ISSUE TITLE
PyAFQ QC report

### ISSUE THREAD

**Issue by 36000** [PennLINC/qsiprep#421]
Hello @mattcieslak , one thing pyAFQ generates is an HTML visualization of the recognized bundles. I wonder if QSIprep generates an overall QC report that could link to this HTML? Not a high priority but if this is easy to do, just link me to the line in the code or an example and I can make the PR.

**Comment by 36000** [comment]
There is a self-contained html file we generate called:
```{prefix_depending_on_dwi_file}_space-RASMM_model-DTI_desc-det-AFQ_viz.html```
It could be identified with the suffix viz and extension html. Also pyAFQ can directly return a path to this.

should I move this into the reportlets directory? Where is reportlets relative to
shim_dir = op.join(runtime.cwd, "study/subject") or output_suffix (I think these are the paths I can see in the pyAFQ workflow) ?

**Comment by mattcieslak** [comment]
It may be best to keep these htmls separate. I believe it's included in the pyafq outputs now too
