### ISSUE TITLE
Connectivity on Gordon333

### ISSUE THREAD

**Issue by raphaelcuhk** [PennLINC/qsiprep#423]
Dear all experts,

Hi, I'm using qsiprep for structural connectivity calculation. And I sucked in gordon333. Here is my code:
qsiprep-docker /Volumes/dataBID /Volumes/output participant --output-resolution 1 --fs-license-file /Applications/freesurfer/license.txt --hmc-model 3dSHORE --recon_input /Volumes/output/qsiprep. May I ask for how could I use FA to define structural connectivity in gordon333?
Thank you very much!!

Best,
Raphael

**Comment by mattcieslak** [comment]
please reopen if you haven't solved this
