### ISSUE TITLE
BrokenProcessPool

### ISSUE THREAD

**Issue by raphaelcuhk** [PennLINC/qsiprep#424]
Hi all,

I tried to run --hmc-model 3dSHORE and got this problem:
<img width="569" alt="截屏2022-05-30 下午2 21 43" src="https://user-images.githubusercontent.com/72928808/170929499-7b62036e-bc45-4930-a06b-7bc6231f0a1c.png">
could anyone help me out?
And if I want to use FA for calculation structural connectivity in gordon333, how could I order the command line?

Thank you all!

**Comment by mattcieslak** [comment]
a couple things could be happening. If your data has only a single shell, 3dSHORE won't work as the hmc model. However, it's more likely that you're running out of memory or trying to open too many processes. I recommend trying to constrain resource usage with --omp-nthreads and --nthreads. There should be lots of examples of changing these in closed issues
