### ISSUE TITLE
Bug in QSIPREP reconstruction pipeline when using --dwi-only

### ISSUE THREAD

**Issue by julfou81** [PennLINC/qsiprep#432]
Originally posted on [Neurostars](https://neurostars.org/t/help-with-qsiprep-reconstruction-pipeline-command/22811), I was directed to QSIPREP GitHub to see if there is a bug or if I did a mistake on the command line:

I am trying to use the qsiprep reconstruction pipeline but the execution quickly crashes, I assume I have a mistake in the command I evoke:

QSIPREP version: 0.16.0RC3
singularity installation
freesurfer folder was created by a previous fmriprep (v 21.0.2) execution
command :
```
study=EcriPark
EXPDIR=/scratch/jsein/BIDS/$study
OUTDIR=
list_sub='CTR13'
part=participant  

singularity run --cleanenv -B /scratch/jsein/BIDS:/work \
 --nv /scratch/jsein/my_images/qsiprep-0.16.0RC3.sif /work/$study  \
 /work/EcriPark/derivatives $part --participant_label $list_sub     \
 -w /work/temp_data_${study}  --fs-license-file /work/freesurfer/license.txt \
 --recon-only --recon-spec mrtrix_multishell_msmt_ACT-hsvs --recon-input /work/$study/derivatives/qsiprep \
--freesurfer-input /work/$study/derivatives/fmriprep/sourcedata/freesurfer 
```

error log:
```
WARNING:py.warnings:TemplateFlow: repository not found at /home/qsiprep/.cache/templateflow. Populating a new TemplateFlow stub.
If the path reported above is not the desired location for TemplateFlow, please set the TEMPLATEFLOW_HOME environment variable.
WARNING:py.warnings:TemplateFlow: repository not found at /home/qsiprep/.cache/templateflow. Populating a new TemplateFlow stub.
If the path reported above is not the desired location for TemplateFlow, please set the TEMPLATEFLOW_HOME environment variable.
IMPORTANT:nipype.workflow:
    Running qsirecon version 0.16.0RC3:
      * BIDS dataset path: /work/EcriPark.
      * Participant list: ['CTR13'].
      * Run identifier: 20220614-235215_7832af95-a925-4521-87dd-2badf42b1f9c.
    
INFO:nipype.workflow:found ['/work/EcriPark/derivatives/qsiprep/sub-CTR13/dwi/sub-CTR13_space-T1w_desc-preproc_dwi.nii.gz'] in /work/EcriPark/derivatives/qsiprep
INFO:nipype.workflow:Missing T1w QSIPrep outputs found: /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_desc-brain_mask.nii.gz /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_desc-preproc_T1w.nii.gz
INFO:nipype.workflow:Missing T1w QSIPrep outputs found: /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5 /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
INFO:nipype.workflow:Freesurfer directory /work/EcriPark/derivatives/fmriprep/sourcedata/freesurfer/sub-CTR13 exists for CTR13
INFO:nipype.workflow:FreeSurfer data will be used to create a HSVS 5tt image.
INFO:nipype.workflow:Anatomical (T1w) available for recon: {'has_qsiprep_5tt_fast': False, 'has_qsiprep_5tt_hsvs': False, 'has_freesurfer_5tt_hsvs': True, 'has_freesurfer': True, 'has_qsiprep_t1w': False, 'has_qsiprep_t1w_transforms': False}
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 129, in validate
    value = Path(value)  # Use pathlib's validation
  File "/usr/local/miniconda/lib/python3.8/pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/local/miniconda/lib/python3.8/pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/miniconda/lib/python3.8/pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 1169, in build_recon_workflow
    retval['workflow'] = init_qsirecon_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 89, in init_qsirecon_wf
    single_subject_wf = init_single_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 232, in init_single_subject_wf
    dwi_recon_wfs[dwi_file] = init_dwi_recon_workflow(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/build_workflow.py", line 49, in init_dwi_recon_workflow
    registered_anat_wf, available_anatomical_data = init_dwi_recon_anatomical_workflow(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/anatomical.py", line 440, in init_dwi_recon_anatomical_workflow
    nio.FreeSurferSource(
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 202, in __init__
    self.inputs.trait_set(**inputs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/has_traits.py", line 1520, in trait_set
    setattr(self, name, value)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 131, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'subjects_dir' trait of a FSSourceInputSpec instance must be a pathlike object or string representing an existing directory, but a value of 'None' <class 'str'> was specified.
```

output log:
```
220614-23:53:30,36 nipype.workflow IMPORTANT:
	 
    Running qsirecon version 0.16.0RC3:
      * BIDS dataset path: /work/EcriPark.
      * Participant list: ['CTR13'].
      * Run identifier: 20220614-235215_7832af95-a925-4521-87dd-2badf42b1f9c.
    
220614-23:53:30,391 nipype.workflow INFO:
	 found ['/work/EcriPark/derivatives/qsiprep/sub-CTR13/dwi/sub-CTR13_space-T1w_desc-preproc_dwi.nii.gz'] in /work/EcriPark/derivatives/qsiprep
220614-23:53:30,393 nipype.workflow INFO:
	 Missing T1w QSIPrep outputs found: /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_desc-brain_mask.nii.gz /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_desc-preproc_T1w.nii.gz
220614-23:53:30,393 nipype.workflow INFO:
	 Missing T1w QSIPrep outputs found: /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5 /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
220614-23:53:30,397 nipype.workflow INFO:
	 Freesurfer directory /work/EcriPark/derivatives/fmriprep/sourcedata/freesurfer/sub-CTR13 exists for CTR13
220614-23:53:30,400 nipype.workflow INFO:
	 FreeSurfer data will be used to create a HSVS 5tt image.
220614-23:53:30,401 nipype.workflow INFO:
	 Anatomical (T1w) available for recon: {'has_qsiprep_5tt_fast': False, 'has_qsiprep_5tt_hsvs': False, 'has_freesurfer_5tt_hsvs': True, 'has_freesurfer': True, 'has_qsiprep_t1w': False, 'has_qsiprep_t1w_transforms': False}
```

Thank you for your help!

**Comment by julfou81** [comment]
Hi! Thank you for your feedback! I tried with the same options but got the same error. I wonder if it is because I am using a study where the participants have sessions? Indeed the qsiprep output does acknowledge correctly the presence of the sessions but it is not the case in the freesurfer output. I wonder if the recon module does not get confused by this?

I will try for another study with no session to see if I get the same error.

**Comment by julfou81** [comment]
I think I found what I was doing wrong. I got confused when I read that fs-recon was excised out of QSIPREP and needed to be done with an external software. I thought that implied to use the `--dwi-only` option. 

When using the QSIPREP preprocessing output that was run without the `--dwi-only` option, the recon is now going further.

**Comment by mattcieslak** [comment]
ahhhh 🤦  you've uncovered a bug. When someone runs `--dwi-only`, qsiprep is supposed to grab the skull stripped t1w from freesurfer and use it in the anatomical workflow. The non-`--dwi-only` processes (skull strips, aligns to an MNI template) the t1w in the BIDS inputs. It looks like you can avoid the bug by processing the t1w during the dwi preprocessing workflow and then incorporating the freesurfer data during reconstruction.

good debugging, thanks for figuring this out!

**Comment by JayJoemary** [comment]
> Originally posted on [Neurostars](https://neurostars.org/t/help-with-qsiprep-reconstruction-pipeline-command/22811), I was directed to QSIPREP GitHub to see if there is a bug or if I did a mistake on the command line:
> 
> I am trying to use the qsiprep reconstruction pipeline but the execution quickly crashes, I assume I have a mistake in the command I evoke:
> 
> QSIPREP version: 0.16.0RC3 singularity installation freesurfer folder was created by a previous fmriprep (v 21.0.2) execution command :
> 
> ```
> study=EcriPark
> EXPDIR=/scratch/jsein/BIDS/$study
> OUTDIR=
> list_sub='CTR13'
> part=participant  
> 
> singularity run --cleanenv -B /scratch/jsein/BIDS:/work \
>  --nv /scratch/jsein/my_images/qsiprep-0.16.0RC3.sif /work/$study  \
>  /work/EcriPark/derivatives $part --participant_label $list_sub     \
>  -w /work/temp_data_${study}  --fs-license-file /work/freesurfer/license.txt \
>  --recon-only --recon-spec mrtrix_multishell_msmt_ACT-hsvs --recon-input /work/$study/derivatives/qsiprep \
> --freesurfer-input /work/$study/derivatives/fmriprep/sourcedata/freesurfer 
> ```
> 
> error log:
> 
> ```
> WARNING:py.warnings:TemplateFlow: repository not found at /home/qsiprep/.cache/templateflow. Populating a new TemplateFlow stub.
> If the path reported above is not the desired location for TemplateFlow, please set the TEMPLATEFLOW_HOME environment variable.
> WARNING:py.warnings:TemplateFlow: repository not found at /home/qsiprep/.cache/templateflow. Populating a new TemplateFlow stub.
> If the path reported above is not the desired location for TemplateFlow, please set the TEMPLATEFLOW_HOME environment variable.
> IMPORTANT:nipype.workflow:
>     Running qsirecon version 0.16.0RC3:
>       * BIDS dataset path: /work/EcriPark.
>       * Participant list: ['CTR13'].
>       * Run identifier: 20220614-235215_7832af95-a925-4521-87dd-2badf42b1f9c.
>     
> INFO:nipype.workflow:found ['/work/EcriPark/derivatives/qsiprep/sub-CTR13/dwi/sub-CTR13_space-T1w_desc-preproc_dwi.nii.gz'] in /work/EcriPark/derivatives/qsiprep
> INFO:nipype.workflow:Missing T1w QSIPrep outputs found: /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_desc-brain_mask.nii.gz /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_desc-preproc_T1w.nii.gz
> INFO:nipype.workflow:Missing T1w QSIPrep outputs found: /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5 /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
> INFO:nipype.workflow:Freesurfer directory /work/EcriPark/derivatives/fmriprep/sourcedata/freesurfer/sub-CTR13 exists for CTR13
> INFO:nipype.workflow:FreeSurfer data will be used to create a HSVS 5tt image.
> INFO:nipype.workflow:Anatomical (T1w) available for recon: {'has_qsiprep_5tt_fast': False, 'has_qsiprep_5tt_hsvs': False, 'has_freesurfer_5tt_hsvs': True, 'has_freesurfer': True, 'has_qsiprep_t1w': False, 'has_qsiprep_t1w_transforms': False}
> Process Process-2:
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 129, in validate
>     value = Path(value)  # Use pathlib's validation
>   File "/usr/local/miniconda/lib/python3.8/pathlib.py", line 1042, in __new__
>     self = cls._from_parts(args, init=False)
>   File "/usr/local/miniconda/lib/python3.8/pathlib.py", line 683, in _from_parts
>     drv, root, parts = self._parse_args(args)
>   File "/usr/local/miniconda/lib/python3.8/pathlib.py", line 667, in _parse_args
>     a = os.fspath(a)
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 1169, in build_recon_workflow
>     retval['workflow'] = init_qsirecon_wf(
>   File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 89, in init_qsirecon_wf
>     single_subject_wf = init_single_subject_wf(
>   File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 232, in init_single_subject_wf
>     dwi_recon_wfs[dwi_file] = init_dwi_recon_workflow(
>   File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/build_workflow.py", line 49, in init_dwi_recon_workflow
>     registered_anat_wf, available_anatomical_data = init_dwi_recon_anatomical_workflow(
>   File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/anatomical.py", line 440, in init_dwi_recon_anatomical_workflow
>     nio.FreeSurferSource(
>   File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 202, in __init__
>     self.inputs.trait_set(**inputs)
>   File "/usr/local/miniconda/lib/python3.8/site-packages/traits/has_traits.py", line 1520, in trait_set
>     setattr(self, name, value)
>   File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 131, in validate
>     self.error(objekt, name, str(value))
>   File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
>     raise TraitError(
> traits.trait_errors.TraitError: The 'subjects_dir' trait of a FSSourceInputSpec instance must be a pathlike object or string representing an existing directory, but a value of 'None' <class 'str'> was specified.
> ```
> 
> output log:
> 
> ```
> 220614-23:53:30,36 nipype.workflow IMPORTANT:
> 	 
>     Running qsirecon version 0.16.0RC3:
>       * BIDS dataset path: /work/EcriPark.
>       * Participant list: ['CTR13'].
>       * Run identifier: 20220614-235215_7832af95-a925-4521-87dd-2badf42b1f9c.
>     
> 220614-23:53:30,391 nipype.workflow INFO:
> 	 found ['/work/EcriPark/derivatives/qsiprep/sub-CTR13/dwi/sub-CTR13_space-T1w_desc-preproc_dwi.nii.gz'] in /work/EcriPark/derivatives/qsiprep
> 220614-23:53:30,393 nipype.workflow INFO:
> 	 Missing T1w QSIPrep outputs found: /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_desc-brain_mask.nii.gz /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_desc-preproc_T1w.nii.gz
> 220614-23:53:30,393 nipype.workflow INFO:
> 	 Missing T1w QSIPrep outputs found: /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5 /work/EcriPark/derivatives/qsiprep/sub-CTR13/anat/sub-CTR13_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
> 220614-23:53:30,397 nipype.workflow INFO:
> 	 Freesurfer directory /work/EcriPark/derivatives/fmriprep/sourcedata/freesurfer/sub-CTR13 exists for CTR13
> 220614-23:53:30,400 nipype.workflow INFO:
> 	 FreeSurfer data will be used to create a HSVS 5tt image.
> 220614-23:53:30,401 nipype.workflow INFO:
> 	 Anatomical (T1w) available for recon: {'has_qsiprep_5tt_fast': False, 'has_qsiprep_5tt_hsvs': False, 'has_freesurfer_5tt_hsvs': True, 'has_freesurfer': True, 'has_qsiprep_t1w': False, 'has_qsiprep_t1w_transforms': False}
> ```
> 
> Thank you for your help!
Hi
I have had the same problem
![图片1](https://user-images.githubusercontent.com/110291636/228721170-08299aa0-9045-4913-869f-0bc976a14bc1.jpg)
But，I use the code following like this:
qsiprep /media/zhangming/E88686698686708/test/wx/test_out /media/zhangming/E88686698686708/test/wx/test_out/derivatives participant participant-label 001 --skip_bids_validation --output-resolution 2 --fs-license-flie /media/zhangming/E88686698686708/test/wx/test_out/license
1.QSIprep is be installed like this:
docker pull PennLINC/qsiprep
pip install --user --upgrade qsiprep-container.
2.My dataset is formatted as BIDS format.
So, I have consult you how it could be solved.
Thank you very much.

**Comment by mattcieslak** [comment]
This is a fairly old issue, could you please open a new one if you're still having problems?

**Comment by JayJoemary** [comment]
好啊！！！
