### ISSUE TITLE
HSVS 5TT Output not in DWI space

### ISSUE THREAD

**Issue by smeisler** [PennLINC/qsiprep#439]
Hello,

I am using 0.16.0RC3 QSIRecon to make HSV segmentations. In the output `anat` directory I see two files:
`$SUBJECT_desc-preproc_space-fsnative_desc-hsvs_5tt.mif` and
`$SUBJECT_desc-preproc_desc-hsvs_5tt.nii.gz`

The first is explicitly in `fsnative` space, but I thought that the `desc-hsvs` file was supposed to be in DWI/T1w space, as suggested by the [anatomical recon workflow code](https://github.com/PennLINC/qsiprep/blob/f0a12fa002ea99cad97f2b5e40c1517d0569e14c/qsiprep/workflows/recon/anatomical.py#L486)
<img width="704" alt="image" src="https://user-images.githubusercontent.com/27028726/177070217-6222fe24-a930-4583-8daa-cdde78e6e13e.png">

For evidence, here is the QSIPrep b0 ref and QSIRecon 5tt side by side:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/27028726/177070306-0bce56e8-05e0-418c-803e-e9641769cab8.png">

Is this the intended output or a bug? I am trying some GMWMI seeding ACT tractography outside of the QSIprep/recon so having the 5tt in subject space would be nice.

Thanks,
Steven

**Comment by mattcieslak** [comment]
Hi @smeisler there should be 2 versions of the 5tt image. One will be aligned with the freesurfer input and the other will be aligned to the QSIPrep T1w image.

**Comment by smeisler** [comment]
Turns out this was just a subject specific error, closing.
