### ISSUE TITLE
SHOREline Iteration registration error

### ISSUE THREAD

**Issue by aiims-himanshu** [PennLINC/qsiprep#440]
Hi, I have an irregular error that occurs at 1/6-7 preprocessing subjects, it is across SHORELine itreation predicted value registration were in certain predicted variable are not found in the directories, My line of code.
#QSIprep preprocessing (315m/subject)
sudo docker run -ti --rm \
-v /media/himanshu/m2/test1/input:/data:ro \
-v /media/himanshu/m2/test1/output:/out \
-v /media/himanshu/m2/test1/tmp1:/w \
-v /home/himanshu/freesurfer/:/freesurfer \
pennbbl/qsiprep \
/data /out \
participant \
-w /w \
--fs-license-file /freesurfer/license.txt \
--verbose \
--dwi_denoise_window auto \
--denoise_method dwidenoise \
--unringing_method mrdegibbs \
--b0-to-t1w-transform Affine \
--hmc-transform Affine \
--hmc_model 3dSHORE \
--shoreline_iters 5 \
--b0-motion-corr-to iterative \
--skull-strip-template NKI \
--skull-strip-fixed-seed \
--fmap-bspline \
--force-syn \
--output-space T1w \
--output_resolution 2 \
--write_graph \
--notrack

System is 16 Core, 128 GB RAM and Space 1.8/7.4 TB,

Following error is not regular however it does occur at certain instances. Rerun twice or thrice solve the issue. Data is BIDS format.
first crash- register 24-62
second crash- register 11

just recently started using fmriprep/qsiprep pipeline in last few months. 

[crash-20220710-135102-root-_register_to_predicted24-62fdd037-2403-4be0-9843-22df4a51b913.txt](https://github.com/PennLINC/qsiprep/files/9079520/crash-20220710-135102-root-_register_to_predicted24-62fdd037-2403-4be0-9843-22df4a51b913.txt)
[crash-20220710-155944-root-_register_to_predicted11-f2d5f1a9-ef0a-4be3-aace-49bb0c659121.txt](https://github.com/PennLINC/qsiprep/files/9079521/crash-20220710-155944-root-_register_to_predicted11-f2d5f1a9-ef0a-4be3-aace-49bb0c659121.txt)

**Comment by mattcieslak** [comment]
Hi! I think you should regulate CPU usage. Maybe something like adding `--nthreads 15 --omp-nthreads 3`

**Comment by aiims-himanshu** [comment]
Hi, CPU regulation resolved the issue as of now completed 5 subjects with the command running the second batch with 8, i restricted nthreads 14, and omp-nthreads came down to 8 (Automatically). also following aspect helped to reduce preprocessing time by 30% in my case with batch process taking 5 subjects at a time.

Thanks
