### ISSUE TITLE
Qsiprep stuck after creating mrtrix_multishell_msmt.recon_wf.msmt_csd.plot_peaks for a subset of subjects

### ISSUE THREAD

**Issue by akelkar26** [PennLINC/qsiprep#441]
Hi,
I am using Qsiprep version 0.13.0RC1 on Docker. 
I have successfully run the reconstruction only pipeline using MRTrix on 18 subjects so far from a study. I have an issue with 2 subjects. 
The docker seems to hang after the csd plot peaks creation step for both subjects. Last time I checked it was still up for 2 days when usually it takes 4-6 hours. 
I deleted the output folders and the temp space and re-ran it twice but it still doesn't seem to converge.

Here is my docker command:
`screen docker run -ti \
-v /Users/neurouser1/Documents/TMS_Aphasia/bids_directory/:/data \
-v /Users/neurouser1/Documents/TMS_Aphasia/qsiprep_mrtrixrecononly/:/out \
-v /Users/neurouser1/Documents/fs_files/:/license \
-v /Users/neurouser1/Documents/TMS_Aphasia/scratch/:/scratch \
-v /Users/neurouser1/Documents/TMS_Aphasia/qsiprepout_dwionly/qsiprep/:/recon_input \
pennbbl/qsiprep:0.13.0RC1 \
/data /out participant \
--participant_label sub-TMSA15 \
--recon_input /recon_input/ \
--recon_only \
--recon_spec mrtrix_multishell_msmt \
--fs-license-file /license/license.txt \
-w /scratch/ \
--output-resolution 1.3 \
--n_cpus 15 \
--omp-nthreads 8 \
--mem_mb 150000 \`

Here is the step it gets stuck:
`  [Node] Setting-up "qsirecon_wf.sub-TMSA15_mrtrix_multishell_msmt.recon_wf.msmt_csd.plot_peaks" in "/scratch/qsirecon_wf/sub-TMSA15_mrtrix_multishell_msmt/recon_wf/msmt_csd/_dwi_file_..recon_input..sub-TMSA15..ses-BRAINRESEARCHCOSLETT..dwi..sub-TMSA15_ses-BRAINRESEARCHCOSLETT_space-T1w_desc-preproc_dwi.nii.gz/plot_peaks".
220708-16:48:44,421 nipype.workflow INFO:
         [Node] Running "plot_peaks" ("qsiprep.interfaces.reports.ReconPeaksReport")
220708-16:49:16,219 nipype.workflow INFO:
         b''
220708-16:49:16,219 nipype.workflow INFO:
         b''
220708-16:50:56,847 nipype.workflow INFO:
         [Node] Finished "qsirecon_wf.sub-TMSA15_mrtrix_multishell_msmt.recon_wf.msmt_csd.plot_peaks".`
         
I am also attaching the complete error log if it's helpful.
[TMSA15_baseline_mrtrixreconerror.txt](https://github.com/PennLINC/qsiprep/files/9084511/TMSA15_baseline_mrtrixreconerror.txt)

Could you please advise? 
Thank you
Best,
Apoorva

**Comment by smeisler** [comment]
Hello,

You can try skipping the ODF plots by adding `--skip-odf-reports` to your qsiprep command.

Best,
STeven

**Comment by akelkar26** [comment]
Hi Steven,

Thank you so much for your response. 
I think I am using an older version of qsiprep (0.13.0RC1 on Docker) which doesn't have the `--skip-odf-reports` option.
Is there another option I could apply to get it working?

Thank you
Best,
Apoorva

**Comment by smeisler** [comment]
I'm not sure of other options while sticking with 0.13.0RC1 besides trying to up your memory allowances.

I would suggest upgrading to a more recent version though for better reconstruction workflows. The HSVS options for MrTrix are appreciably better than the older options that relied on FSL FAST!

**Comment by akelkar26** [comment]
Thanks Steven. I will try increasing the memory allowance and see if it works. 
I wanted to keep the qsiprep version specific to a project (which started a year ago) but will definitely use the new versions with the upgrades in the reconstruction pipelines for new projects. 
I might also rerun data from this project with the new version once I am through with processing it on the old version. 
Thank you

**Comment by smeisler** [comment]
Okay good luck! I don't think it is too big a deal if you preprocess with one version and reconstruct with another, as long as 1) there have not been any big changes to methods you are using in preprocessing, and 2) you are consistent across subjects.

If you do preprocess with the new version, DO NOT use the same working directory as the old version.
