### ISSUE TITLE
 from qsiprep.cli.run import main ModuleNotFoundError: No module named 'qsiprep.cli'

### ISSUE THREAD

**Issue by xxbelight** [PennLINC/qsiprep#444]
Hi I'm trying to run qsiprep-docker , but I keep getting error like "ModuleNotFoundError: No module named 'qsiprep.cli'"
It used to be fine, but after I upgraded new qsiprep, I got this error . 

 qsiprep-docker /home/connectome/lsy0174/PTSDkimbo /home/connectome/lsy0174/PTSDkimbo/output --output_resolution 1.2 --unringing_method mrdegibbs --fs-license-file /home/connectome/lsy0174/license.txt --skip_bids_validation --ignore fieldmaps -freesurfer-input --participant-label hc032
['/home/connectome/lsy0174/.local/bin/qsiprep-docker', '/home/connectome/lsy0174/PTSDkimbo', '/home/connectome/lsy0174/PTSDkimbo/output', '--output_resolution', '1.2', '--unringing_method', 'mrdegibbs', '--fs-license-file', '/home/connectome/lsy0174/license.txt', '--skip_bids_validation', '--ignore', 'fieldmaps', '-freesurfer-input', '--participant-label', 'hc032']
RUNNING: docker run --rm -it -v /home/connectome/lsy0174/reesurfer-input:/usr/local/miniconda/lib/python3.8/site-packages/qsiprep:ro -v /home/connectome/lsy0174/license.txt:/opt/freesurfer/license.txt:ro -v /home/connectome/lsy0174/PTSDkimbo:/data:ro -v /home/connectome/lsy0174/PTSDkimbo/output:/out pennbbl/qsiprep:0.15.4 /data /out participant --output_resolution 1.2 --unringing_method mrdegibbs --skip_bids_validation --ignore fieldmaps --participant-label hc032
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 5, in <module>
    from qsiprep.cli.run import main

**Comment by aiims-himanshu** [comment]
hi, i see you have given freesurfer-input command with no valid input, probably it is import error. remove and rerun the command
