### ISSUE TITLE
Various `autorecon` errors

### ISSUE THREAD

**Issue by dyhan316** [PennLINC/qsiprep#447]
When running dwi preprocessing on BIDS compatible data, 10% of the subjects gave out crash errors, which could be divided into three categories:

1. `autorecon30` error
2. `autorecon_surfs1` error
3. `autorecon1` error

Upon research, I found that he last error could be resolved by ACPC alignment. However, I cannot seem to be able to find the answers to the 1. and 2. crash errors. 
#note: the qsiprep version used was 14.3. The older version was used as the current version does not have freesurfer.

Any help would be recommended! Thank you!

p.s. due to the long length of the crash reports, please refer to the following notion link for carsh logs : https://www.notion.so/Crash-reports-for-reporting-purposes-7088f020a7b645d3b636031a24eb7d4d

**Comment by mattcieslak** [comment]
Hi @dyhan316 these errors can happen sometimes when the t1w image has a lot of motion in it. You can run freesurfer outside of qsiprep and still use the results for any of the reconstruction workflows that use it (like hsvs)
