### ISSUE TITLE
Way to use MNI Pediatric Template?

### ISSUE THREAD

**Issue by dyhan316** [PennLINC/qsiprep#459]
I was wondering if there is a way to use MNI Pediatric template, like how `--infant` option can be used to use the MNI infant template instead of the adult template. 

Is there a way to do this in QSIPREP? (for example, by changing the json files?) 

Thank you!

**Comment by mattcieslak** [comment]
Hi Danny,

I suggest using --dwi-only and doing all your infant-specific anatomical work outside of qsiprep. The T1w-based registration is good for getting gray matter atlases into alignment with the DWIs, but is not great for lining up white matter structures. I'd suggest using DSI Studio or MRtrix3 to register the DWI data directly to a template

**Comment by dyhan316** [comment]
Thank you for the response!

Is my understanding correct that you are suggesting: 
1. Run freesurfer with MNI Pediatric template by itself (not using QSIPREP)
2. Run preprocess only dwi by using dwi-only
3. Use the results of the previous #2 step and register the dwi image to the preprocessed results of the #1 step. 
4. Use the "registered" dwi image (and the freesurfer outcomes from step1) as the inputs for qsiprep recon-only

(Sorry for asking, as I am not adept at MRI preprocessing, so wanted to make sure if my understanding was right!)

**Comment by scchueler** [comment]
I want to add to this:
I'm using the --infant flag for preprocessing WITHOUT the --dwi-only flag ([due to this issue](https://github.com/PennLINC/qsiprep/issues/432)). 
However, it seems that QSIprep doesn't recognize the flag properly as the transforms in the sub/anat directory are named "...from-MNI152NLin2009cAsym_to-T1w..."

**Comment by dyhan316** [comment]
Thank you for your comment @scchueler !  do you mean that you preprocess T1w separately (perhaps using infant recon all), then provide them as inputs to QSIPREP for dwi preprocessing while doing `--infant` and `--dwi-only`?

**Comment by dyhan316** [comment]
If possible, could you share the command that you used to do this? I am trying to do something like what you said because some of our subjects are 0~2 years old so conventional skull stripping fails, but I can't get the QSIPREP to take in a pre-done freesurfer result as input

**Comment by mattcieslak** [comment]
You should have no trouble skull stripping in recent versions. We've switched to synthstrip
