### ISSUE TITLE
Gradients don't match

### ISSUE THREAD

**Issue by angelwong55** [PennLINC/qsiprep#473]
Hi,

I got the following crash report when running qsiprep 0.15.2 for two DWI data collected with two different PE directions:

> Node: qsiprep_wf.single_subject_JF220518_wf.dwi_preproc_wf.confounds_wf.concat
> Working directory: /home/awong/Scratch/qsiprep_wf/single_subject_JF220518_wf/dwi_preproc_wf/confounds_wf/concat
> 
> Node inputs:
> 
> denoising_confounds = /home/awong/Scratch/qsiprep_wf/single_subject_JF220518_wf/dwi_preproc_wf/pre_hmc_wf/rpe_concat/merge__merged_confounds.csv
> fd = /home/awong/Scratch/qsiprep_wf/single_subject_JF220518_wf/dwi_preproc_wf/confounds_wf/fdisp/fd_power_2012.txt
> motion = /home/awong/Scratch/qsiprep_wf/single_subject_JF220518_wf/dwi_preproc_wf/confounds_wf/add_motion_headers/eddy_correctedspm_rp_motion.tsv
> original_bvals = ['/home/awong/Scratch/qsiprep_wf/single_subject_JF220518_wf/dwi_preproc_wf/pre_hmc_wf/rpe_concat/merge__merged.bval']
> original_bvecs = ['/home/awong/Scratch/qsiprep_wf/single_subject_JF220518_wf/dwi_preproc_wf/pre_hmc_wf/rpe_concat/merge__merged.bvec']
> original_files = ['/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-PA_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-AP_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-AP_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-AP_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-AP_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-AP_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-AP_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-AP_dwi.nii', '/home/awong/Data/appetitive/raw_mri_data/bidsnii/sub-JF220518/dwi/sub-JF220518_dir-AP_dwi.nii']
> sliceqc_file = /home/awong/Scratch/qsiprep_wf/single_subject_JF220518_wf/dwi_preproc_wf/hmc_sdc_wf/eddy/eddy_corrected.eddy_outlier_n_sqr_stdev_map
> 
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
>     self.procs[jobid].run(updatehash=updatehash)
>   File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
>     result = self._run_interface(execute=True)
>   File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
>     return self._run_command(execute)
>   File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
>     raise NodeExecutionError(
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node concat.
> 
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
>     runtime = self._run_interface(runtime)
>   File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/confounds.py", line 53, in _run_interface
>     combined_out, confounds_list = _gather_confounds(
>   File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/confounds.py", line 172, in _gather_confounds
>     raise Exception("Gradients don't match. File a bug report!")
> Exception: Gradients don't match. File a bug report!
> 
Here is the command used to run qsiprep:
`/usr/local/miniconda/bin/qsiprep /home/awong/Data/appetitive/raw_mri_data/bidsnii /home/awong/Data/appetitive/derivatives/qsiprep-0.15.2 participant -w /home/awong/Scratch --output-resolution 1.2 --fs-license-file /home/awong/fmriprep/license.txt --participant-label JF220518
`
How to solve this issue?

Thanks,
Angel

**Comment by cookpa** [comment]
I think this was fixed by #403. v0.15.X had a few serious bugs, I would recommend using [0.16.0RC3 ](https://github.com/PennLINC/qsiprep/releases/tag/0.16.0RC3)

**Comment by angelwong55** [comment]
Thanks @cookpa I will try 0.16.0RC3

**Comment by angelwong55** [comment]
I tried 0.16.0RC3 and it completed without errors.
