### ISSUE TITLE
can't start qsiprep on ubuntu

### ISSUE THREAD

**Issue by gcetin99** [PennLINC/qsiprep#475]
Hey there, I'm trying to start qsiprep on Ubuntu, but with the commands below, but I keep getting an error. Can you help me resolve this issue please?

(base) ae-grotheer@pc04679-ubuntu:~$ qsiprep-docker \ /home/ae-grotheer/Desktop/my_dataset / home/ae-grotheer/Desktop/my_dataset participant --output-resolution 1.2 --fs-license-file /fslicense.txt

RUNNING: docker run --rm -it -v /fslicense.txt:/opt/freesurfer/license.txt:ro -v /home/ae-grotheer/ /home/ae-grotheer/Desktop/my_dataset:/data:ro -v /home/ae-grotheer/Desktop/my_dataset:/out pennbbl/qsiprep:0.15.4 /data /out participant --output-resolution 1.2

**Comment by cookpa** [comment]
v0.15.X has bugs, try [0.16.0RC3](https://github.com/PennLINC/qsiprep/releases/tag/0.16.0RC3).

Hopefully that will fix it but if you have errors, it's best to include both the command and the output.
