### ISSUE TITLE
bvecs , fsl and dipy

### ISSUE THREAD

**Issue by kodiweera** [PennLINC/qsiprep#480]
Hi Matt,
Does fsl use image axes for bvecs. I don't know what convention dipy uses. The question is whether the qsiprep-bvecs can directly be used  in both dipy and fsl. Other fact to consider is dipy uses RAS coordinate system while I've seen probably qsiprep images-output are in LPS. Do I have to convert LPS to RAS before enter into dipy?

What's the tool internally used to convert between right handed coordinates and left handed coordinates (neurological vs radiological)?

I have some fsl data in LAS coordinates that I'd like to process in dipy. Do you have recommendation for a tool that I can convert these fsl data to DIPY compatible ( both image and bvecs) format?

Thanks
Chandana

**Comment by mattcieslak** [comment]
Hi Chandana,

FSL does not use the image axes for bvecs *unless the image is in LAS+ voxel orientation*.  DIPY uses the image axis orientation regardless of the voxel direction. So LAS+ Will work in both dipy and fsl.

It is worth thinking about the difference between [voxel coordinates and world coordinates](https://nipy.org/nibabel/coordinate_systems.html).

**Comment by kodiweera** [comment]
> > DIPY uses the image axis orientation regardless of the voxel direction
> 
> Thanks , Matt, for the reply. That helped! So, fsl always uses voxel orientation for bvecs? It helps to know "DIPY uses the image axis orientation regardless of the voxel direction". In literature, I've seen data is converted into RAS+ before working with dipy so that voxel coordinsates match world coordinates. I've also seen some flip/permutate x or y or z of bvecs when working with dipy/mrtrix depending on the orientation of the data.
> 
> If dipy treats data in RAS+ image axis convention, then in the case of LAS+ data, should the x bvecs be flipped to -x?
> 
> Thanks for your clarifications. Chandana

When fitting it should come down to intensities and relavant diff drections; there's no more voxels or world coordinates. Coordinates only matters when saving/storing data. However, it's good to know how these things handle inside each software.
