### ISSUE TITLE
Is there a way to skip dwi FSL preprocessing completely? 

### ISSUE THREAD

**Issue by dyhan316** [PennLINC/qsiprep#494]
I am trying to do preprocessing and reconstruction on minimally preprocessed ABCD dwi data, which I was told, already had eddy and TOPUP done on them.

I want to configure qsiprep so that those two are not applied, but cannot find the right command to do so. Is there a way to do this?

Thank you in advance for your reply :)

**Comment by mattcieslak** [comment]
Hi! Where are you getting the ABCD data from? The official release does not use TOPUP and eddy

**Comment by chrisadamsonmcri** [comment]
I have this question as well but for non-public data. Is it possible to get qsiprep to skip topup and eddy and just do the resampling and alignment to the anatomical templates?
