### ISSUE TITLE
Patch2Self and needed Resolution 

### ISSUE THREAD

**Issue by lizannea** [PennLINC/qsiprep#497]
Dear Experts, 

This is such an amazing and flexible pipeline!

After successfully running the pre-processed comment below with QSIPrep version:0.16.1. After re-run the comment below, but now used --denoise-method patch2self to denoise my images instead of --denoise-method dwidenoise, it didn't run to completion.
Comment:
#!/bin/bash
#SBATCH -J qsiprep
#SBATCH --time=12:00:00
#SBATCH -n 1
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=12G
#SBATCH --gres=gpu					# request GPU access, can specify number of GPUs with --gres=gpu:2 (https://supercomputing.swin.edu.au/docs/2-ozstar/oz-partition.html#requesting-gpus)
#SBATCH --tmp=50GB
subj=$1

bids_root_dir="/fred/oz251/Arla/conversion_LA"
container_dir="/fred/oz251/containers/qsiprep-0.16.1.sif"
derivs_dir="/fred/oz251/Arla/derivatives/LA/qsiprep/96/ssff"

module load apptainer/latest  

apptainer run --cleanenv --nv -B /fred/oz251/Arla:/data -B $derivs_dir:/output $container_dir \
/data/conversion_LA /output \
participant \
--participant-label $subj \
--fs-license-file $FS_LICENSE \
--eddy-config /data/conversion_LA/code/LA/qsiprep/eddy_params.json \
--nthreads 2 \
--mem_mb 24000 \
--output-resolution 2 \
--denoise-method dwidenoise \
--unringing-method mrdegibbs \
--resource-monitor \
-w /data/derivative--eddy-config /data/conversion_LA/code/LA/qsiprep/eddy_params.json \
--nthreads 2 \
--mem_mb 24000 \
--output-resolution 2 \
--denoise-method dwidenoise \
--unringing-method mrdegibbs \
--resource-monitor \
-w /data/derivatives/LA/qsiprep/96/ssff/work >& qsiprep_ssff_$(date -Iseconds).log

**Patch2Self denoising:**
- This generated the following output: 
[qsiprep_ssff_p2s_2022-12-02T14:19:37+1100.txt](https://github.com/PennLINC/qsiprep/files/10149732/qsiprep_ssff_p2s_2022-12-02T14.19.37%2B1100.txt)
- Would you know what the problem could be? I tried to increase the run time and the amount of memory available. 
- qsiprep command with P2S: apptainer run --cleanenv --nv -B /fred/oz251/Arla:/data -B $derivs_dir:/output $container_dir \
/data/conversion_LA /output participant --participant-label 096 --fs-license-file /home/larnoldy/private/fs_license_linux.txt --eddy-config /data/conversion_LA/code/LA/qsiprep/eddy_params.json --nthreads 2 --mem_mb 24000 --output-resolution 2 --denoise-method patch2self --unringing-method mrdegibbs --resource-monitor -w /work

**Resolution:**
- I would also like to know what your recommendation is about up and down sampling, when using multiple datasets. The studies I am comparing have different resolutions, and one is isometric. I have included an overview of the included studies (see below). The end goal is to use connectome MRtrix tools and TractSeg after pre-processing the data through QSIprep and use a part of the “mrtrix_multishell_msmt_ACT-hsvs” reconstruction workflow.
- What would be the ideal resolution and can I bring the different studies to the same resolution?
- In the readthedocs the following is mentioned: ‘Some post-processing pipelines such as fixel-based analysis recommend resampling your output to at least 1.3mm resolution.  Is this also the case for tractography and connectoom analysis? 
- Should I upsample during the pre-processing process as it will happen at the end of the preprocessing steps (include --output-resolution 1.3) OR include it--output-resolution 1.3 during the reconstruction? 

Thank you so much,
Lizanne

@civier @davidjwhite_33

**Comment by ShreyasFadnavis** [comment]
Hi @lizannea ! Thanks for reporting this. It seems to be an issue relating to parallel execution of Patch2Self via QSIPrep. Can you tell us the shape/dimensions and resolution of your data? We can make suggestions accordingly!

@mattcieslak may know more about this -- but a quick workaround maybe to just denoise the data before passing it through QSIPrep: i.e. via DIPY: https://dipy.org/documentation/1.5.0/examples_built/denoise_patch2self/#example-denoise-patch2self (and switch denoising off in the QSIPrep command that you are running)...

**Comment by lizannea** [comment]
Hi @ShreyasFadnavis, 
￼
Thank you for your response! I have included some of the details of my data in the figure below:
[Included studies.pdf](https://github.com/PennLINC/qsiprep/files/10153341/Included.studies.pdf)

Apologies, this image needed to be included in my previous message.

**Comment by ShreyasFadnavis** [comment]
Hi @lizannea -- the acquisition looks ABCD style and can confirm that Patch2Self should work well out of the box 👍🏽 I think its an issue of threading/multiprocessing. @mattcieslak do you have an intuition as to what maybe happening here?

**Comment by lizannea** [comment]
Thank you for clarifying this in such detail. I will let you know if the job runs completely after including the increased GB per cpu. 

Lastly, I wanted to clarify if I’ll need to upsample to a resolution of 1.3 for connectomic analysis and tractography or would 2.0 be sufficient.

**Comment by mattcieslak** [comment]
I'd suggest trying both on a single subject and seeing how some important fascicles look. I don't believe there is a consensus on a minimum/optimal resolution for connectomic analysis

**Comment by lizannea** [comment]
Thank you for your suggestions! After increasing the requested memory to 24GB per cpu, patch2self did not cause any problems. 

Lizanne
