### ISSUE TITLE
[BUG] SHORELine not passing transforms in a flat list

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/qsiprep#515]
When using DRBUDDI for SDC, the transforms are not being sent to the rotation calculator in a flat list. This results in a file not found error. Thanks to @nseider @mb3152 for reporting

**Comment by mattcieslak** [comment]
@nseider could you try running using the current master branch? It worked for me but I'm not going to close this until it works for you too

**Comment by nseider** [comment]
Yes of course, testing now. I will report back if we have any issues.

**Comment by mb3152** [comment]
Thanks Matt! We are still getting stuck here: 
	 [Node] Setting-up "_uncorrect_model_images81" in "/scratch/qsiprep_wf/single_subject_V1MS_wf/dwi_preproc_ses_custom_wf/hmc_sdc_wf/uncorrect_model_images/mapflow/_uncorrect_model_images81".
230218-00:40:38,569 nipype.workflow INFO:
	 [Node] Cached "_uncorrect_model_images81" - collecting precomputed outputs
230218-00:40:38,569 nipype.workflow INFO:
	 [Node] "_uncorrect_model_images81" found cached.

**Comment by mattcieslak** [comment]
I don't see any error messages here. Are you reusing the same working directory from the previous run? Is it possible you have run out of disk space?

**Comment by mb3152** [comment]
Yeah, it just stalls out there and goes really slowly, that is after 24 hours. Tons of disk space left, and we have been using fresh directories each time. Let me re-run it on my user (this was Nicole's run) in a totally new directory in my home directory. Also going to not mount any tmpdir.

**Comment by mb3152** [comment]
SUCCESS. 

Looks like I forgot to remind Nicole to remove her local python version mount of qsiprep that she had been using to try out the single shell stuff. Thanks for fixing this Matt!!
