### ISSUE TITLE
running qsiprep for a specific session

### ISSUE THREAD

**Issue by gcetin99** [PennLINC/qsiprep#535]
Hi there,
I am trying to do a qsiprep analysis for one specific session for a participant instead of all the sessions. Is there a way to do this? 
PS: I'm running a docker wrapped command

**Comment by mattcieslak** [comment]
When we do this, we will typically copy just the data for that session into a new "bids" directory and run QSIPrep on that. This will also speed up the BIDS indexing if you have lots of subjects/sessions in your data.

You can also use a BIDS filter file as [described here](https://qsiprep.readthedocs.io/en/latest/usage.html#options-for-filtering-bids-queries)

**Comment by cookpa** [comment]
More on the BIDS filters

https://qsiprep.readthedocs.io/en/latest/preprocessing.html#using-bids-filters
