### ISSUE TITLE
add qsirecon --recon-only option to documentation

### ISSUE THREAD

**Issue by mckenziephagen** [PennLINC/qsiprep#538]
The flag `--recon-only` should be included in the reconstruction.rst documentation. I'm not sure where in that file would be the best place, but if someone wants to point to a good place to include it, I can take a stab and put in a PR.

**Comment by mattcieslak** [comment]
Thanks for opening an issue on this! The documentation is in `docs/reconstruction.rst`, a PR would be greatly appreciated.  Please also add yourself to `.zenodo.json`

**Comment by pierre-nedelec** [comment]
that should be fixed with #628
