### ISSUE TITLE
reconstruction failing

### ISSUE THREAD

**Issue by dkp** [PennLINC/qsiprep#545]
# Problem

I am encountering a very similar issue to the one reported here with the qsiprep reconstruction step. I've had some success and some failure with the same data and what appears to me to be the same environment: (same container, same OS, apptainer in both cases).

**Jan 2, 2023**:  It succeeded and produced the HTML report which claimed success. See attached slurm-qsirecon-success.out.txt

**April 8, 2023**: The output in the dwi directory is produced (all the same 40 files are included as in January), but the HTML report is **not** produced and qsiprep reconstruction claims to have failed. See attached slurm-qsirecon-fail.out.txt

There are differences reported by **diff** in some of the files, I looked at one and it was a slight calculation difference, so I'm going to assume this is due to the probabilistic nature of the processing.

# Environment

**Version**: qsiprep 0.16.1
**OS**: HPC  CentOS Linux release 7.9.2009 (Core)
**apptainer version**: 1.1.5-1.el7

# Input data:

**Validated BIDS directory**: CAM003 with session. Available here: [https://osf.io/m2dz7](https://osf.io/m2dz7)

This is a 3-shell acquisition on a Siemens Skyra. A reverse-phase-encode image is provided. IntendedFor is specified.

# COMMANDS

## QSIPREP

This qsiprep command works flawlessly every time

```bash
singularity run --cleanenv --bind ${MRIS}/data:/data:ro \
--bind ${MRIS}/derivatives:/out \
--bind ${MRIS}/qsi_work:/work \
${SIF}/qsiprep.sif /data /out participant \
--participant_label ${Subject} \
--fs-license-file ${HOME}/license.txt \
--stop-on-first-crash \
--output-resolution 1.3 -w /work --n_cpus 16 -v -v
```

## QSIPREP RECONSTRUCTION

It has succeeded and failed on separate runs, causing me confusion!

```bash
# Use --cleanenv to prevent problems with singularity grabbing variables, libraries etc.
# from your HPC directories. You want the environment to be defined
# by what is inside the container.
# We specify the name of the singularity container to run.
# We need to bind three directories:
# 1) the derivatives created by qsiprep
# 2) the main derivatives directory
# 3) the work directory
# The recon-input is the output of qsiprep
# The recon spec can vary, there are a dozen or so canned options described on the read-the-docs site
# Output resolution is 1.3 as per suggestions
# If you ran freesurfer when you did fmriprep, then you can now specify those freesurfer results to be used with qsirecon

singularity run --cleanenv --bind ${MRIS}/data:/data:ro \
--bind ${MRIS}/derivatives/qsiprep:/qsiprep-output:ro \
--bind ${MRIS}/derivatives:/out \
--bind ${MRIS}/qsi_work:/work \
${SIF}/qsiprep.sif /data /out participant \
--participant_label ${Subject} \
--recon-input /qsiprep-output \
--recon-spec mrtrix_multishell_msmt_noACT \
--output-resolution 1.3 -w /work -v -v \
--fs-license-file ${HOME}/license.txt \
--freesurfer_input /out/sourcedata/freesurfer
```

# Output

- The dwi directory contains all 40 output files in both the success and failure cases. 
- Some files do differ, but I assume this is because of the probabilistic nature of the processing
- Both directories are ~14 GB
- The failure does not generate the HTML report.
- I have attached both SLURM logs

Any help or suggestions would be appreciated.

Thank you for your time,

Dianne Patterson, Ph.D.

[slurm-qsirecon-fail.out.txt](https://github.com/PennLINC/qsiprep/files/11186287/slurm-qsirecon-fail.out.txt)
[slurm-qsirecon-success.out.txt](https://github.com/PennLINC/qsiprep/files/11186288/slurm-qsirecon-success.out.txt)

[[slurm-qsirecon-fail.out.txt|attachment](upload://laFbFhK3leggkByPC13Vg1v2Lte.txt)](upload://laFbFhK3leggkByPC13Vg1v2Lte.txt) (476.4 KB)
[[slurm-qsirecon-success.out.txt|attachment](upload://cJO5Z71Xp65BzxdY0VqrUnxgk26.txt)](upload://cJO5Z71Xp65BzxdY0VqrUnxgk26.txt) (224.6 KB)

**Comment by mattcieslak** [comment]
Hi @dkp, thanks for such a thorough write up (and data!) of the issue. A couple ideas here. 

First, is there a reason you're not using the `--recon-only` flag when you're running reconstruction? I looks like the preprocessing part isn't actually being skipped in your recon run, but is finishing quickly because it's finding the previous run cached. 

The actual error here

```
	Current thread 0x00002ad6750d72c0 (most recent call first):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/fury/window.py", line 760 in record
	  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/recon_plot.py", line 181 in plot_peak_slice
	  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/recon_plot.py", line 201 in peak_slice_series
	  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/recon_plot.py", line 115 in recon_plot
	  File "/usr/local/miniconda/bin/recon_plot", line 8 in <module>
	Segmentation fault (core dumped)

```
suggests that there is a problem with creating the images for the html report. These have been problematic and tough to debug on some systems so we added the `--skip-odf-reports` option to prevent them from being created. But these are very useful to look at, so I think it's worth trying to figure out what's going on.

Are the successful and unsuccessful jobs being sent to compute hosts that may have different libraries available on them? Here since it's Fury, it's possible that there are some x11 or opengl libraries involved. 

Are you able to successfully run some of these with 1 cpu and a lot of available memory? Another possibility is that you're running out of memory if generating this report while other processes are also using lots of memory. I typically run this recon workflow with `--n-cpus 8 --omp-nthreads 7` with at least 32GB memory available.

**Comment by dkp** [comment]
The revisions ran!  I’m betting the --skip-odf-reports was crucial! Thanks so much!
(the other improvements have also been incorporated)

singularity run --cleanenv --bind ${MRIS}/data:/data:ro \
--bind ${MRIS}/derivatives2/qsiprep:/qsiprep-output:ro \
--bind ${MRIS}/derivatives2:/out  \
--bind ${MRIS}/qsi_work3:/work \
${SIF}/qsiprep.sif /data /out participant \
--participant_label ${Subject} \
--recon-input /qsiprep-output \
--recon-spec mrtrix_multishell_msmt_ACT-hsvs \
--stop-on-first-crash \
--output-resolution 1.3 -w /work -v -v  \
--n-cpus 16 --omp-nthreads 15 \
--skip-odf-reports --recon-only \
--fs-license-file ${HOME}/license.txt \
--freesurfer_input /out/fmriprep2301/sourcedata/freesurfer 

-Dianne
