### ISSUE TITLE
Schaefer atlas changes in 0.16.1

### ISSUE THREAD

**Issue by cookpa** [PennLINC/qsiprep#552]
Hi Matt,

The Schaefer 400 parcellation is noted to change in #428.

Comparing 0.16.1 output to 0.14.2 using the dsi_studio_qqi recon workflow, I'm seeing that the network measures are only computed once per parcel resolution, so I get schaefer400 rather than schaefer400x7 and schaefer400x17. 

I believe the new schaefer400 LUT (desc-schaefer400x7_origLUT.txt) corresponds to the schaefer400x7 parcel names (plus subcortical labels).

I can see that it makes sense to not do both 7 and 17 networks in the dsi_studio_qqi workflow, since the results would be the same.

Is there anything else that changed?

Thanks

**Comment by mattcieslak** [comment]
Hi Phil, the addition of the subcortical regions was the main update with the schaefer atlases also being limited to the 7-network ordering. Do you need a lookup table to reordering the matrices into the 17 network ordering?

**Comment by cookpa** [comment]
A lookup table would be great, yes!

**Comment by cookpa** [comment]
Awesome, this looks incredibly useful. Good to see convergence between different modality preps.
