### ISSUE TITLE
About distortion_group_merge

### ISSUE THREAD

**Issue by Moyejiang** [PennLINC/qsiprep#554]
Thanks for making qsiprep! I have a double-shell dwi dataset and each shell acquired in 2 opposite phase-encoding directions. The preprocessing for some of my subjects did not execute cleanly and I got an error message (please see below).

docker run --rm -it -v /home/moye/software/licenses/license.txt:/opt/freesurfer/license.txt:ro -v /media/moye/Data/test/data_bids:/data:ro -v /media/moye/Data/test/eddy_params.json:/sngl/eddy/eddy_config.json:ro -v /media/moye/Data/test/data_output/output1:/out pennbbl/qsiprep:0.17.0 /data /out participant --eddy-config /sngl/eddy/eddy_config.json --skip_bids_validation --output_space T1w --output_resolution 3 --nthreads 4  --distortion-group-merge concat

230422-09:16:34,454 nipype.workflow INFO:
	 Running with omp_nthreads=3, nthreads=4
230422-09:16:34,454 nipype.workflow IMPORTANT:
	 
    Running qsiprep version 0.17.0:
      * BIDS dataset path: /data.
      * Participant list: ['1009'].
      * Run identifier: 20230422-091633_a12b7035-cd27-416b-822a-777be0ded84b.
    
230422-09:16:36,562 nipype.workflow INFO:
	 Combining all 4 dwis within the single available session
230422-09:16:36,591 nipype.workflow INFO:
	 [{'dwi_series': ['/data/sub-1009/dwi/sub-1009_acq-dir107PA_dwi.nii.gz', '/data/sub-1009/dwi/sub-1009_acq-dir99PA_dwi.nii.gz'], 'dwi_series_pedir': 'j', 'fieldmap_info': {'suffix': 'rpe_series', 'rpe_series': ['/data/sub-1009/dwi/sub-1009_acq-dir107AP_dwi.nii.gz', '/data/sub-1009/dwi/sub-1009_acq-dir99AP_dwi.nii.gz']}, 'concatenated_bids_name': 'sub-1009'}]
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 950, in build_qsiprep_workflow
    retval['workflow'] = init_qsiprep_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/base.py", line 241, in init_qsiprep_wf
    single_subject_wf = init_single_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/base.py", line 650, in init_single_subject_wf
    merging_group_workflows[merged_group] = init_distortion_group_merge_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/dwi/distortion_group_merge.py", line 136, in init_distortion_group_merge_wf
    b0_ref_wf = init_dwi_reference_wf(name='merged_b0_ref', register_t1=False,
TypeError: init_dwi_reference_wf() missing 1 required positional argument: 'omp_nthreads'

I think that distortion_group_merge.py don't  received ‘omp_nthreads’。
My file structure is as follows:
├── sub-1009_acq-dir107AP_dwi.bval
├── sub-1009_acq-dir107AP_dwi.bvec
├── sub-1009_acq-dir107AP_dwi.json
├── sub-1009_acq-dir107AP_dwi.nii.gz
├── sub-1009_acq-dir107AP_sbref.json
├── sub-1009_acq-dir107AP_sbref.nii.gz
├── sub-1009_acq-dir107PA_dwi.bval
├── sub-1009_acq-dir107PA_dwi.bvec
├── sub-1009_acq-dir107PA_dwi.json
├── sub-1009_acq-dir107PA_dwi.nii.gz
├── sub-1009_acq-dir107PA_sbref.json
├── sub-1009_acq-dir107PA_sbref.nii.gz
├── sub-1009_acq-dir99AP_dwi.bval
├── sub-1009_acq-dir99AP_dwi.bvec
├── sub-1009_acq-dir99AP_dwi.json
├── sub-1009_acq-dir99AP_dwi.nii.gz
├── sub-1009_acq-dir99AP_sbref.json
├── sub-1009_acq-dir99AP_sbref.nii.gz
├── sub-1009_acq-dir99PA_dwi.bval
├── sub-1009_acq-dir99PA_dwi.bvec
├── sub-1009_acq-dir99PA_dwi.json
├── sub-1009_acq-dir99PA_dwi.nii.gz
├── sub-1009_acq-dir99PA_sbref.json
└── sub-1009_acq-dir99PA_sbref.nii.gz
I want to end up with just one dwi file with a size of dir-206。

**Comment by smeisler** [comment]
Should be fixed by the above PR included in the next release. Closing this issue, but please reopen if the error persists in the next release!
