### ISSUE TITLE
[BUG] Local gradient rotation workflow

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/qsiprep#56]
Looks like an unset input/output path
```
local_grad_rotation: TypeError: stat: path should be string, bytes, os.PathLike or integer, not _Undefined

TypeError: stat: path should be string, bytes, os.PathLike or integer, not _Undefined
```

**Comment by RobertJirsaraie** [comment]
I just ran into this bug too. I am going to remove `--write_local_bvecs` from my call as a temporary solution. Thank you for the awesome pipeline @mattcieslak!

**Comment by eds-slim** [comment]
Issue seems to be persisting with verison 0.9.0beta1. Will also deactivate the `--write_local_bvecs` flag.
