### ISSUE TITLE
qsirecon with pyAFQ doesn't generate the expected outputs with latest qsiprep Docker Image

### ISSUE THREAD

**Issue by earoy** [PennLINC/qsiprep#566]
Hi! I'm running both qsiprep and pyAFQ through the qsiprep recon workflow and ran into some issues with the latest Docker/Singularity image. When I run qsirecon using the Singularity image built from `pennbbl/qsiprep:latest`, I get some of the expected output (tract_profiles.csv and whole-brain .trk files) but it does not generate expected `bundles`, `clean_bundles`, and `ROIs` directories. 

However, when I run qsirecon using the image built from `pennbbl/qsiprep:unstable`, all the expected output and directories are generated. I'm not sure if this is something that has been changed between the latest and unstable versions but just wanted to check to see if this is expected with the `pennbbl/qsiprep:latest` image. Thanks!

**Comment by mattcieslak** [comment]
I think there have been some relevant bugfixes that haven't been included in a release yet. If you use unstable just be sure to check your results closely

**Comment by arokem** [comment]
Did this make it to the recent release? Apparently some people are still seeing this with the 0.18 tag: https://neurostars.org/t/qsiprep-and-pyafq-to-generate-individual-tracts-and-visualizations/26172/6 (also of note, the html visualizations don't seem to show up). 

Cross-ref with https://github.com/yeatmanlab/pyAFQ/issues/963

**Comment by 36000** [comment]
This fix would have been in the 0.18.0 release. It looks like Steven Meisler got it to work. Are we sure this is using the 0.18 tag? I will try it locally to see if I can reproduce the error.

**Comment by arokem** [comment]
OK - looks like maybe this is more subtle, where it works when you run prep+recon together, but maybe not when you run recon on its own (see most recent comment in the above-linked neurostars thread).
