### ISSUE TITLE
SDC issue

### ISSUE THREAD

**Issue by mrribbits** [PennLINC/qsiprep#568]
Hi !

This is my first shot at using QSIPrep, and it seems the SDC is stretching out my image a humorous amount. Not sure why.  Here's what I have:

- In the dwi folder: a volume with 101 b>0 and 10 b=0 collected in AP dir (j-)
- In the fmap folder: a volume with 4 b=0 collected in PA dir (j)
- The intended for line is in there correctly, QSIPrep finds the file in the fmap folder and runs the SDC.
- And attached is an image of the output. wah wah wah.

Thanks ahead!
Mark

Here's my command:
```
/usr/local/miniconda/bin/qsiprep \
/data /out participant \
--fs-license-file /opt/freesurfer/license.txt \
--work_dir /work \
--output-resolution 2.4 \
--separate-all-dwis \
--skip_bids_validation \
--participant_label 99T \
--hmc_model 3dSHORE \
--dwi-only \
--stop-on-first-crash \
--bids-filter-file /data/sub-99T/ses-01/dwi/dsi-bids-filter.json \
--verbose
```

![Screenshot 2023-05-08 at 11 46 08 PM](https://user-images.githubusercontent.com/6782903/236988895-6cf7a2b4-3d1b-44cb-8ee1-083a28841e1e.png)

**Comment by mattcieslak** [comment]
wow, this is definitely not how it's supposed to look. A couple questions: 

Are you sure the images are actually j and j-? If you load the fieldmap image and the dwi series with the b=0's can you tell that they have opposite distortion?

Why use 3dSHORE instead of eddy? Do you have a non-shelled acquisition?

Have you tried using `--pepolar-method DRBUDDI`?

**Comment by mrribbits** [comment]
Hi Matt!   Yes they are indeed j and j- confirmed visually.  It's a grid acquisition so no eddy for me. 

I have not tried DRBUDDI.  The usage for 0.16.1 doesn't list that option.  Should I install a different build?

**Comment by mattcieslak** [comment]
Could you try out the unstable tag? There are some drbuddi updates in there that may help

**Comment by mrribbits** [comment]
Okay that did indeed help!  Looks as it should now.  thx!
