### ISSUE TITLE
--b0-to-t1w-transform   Is it working as expected?

### ISSUE THREAD

**Issue by mrribbits** [PennLINC/qsiprep#574]
Hi, I ran one subject twice, trying:
```
--b0-to-t1w-transform Affine
```
versus
```
--b0-to-t1w-transform Rigid
```
to see which would align better to the T1w.  

However the outputs are identical. So I'm not sure if this option is working as intended. I expected there'd be some tiny differences, but they are _exactly_ the same.

Thanks!

```
qsiprep version: 0.17.0+133.g92c706c
qsiprep command: /usr/local/miniconda/bin/qsiprep /data /out participant --fs-license-file /opt/freesurfer/license.txt --work_dir /work --output-resolution 2.4 --separate-all-dwis --skip_bids_validation --participant_label 97T --hmc_model 3dSHORE --stop-on-first-crash --pepolar-method DRBUDDI --anat-modality T1w --anatomical-template MNI152NLin2009cAsym --unringing-method rpg --bids-filter-file /data/dsi101-bids-filter.json --longitudinal --b0-to-t1w-transform Rigid --verbose
```

**Comment by mrribbits** [comment]
Maybe not high priority I'm guessing, but still curious if anyone has noticed the same issue.  Thx!

**Comment by mattcieslak** [comment]
I just looked through the code and indeed it is always using "Rigid" no matter what is specified on the command line. There only time that an affine for coregistration might make sense is if you don't have any fieldmaps and the dwis are distorted. Even then, the types of distortion present won't be addressed adequately by an affine transform. 

If you'd like to do a bugfix, I'd be happy to merge it. You can change the instances where the `nit_b0_to_anat_registration_wf` is called and pass in the transform type

**Comment by mrribbits** [comment]
Got it. Given what you said about affine not making sense, i'll just stick with rigid then.  Thx!
