### ISSUE TITLE
What's the latest stable release?

### ISSUE THREAD

**Issue by Shade-** [PennLINC/qsiprep#577]
Hello, just wondering if 0.17.0 is stable enough to use. The releases page lists 0.16.1 as the latest stable one but there is a 0.17.0 tag. Additionally, 0.18.0alpha0 is now available as a pre-release.

I'm using 0.16.1 without any major issue so I'm just wondering if I can upgrade to 0.17.0 safely or if I should wait until 0.18.0 is released.

I'm particularly interested in the SynthStrip enhancement.

Thanks.

**Comment by mattcieslak** [comment]
Are you working with infants or seniors? If not then 0.16.1 is going to be the most well-tested release for preprocessing.

**Comment by marcelzwiers** [comment]
This is also unclear to me, I see for instance that `v0.18.0alpha0` has been released as the latest release, but if I look at the tagged versions (https://github.com/PennLINC/qsiprep/tags) I see a newer `v0.18` version that is not (yet?) released?

**Comment by mattcieslak** [comment]
I need to figure out how to automate the GitHub releases so they stay synced with DockerHub and PyPI. I just updated GitHub so it includes 0.18.0.

**Comment by Shade-** [comment]
Thanks for your reply. I have been using 0.18 on 5-6 subjects without any issue and with an improved T1 skull stripping, at least visually.
