### ISSUE TITLE
qsiprep report v0.17 vs 0.18 difference

### ISSUE THREAD

**Issue by dkp** [PennLINC/qsiprep#589]
In v 0.17 the *desc-resampled_b0ref.svg clear has red and blue (and maybe cyan) lines. In the v0.18.0 image I can make out the blue lines (barely) but don't see the red.  Copies of both images are attached (this is the same subject, only the qsiprep version has changed):
![v18_sub-CAM003_ses-01brain_dir-AP_desc-resampled_b0ref](https://github.com/PennLINC/qsiprep/assets/965184/4175a3c6-1454-43d7-9bde-5f7fc28df3f9)
![v17_sub-CAM003_ses-01brain_dir-AP_desc-resampled_b0ref](https://github.com/PennLINC/qsiprep/assets/965184/f8158699-45a3-4070-a9ad-30411cfd984d)

**Comment by mattcieslak** [comment]
There are fewer colors in the newest version because there is only one mask being generated by synthstrip. The line could definitely be bigger though

**Comment by dkp** [comment]
Thank you, that is helpful! --thicker lines would be nice for those of us who are getting older ; )
