### ISSUE TITLE
problem with node Eddy

### ISSUE THREAD

**Issue by snaillyd** [PennLINC/qsiprep#590]
Hi there,
I was trying out qsiprep v0.16.1(that is incorprate into DPABIFiber) on a multiband dRMI dataset, and I encountered error when it tries to run eddy_openmp， the followings are the content of the crash file:

Node: qsiprep_wf.single_subject_sub001_wf.dwi_preproc_wf.hmc_sdc_wf.eddy
Working directory: /data/qsiprepwork/sub-sub001/qsiprep_wf/single_subject_sub001_wf/dwi_preproc_wf/hmc_sdc_wf/eddy

Node inputs:

args = 
cnr_maps = True
dont_peas = False
dont_sep_offs_move = False
environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ', 'OMP_NUM_THREADS': '1'}
estimate_move_by_susceptibility = <undefined>
fep = False
field = <undefined>
field_mat = <undefined>
flm = linear
fudge_factor = 10.0
fwhm = <undefined>
in_acqp = <undefined>
in_bval = <undefined>
in_bvec = <undefined>
in_file = <undefined>
in_index = <undefined>
in_mask = <undefined>
in_topup_fieldcoef = <undefined>
in_topup_movpar = <undefined>
initrand = <undefined>
interp = spline
is_shelled = True
json = <undefined>
mbs_ksp = <undefined>
mbs_lambda = <undefined>
mbs_niter = <undefined>
method = jac
mporder = <undefined>
multiband_factor = <undefined>
multiband_offset = <undefined>
niter = 5
num_threads = 1
nvoxhp = 1000
out_base = eddy_corrected
outlier_nstd = <undefined>
outlier_nvox = <undefined>
outlier_pos = <undefined>
outlier_sqr = <undefined>
outlier_type = <undefined>
output_type = NIFTI_GZ
repol = True
residuals = False
session = <undefined>
slice2vol_interp = <undefined>
slice2vol_lambda = <undefined>
slice2vol_niter = <undefined>
slice_order = <undefined>
slm = linear
use_cuda = False

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node eddy.

Cmdline:
	eddy_openmp  --cnr_maps --flm=linear --ff=10.0 --acqp=/data/qsiprepwork/sub-sub001/qsiprep_wf/single_subject_sub001_wf/dwi_preproc_wf/hmc_sdc_wf/gather_inputs/eddy_acqp.txt --bvals=/data/BIDS/sub-sub001/dwi/sub-sub001_dwi.bval --bvecs=/data/BIDS/sub-sub001/dwi/sub-sub001_dwi.bvec --imain=/data/qsiprepwork/sub-sub001/qsiprep_wf/single_subject_sub001_wf/dwi_preproc_wf/pre_hmc_wf/merge_and_denoise_wf/dwi_denoise_dwi_wf/biascorr/sub-sub001_dwi_denoised_N4.nii.gz --index=/data/qsiprepwork/sub-sub001/qsiprep_wf/single_subject_sub001_wf/dwi_preproc_wf/hmc_sdc_wf/gather_inputs/eddy_index.txt --mask=/data/qsiprepwork/sub-sub001/qsiprep_wf/single_subject_sub001_wf/dwi_preproc_wf/hmc_sdc_wf/pre_eddy_b0_ref_wf/enhance_and_mask_b0/topup_imain_avg_mask.nii.gz --interp=spline --data_is_shelled --resamp=jac --niter=5 --nvoxhp=1000 --out=/data/qsiprepwork/sub-sub001/qsiprep_wf/single_subject_sub001_wf/dwi_preproc_wf/hmc_sdc_wf/eddy/eddy_corrected --repol --slm=linear
Stdout:
	EDDY:::  AcqPara::AcqPara: Unrealistic read-out time
	EDDY:::  EddyHelperClasses.cpp:::  EDDY::AcqPara::AcqPara(const ColumnVector&, double):  Exception thrown
	EDDY::: Eddy failed with message EDDY:::  ECScanClasses.cpp:::  EDDY::ECScanManager::ECScanManager(const string&, const string&, const string&, const string&, const string&, const string&, const string&, const string&, EDDY::ECModel, EDDY::ECModel, const std::vector<unsigned int>&, const EDDY::PolationPara&, EDDY::MultiBandGroups, bool):  Exception thrown
Stderr:

Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
	    setattr(outputs, key, val)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
	    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
	    self.error(objekt, name, str(value))
	  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
	    raise TraitError(
	traits.trait_errors.TraitError: The 'out_corrected' trait of an ExtendedEddyOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/data/qsiprepwork/sub-sub001/qsiprep_wf/single_subject_sub001_wf/dwi_preproc_wf/hmc_sdc_wf/eddy/eddy_corrected.nii.gz' <class 'str'> was specified.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 401, in run
	    outputs = self.aggregate_outputs(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
	    raise FileNotFoundError(msg)
	FileNotFoundError: No such file or directory '/data/qsiprepwork/sub-sub001/qsiprep_wf/single_subject_sub001_wf/dwi_preproc_wf/hmc_sdc_wf/eddy/eddy_corrected.nii.gz' for output 'out_corrected' of a ExtendedEddy interface

Would appreciate any help on this!

Best Regards,
YD Li

**Comment by mattcieslak** [comment]
This seems to be the problem `EDDY::: AcqPara::AcqPara: Unrealistic read-out time`. What is the TotalReadoutTime in your json files?

**Comment by mattcieslak** [comment]
closing for now, please reopen if you're still having this problem
