### ISSUE TITLE
Take up too much memory when using 0.18.0 to preprocess

### ISSUE THREAD

**Issue by weiwei-wch** [PennLINC/qsiprep#598]
I used 0.18.0 to re-preprocess our data for testing, which were all preprocessed with 0.16.0. I found that in 0.18.0, a single subject will take nearly 50GiB (yes, it is GiB) memory at very early stage. I do not see this in 0.16.0, so I think there maybe someting wrong? This is the few last lines of the log when I kill the process, it seems the N4-correct eating this much memmory, which is wired.

`[Node] Finished "skulled_1mm_resample", elapsed time 1.692178s.`
`230707-10:34:45,458 nipype.workflow INFO:`
	 `[Node] Finished "raw_merge", elapsed time 2.675767s.`
`230707-10:34:46,673 nipype.workflow INFO:`
	 `[Node] Setting-up "qsiprep_wf.single_subject_BPM100_wf.anat_preproc_wf.anat_template_wf.n4_correct" in "/work/qsiprep_wf/single_subject_BPM100_wf/anat_preproc_wf/anat_template_wf/n4_correct". `
`230707-10:34:46,676 nipype.workflow INFO:`
	` [Node] Executing "n4_correct" <nipype.interfaces.ants.segmentation.N4BiasFieldCorrection>` 

and this is the command I use, the --low-mem or --mem-mb seems to be useless

`docker run --rm -u 1005:1005 -m 8g -v /home/weiw/Desktop/data/Philip_data/all_data_preprocessed:/data \`
	`-v /home/weiw/Desktop/data/Philip_data/all_data_preprocessed/qsiprep_result:/out \`
	`-v /home/weiw/Desktop/data/Philip_data/all_data_preprocessed/temp_workdir/temp_${subj}_qsiprep:/work \`
	`pennbbl/qsiprep:0.18.0 /data/BIDS /out participant --participant-label ${subj} --output-resolution 2 \`
	`--fs-license-file /data/license.txt --denoise-method patch2self \`
	`--unringing-method mrdegibbs --skip_bids_validation --low-mem \`
	`--freesurfer-input /data/fmriprep_result/sourcedata/freesurfer \`
	`--work-dir /work --hmc-model eddy --nthreads 4 > log_shell/qsiprep_${subj}_log.txt`

**Comment by mattcieslak** [comment]
Adding in synthseg and synthstrip has blown up the memory use in qsiprep. @weiwei-wch can you try adding --omp-nthreads 4?

**Comment by weiwei-wch** [comment]
the usage of memory is down, but the process will be killed if the swap limitaion reached (I guess?) when I  do parallel processing for several participants @mattcieslak . Below is the error message:
`concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.`

**Comment by weiwei-wch** [comment]
> the usage of memory is down, but the process will be killed if the swap limitaion reached (I guess?) when I do parallel processing for several participants @mattcieslak . Below is the error message: `concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.`

I guess this was caused because I use the patch2self denoise method, when I switch to the default mrtrix dtidenoise, there is not too many swap spaces used.
And the patch2self mehod can be finished when I have enough resources, so the method is good, but the problem is that it is too expensive

**Comment by mattcieslak** [comment]
patch2self will use a lot of memory if you're running in parallel. Have you run both the dwidenoise and patch2self? If so I'm curious if you have the head motion estimates from both

**Comment by mattcieslak** [comment]
I think this should be fixed, please reopen if now
