### ISSUE TITLE
qsiprep/dwiqc.json and parallel processing

### ISSUE THREAD

**Issue by cookpa** [PennLINC/qsiprep#609]
If I am running many participants in parallel, isn't there a risk of dwiqc.json getting corrupted? Is there a way to turn this off and generate it after the project processing is complete?

Thanks

**Comment by mattcieslak** [comment]
It should be ok if the group level file gets corrupted during preprocessing. In fact, I should probably remove the group level write when the analysis level argument is `participant`. Once all your individual subject processing is done you should use `qsiprep_group_report /path/to/results/qsiprep` and it will generate a correct group-level dwiqc.json file.

**Comment by cookpa** [comment]
Awesome, thanks!
