### ISSUE TITLE
Multi-subject workflows

### ISSUE THREAD

**Issue by jhlegarreta** [PennLINC/qsiprep#611]
Hi,
I was referred to `qsiprep` following a question about susceptibility correction on neurostars:
https://neurostars.org/t/epi-factor-fsl-topup-datain-parameter-values/26503

Steven specifically mentioned having a look at this page where a comparison of different preprocessing tools is made:
https://qsiprep.readthedocs.io/en/latest/comparisons.html

I am interested in being able to use `qsiprep` on a multi-subject workflow: that is, being able to run the `qsiprep` scripts in such a way that a workflow orchestration tool takes care of distributing the jobs across scripts/subjects, in a such a way that I do not have to write a loop and if a subject fails, the tool is able to resume the work automatically. Much like `nextflow` would do. I see on that table that this should be possible with `qsiprep` and `NiPyPe`. I am not sure where to look for sample workflow scripts or appropriate documentation to see how `qsiprep` can be used with `NiPyPe`. Suggestions would be welcome.

Thanks for developing and maintaining this tool.

**Comment by mattcieslak** [comment]
@jhlegarreta It seems from other issues that you've got this working? You won't have to interact with nipype directly, qsiprep will handle that for you

**Comment by jhlegarreta** [comment]
Have not tested in a multi-subject setting yet. If there is some documentation, I'd be interested in reading about it.

**Comment by mattcieslak** [comment]
the default is to run all the subjects in the BIDS directory. This will be handled using nipype, just like in the single subject tests you've run so far
