### ISSUE TITLE
Qsirecon longitudinal data with a single anatomical reference

### ISSUE THREAD

**Issue by mayayab** [PennLINC/qsiprep#618]
Running qsiprep+qsirecon (v18) on longitudinal data creates qsiprep derivatives for all sessions, but qsirecon derivatives only for ses-1. Workaround was to run qsiprep+qsirecon again using bids-filter-file on single sessions (ses-2, ses-3... ), but this crashed since the anatomical data were acquired only for the first scan session (ses-1). Would it be possible to add a functionality to run qsirecon on subsequent sessions and point to the anatomical data?

**Comment by smeisler** [comment]
Closing as I think this was fixed in 0.19.1, but reopen if this is still an issue!
