### ISSUE TITLE
nvidia/gpu issues with v0.19.0

### ISSUE THREAD

**Issue by pierre-nedelec** [PennLINC/qsiprep#623]
The 0.19.0 container doesn't have the right libcublas libraries. It fails on the eddy correction for example:
```
eddy_cuda: error while loading shared libraries: libcublas.so.10: cannot open shared object file: No such file or directory
```

**Comment by mblesac** [comment]
I found the same issue. Has been any updates on this?

**Comment by jhauneuro** [comment]
I experienced the same issue. I'm using v0.19.1 (docker container).

**Comment by julfou81** [comment]
Same here. I reverted to v0.18.1 for the preprocessing stage with qsiprep calling `eddy_cuda` (with singularity). I keep v0.19.0 for reconstruction where this issue is not present (I guess no GPU is called for the reconstruction workflow I use: `mrtrix_multishell_msmt_pyafq_tractometry`

**Comment by mattcieslak** [comment]
I'm working on this now. My current thought is to copy over the cuda libraries from 0.18.1 since the official nvidia image with this old cuda version is no longer available. wdyt?

**Comment by mattcieslak** [comment]
There would have been license issues with just copying libraries from 0.18.1, but I got the cuda libraries installed from deb packages. This worked through Docker with my gpu. Please try out 0.20 and open a new issue if there are still problems!
