### ISSUE TITLE
Question about reconstruction table on website

### ISSUE THREAD

**Issue by dkp** [PennLINC/qsiprep#624]
In the table on https://qsiprep.readthedocs.io/en/latest/reconstruction.html 
row 1 and row 6 refer to the same mrtrix_multishell_msmt_ACT-fast* 
however, each contains different values for the multishell and DTI columns.

I'm not sure what to make of this, is it a typo?

Also, I'm wondering how to interpret these columns.  For example, if a reconstruction says Multishell "Yes", does that mean it is compatible with multishell or that it requires multishell?   Thanks for any clarifications.

-Dianne

**Comment by dkp** [comment]
Thank you for the fix!  "Req" really helps! and now the double-entry for mrtrix_multishell_msmt_ACT-fast* at least has the same values.

**Comment by mattcieslak** [comment]
Hi Dianne,
The multishell msmt workflows require more than 1 shell, whereas the singleshell ss3t workflows do not - this is definitely a typo! In this table "yes" means "compatible"

**Comment by dkp** [comment]
thank you!
