### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by jhlegarreta** [PennLINC/qsiprep#625]
The installation instructions in https://qsiprep.readthedocs.io/en/latest/installation.html#id1 are somewhat unclear concerning how to install qsiprep from PyPI, as a package named `qsiprep` exists:
https://pypi.org/project/qsiprep/

but the instructions point to `qsiprep-container`:
https://pypi.org/project/qsiprep-container/

A few thoughts:
- Are there some additional instructions concerning the installation/use of `qsiprep` using `PyPI`, like the additional software required to be installed manually and how things need to be configured so that things work? If yes, should they be cross-referenced when talking about installing `qsiprep` using `PyPI`? If not, can a something be proposed?
- It is unclear to me what `qsiprep-container` does. Do users using `qsiprep` using a `Docker` or `Singularity` image need to install that through `PyPI`? If yes, for what purpose? If not, can the purpose of the package be clarified?

 Happy to contribute to improve this if some additional context is given.

**Comment by jhlegarreta** [comment]
WIP: PR #626. Suggestions and comments are appreciated.

**Comment by smeisler** [comment]
Hi @jhlegarreta,

In general, installing qsiprep from pip is not recommended, compared to containerized applications. Pip should install all dependencies for you with `pip install qsiprep,` but still not recommended. Qsiprep-container is a command that creates a wrapper function around qsiprep. It is just an easier way to invoke qsiprep in containers, but not necessary.

Also, general questions (e.g., not bug issues) should go to neurostars.com, with the qsiprep tag.

Best,
Steven

**Comment by jhlegarreta** [comment]
Thanks @smeisler. OK, I am taking a note about asking questions on neurostars (have not found any mention to this in the documentation; can do a PR to make this clear in the documentation if you want).

Can you then please comment on the mentioned PR how this should be put as the way it currently stands is misleading? Thanks.
