### ISSUE TITLE
Move qsiprep's docker url to pennlinc?

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/qsiprep#627]

**Comment by mattcieslak** [comment]
definitely! I have put in the wrong docker address numerous times since we moved qsirecon to pennlinc

**Comment by tsalo** [comment]
I'm not sure that was ready to close. I just opened #869, but I'm betting it will fail because qsiprep_build is on pennbbl.

**Comment by mattcieslak** [comment]
wrong button :facepalm:
