### ISSUE TITLE
How to get qsiprep to detect fieldmaps?

### ISSUE THREAD

**Issue by suneelbanerjee** [PennLINC/qsiprep#644]
Hi Matt,

Hope you're doing well. Thanks for developing and maintaining this super helpful toolbox. 

I am hoping to use qsiprep to preprocess a small dataset, and have been having some trouble with the susceptibility distortion correction step. I don't think qsiprep is detecting my fieldmaps.

Snippet from the log:
```
230925-12:24:29,160 nipype.workflow INFO:
	 [{'dwi_series': ['/derivatives/nii/sub-PR05/ses-brainlabMRI/dwi/sub-PR05_ses-brainlabMRI_dir-AP_dwi.nii.gz'],
	 	'fieldmap_info': {'suffix': None},
	 	'dwi_series_pedir': 'j',
		'concatenated_bids_name': 'sub-PR05_ses-brainlabMRI_dir-AP'}]
```

Here is my directory structure:

```
|-- nii
  |-- dataset_description.json
  |-- sub-PR05
    |-- ses-brainlabMRI
      |-- dwi
        |-- sub-PR05_ses-brainlabMRI_dir-AP_dwi.bval
        |-- sub-PR05_ses-brainlabMRI_dir-AP_dwi.bvec
        |-- sub-PR05_ses-brainlabMRI_dir-AP_dwi.json
        |-- sub-PR05_ses-brainlabMRI_dir-AP_dwi.nii.gz
      |-- fmap
        |-- sub-PR05_ses-brainlabMRI_dir-PA_dwi.bvec
        |-- sub-PR05_ses-brainlabMRI_dir-PA_dwi.bval
        |-- sub-PR05_ses-brainlabMRI_dir-PA_dwi.nii.gz
        |-- sub-PR05_ses-brainlabMRI_dir-PA_dwi.json
      |-- anat
        |-- sub-PR05_ses-brainlabMRI_acq-T13DAXT1BRAVO_T1w.json
        |-- sub-PR05_ses-brainlabMRI_acq-T13DAXT1BRAVO_T1w.nii.gz
    |-- ses-preopMRI
      |-- anat
        |-- sub-PR05_ses-preopMRI_acq-T1BrainAx3DT1GRE_T1w.json
        |-- sub-PR05_ses-preopMRI_acq-T1BrainAx3DT1GRE_T1w.nii.gz
  |-- sub-PR03
    |-- ses-brainlabMRI
      |-- dwi
        |-- sub-PR03_ses-brainlabMRI_dir-AP_dwi.bval
        |-- sub-PR03_ses-brainlabMRI_dir-AP_dwi.nii.gz
        |-- sub-PR03_ses-brainlabMRI_dir-AP_dwi.bvec
        |-- sub-PR03_ses-brainlabMRI_dir-AP_dwi.json
      |-- fmap
        |-- sub-PR03_ses-brainlabMRI_dir-PA_dwi.bvec
        |-- sub-PR03_ses-brainlabMRI_dir-PA_dwi.bval
        |-- sub-PR03_ses-brainlabMRI_dir-PA_dwi.nii.gz
        |-- sub-PR03_ses-brainlabMRI_dir-PA_dwi.json
      |-- anat
        |-- sub-PR03_ses-brainlabMRI_acq-T13DAXT1BRAVO_T1w.json
        |-- sub-PR03_ses-brainlabMRI_acq-T13DAXT1BRAVO_T1w.nii.gz
  |-- sub-PR04
    |-- ses-brainlabMRI
      |-- dwi
        |-- sub-PR04_ses-brainlabMRI_dir-AP_dwi.json
        |-- sub-PR04_ses-brainlabMRI_dir-AP_dwi.bval
        |-- sub-PR04_ses-brainlabMRI_dir-AP_dwi.nii.gz
        |-- sub-PR04_ses-brainlabMRI_dir-AP_dwi.bvec
      |-- fmap
        |-- sub-PR04_ses-brainlabMRI_dir-PA_dwi.nii.gz
        |-- sub-PR04_ses-brainlabMRI_dir-PA_dwi.json
        |-- sub-PR04_ses-brainlabMRI_dir-PA_dwi.bval
        |-- sub-PR04_ses-brainlabMRI_dir-PA_dwi.bvec
      |-- anat
        |-- sub-PR04_ses-brainlabMRI_acq-T13DAXT1BRAVO_T1w.nii.gz
        |-- sub-PR04_ses-brainlabMRI_acq-T13DAXT1BRAVO_T1w.json
```

I've also made sure to include the 'IntendedFor' field inside the JSON sidecar files of the fieldmaps. 
``` json
"IntendedFor": "PR_BIDS/derivatives/nii/sub-PR05/ses-brainlabMRI/dwi/sub-PR05_ses-brainlabMRI_dir-AP_dwi.nii.gz"

```

What is the correct way to make sure that qsiprep reads the fieldmaps?

Any advice would be greatly appreciated. Please let me know if I should provide more information. Thanks in advance!

**Comment by suneelbanerjee** [comment]
I also came across this issue:

1) [https://github.com/PennLINC/qsiprep/issues/373](https://github.com/PennLINC/qsiprep/issues/373)
I don't think my directory structure is different from Alicja's, who also had fieldmaps.

**Comment by mattcieslak** [comment]
I think I know the answer here: could you make the path in IntendedFor [relative to the subject directory](https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.metadata.IntendedFor) in your BIDS?

**Comment by pcamach2** [comment]
What acquisition was used for the fieldmaps? Based on the names of the files in the fmap directories and the presence of bvec and bval files, these look like reverse phase-encoding direction DWI acquisitions, not any of the recognized [BIDS fieldmap types](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#types-of-fieldmaps) (e.g. file names ending with '_phasediff', '_magnitude', '_epi', 'etc.)

**Comment by mattcieslak** [comment]
good catch @pcamach2. @suneelbanerjee is the dwi currently in your fmaps directory a complete series (ie has enough b>0 images to use for modeling)? If so you can move it into the dwi directory and the it will be used for distortion correction

**Comment by pierre-nedelec** [comment]
Hi @pcamach2 and @mattcieslak ! thank you for your help. We have 2 b0s and 6 volumes at b3000.

**Comment by mattcieslak** [comment]
ah! That's an epi fieldmap. you can rename it to _epi.nii.gz and keep the dwi in your intendedfor.

optionally you can keep the bval and bvec in your fmaps directory and add a line in your bidsignore so **/fmaps/*.bval **/fmaps/*bvec are ignored when doing bids validation.

It should look like:

```
|-- nii
  |-- dataset_description.json
  |-- .bidsignore
  |-- sub-PR05
    |-- ses-brainlabMRI
      |-- dwi
        |-- sub-PR05_ses-brainlabMRI_dir-AP_dwi.bval
        |-- sub-PR05_ses-brainlabMRI_dir-AP_dwi.bvec
        |-- sub-PR05_ses-brainlabMRI_dir-AP_dwi.json
        |-- sub-PR05_ses-brainlabMRI_dir-AP_dwi.nii.gz
      |-- fmap
        |-- sub-PR05_ses-brainlabMRI_dir-PA_epi.bvec
        |-- sub-PR05_ses-brainlabMRI_dir-PA_epi.bval
        |-- sub-PR05_ses-brainlabMRI_dir-PA_epi.nii.gz
        |-- sub-PR05_ses-brainlabMRI_dir-PA_epi.json
      |-- anat
        |-- sub-PR05_ses-brainlabMRI_acq-T13DAXT1BRAVO_T1w.json
        |-- sub-PR05_ses-brainlabMRI_acq-T13DAXT1BRAVO_T1w.nii.gz

```

**Comment by suneelbanerjee** [comment]
@mattcieslak @pcamach2 Thanks so much for your help!

**Comment by suneelbanerjee** [comment]
Hey guys, 

Can qsiprep use reverse-phase encoded DWI scans that only contain 8 b=0 volumes as fieldmaps for SDC? If so, I'm bumping into a new issue where qsiprep can't find the file in the ```IntendedFor``` field in the fieldmap's json.


```
	[31m2: [ERR] 'IntendedFor' field needs to point to an existing file. (code: 37 - INTENDED_FOR)[39m
		./sub-PR05/ses-brainlabMRI/fmap/sub-PR05_ses-brainlabMRI_dir-PA_epi.nii.gz
			Evidence: sub-PR05/ses-brainlabMRI/dwi/sub-PR05_ses-brainlabMRI_dir-AP_dwi.nii.gz
```

(I have tried using both the absolute file path as well as the path relative to the subject directory, as you suggested earlier @mattcieslak). 

Thanks again!

**Comment by pcamach2** [comment]
@suneelbanerjee, did the path relative to the subject directory work in the prior case? 
I would expect the following to find the diffusion weighted image of interest:
```
"IntendedFor": "ses-brainlabMRI/dwi/sub-PR05_ses-brainlabMRI_dir-AP_dwi.nii.gz"
```

Can you provide any information on what manufacturer and sequences were used for these acquisitions? Something may have gone awry in conversion to BIDS.

**Comment by suneelbanerjee** [comment]
hi @pcamach2 , what went awry in the previous case is that our dicom header is actually incorrect. During the dcm2nii conversion, bvals/bvecs are generated that don't reflect the fact that the scan is just 8 b=0 volumes. The manufacturer is GE and the sequence is the ABCD DWI sequence.

The path you suggested worked! Now I am simply wondering whether distortion correction can take place using a 'fieldmap' that only contains 8 b=0 volumes. Thanks again.

**Comment by mattcieslak** [comment]
how many b=0 volumes do you have in each phase encoding direction? 8 is probably more than enough as long as you have a few in the other direction

**Comment by suneelbanerjee** [comment]
Hi @mattcieslak , yeah looks like there were exactly 8 b=0 volumes in the other direction too. QSIprep handled things beautifully. Thanks again for your help!
