### ISSUE TITLE
Brainnetome246 atlas has 256 regions

### ISSUE THREAD

**Issue by vnckppl** [PennLINC/qsiprep#645]
The number of columns/rows in the output of the qsiprep pipeline (e.g., in the 'brainnetome246_sift_invnodevol_radius2_count_connectivity' matrix) is 256. It seems to contain all regions of the brainnetome246 atlas as well as 10 cerebellar regions. Where can I find more information about these 10 cerebellar regions such as their labels, MNI coordinates (for display usage of nodes), etc.?

**Comment by mattcieslak** [comment]
you can find the atlases here: https://upenn.box.com/shared/static/40f2m6dzzd8co5jx3cxpgct3zkkwm5d3.xz
and unzip this with `tar xvfJ`. It has the images and a corresponding sidecar for each with the atlases. Let me know if anything is missing from there that you're looking for.

**Comment by vnckppl** [comment]
Thank you, that is helpful.

**Comment by jiazhuotao** [comment]
> The number of columns/rows in the output of the qsiprep pipeline (e.g., in the 'brainnetome246_sift_invnodevol_radius2_count_connectivity' matrix) is 256. It seems to contain all regions of the brainnetome246 atlas as well as 10 cerebellar regions. Where can I find more information about these 10 cerebellar regions such as their labels, MNI coordinates (for display usage of nodes), etc.?

Hello, seeing your answer, I would like to know which command line parameters you used, if it is convenient for you, I hope you can tell me, thanks!

**Comment by vnckppl** [comment]
> > The number of columns/rows in the output of the qsiprep pipeline (e.g., in the 'brainnetome246_sift_invnodevol_radius2_count_connectivity' matrix) is 256. It seems to contain all regions of the brainnetome246 atlas as well as 10 cerebellar regions. Where can I find more information about these 10 cerebellar regions such as their labels, MNI coordinates (for display usage of nodes), etc.?
> 
> Hello, seeing your answer, I would like to know which command line parameters you used, if it is convenient for you, I hope you can tell me, thanks!

Can you be more specific? What is it that you are trying to do?

**Comment by jiazhuotao** [comment]
> brainnetome246

Thank you very much for replying, I would like to use the WU-Minn HCP Retest Data with the processing filter of “Unprocessed” to get the brainnetome246 Atlas.So I want to know that you are using the command line, to generate the Atlas
