### ISSUE TITLE
multishell_scalarfest: NODDI never ending

### ISSUE THREAD

**Issue by dkp** [PennLINC/qsiprep#646]
**Overview**: When I run multishell_scalarfest, it generates most results, but not the NODDI results (like AMICO NODDI by itself, the process just goes on and on)

**Environment** This is all with apptainer slurm jobs on the HPC, using qsiprep 0.19.

I'm attaching the slurm log for multishell_scalarfest
[slurm-1651096_multishell_scalarfest_noddi-fail1.txt](https://github.com/PennLINC/qsiprep/files/12910908/slurm-1651096_multishell_scalarfest_noddi-fail1.txt)

and here's what it did generate:

$ cd qsirecon_scalar_fest/
$ tree
.
|-- logs
|   |-- CITATION.html
|   |-- CITATION.md
|   `-- CITATION.tex
`-- sub-CAM003
    `-- ses-01brain
        `-- dwi
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-ad_DKI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-ak_DKI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-CNR_3dSHORE.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-colorFA_DKI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-extrapolated_3dSHORE.b
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-extrapolated_3dSHORE.bval
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-extrapolated_3dSHORE.bvec
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-extrapolated_3dSHORE.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-fa_DKI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-kfa_DKI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-L1alpha_3dSHORE.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-lapnorm_MAPMRI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-md_DKI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-mk_DKI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-mkt_DKI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-msd_MAPMRI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-qiv_MAPMRI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-r2_3dSHORE.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-rd_DKI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-regularization_3dSHORE.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-rk_DKI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-rtap_MAPMRI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-rtop_3dSHORE.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-rtop_MAPMRI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-rtpp_MAPMRI.nii.gz
            |-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-SHOREcoeff_3dSHORE.nii.gz
            `-- sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_desc-tensor_DKI.nii.gz

4 directories, 30 files

**Comment by smeisler** [comment]
Hi @dkp,

What's your memory/CPU allocation for this job?

**Comment by dkp** [comment]
10 hours wall time (but I restarted it and the additional 10 hours did not help).
16 CPUs, 4 GB of RAM per CPU
______________

#SBATCH --partition=standard

### Walltime is clock time
### --time HH:MM:SS (below, 10 hours)
#SBATCH --time=10:00:00

### Specify the number of nodes, cpus and memory
#SBATCH --nodes=1 --ntasks=16

### Specify a name for the job
#SBATCH --job-name=runqsirecon
### Specify the group name
#SBATCH --account=dkp

### standard error and standard out are joined by default

#SBATCH --mail-type=ALL
#SBATCH --mail-user=dkp@arizona.edu

**Comment by smeisler** [comment]
Can you share your full command for QSIPrep? Mainly interested in whether you also explicitly defined cpu (and max cpu per process) in the command. In general I have found that 12 cpus total with 8 max per process has worked well. Can you also talk about your data? E.g., how many directions, acquisition scheme, and confirming that it is multishell (required for NODDI)

**Comment by dkp** [comment]
Sorry, I should have done this up front:
**Data Description** 
This is a single subject with ADNI4-compatible multishell data: 3 shells besides b0: 1000, 2000, 3000: 131 diffusion directions, 2 mm isotropic voxels. There are RPE b0 images for distortion correction

**Command**
apptainer run --cleanenv \
--bind ${DATA}:/data:ro \
--bind ${APP_PREP_DERIV_DIR}:/qsiprep-output:ro \
--bind ${APP_DERIV_DIR}:/out \
--bind ${WORK_DIR}:/work \
${APP} /data /out participant \
--participant_label ${Subject} \
--recon-input /qsiprep-output \
--recon-spec ${RECON_SPEC} \
--stop-on-first-crash \
--output-resolution 1.3 -w /work -v -v  \
--n-cpus 16 --omp-nthreads 15 \
--skip-odf-reports --recon-only \
--fs-license-file ${HOME}/license.txt \
--freesurfer_input ${FREESURFER_DIR}

All of the following reconstructions have worked: 	
        - dipy_3dshore
	- dipy_dki
	- dipy_mapmri
	- dsi_studio_autotrack
	- dsi_studio_gqi
	- mrtrix_multishell_msmt_ACT-hsvs
	- mrtrix_multishell_msmt_pyafq_tractometry
	- pyafq_tractometry

**Comment by smeisler** [comment]
Are you allowed to increase walltime above 10h?

**Comment by dkp** [comment]
Yes, and I am now trying the following:
20 hours walltime, 
24 cpus (2 nodes), 
This should be 96 GB ram on el gato (4 GB of RAM per CPU).  
I also removed the --n-cpus 16 --omp-nthreads 15

There are a couple of other machines that provide 6 GB of ram per CPU.  I could try those instead if you think I have not provided enough compute power.

**Comment by dkp** [comment]
Yay!  It looks like those extra resources did the trick!  Thank you so much!
