### ISSUE TITLE
issue with longitudinal T1 template

### ISSUE THREAD

**Issue by dcoynel** [PennLINC/qsiprep#647]
Hi everyone, thanks for developing this great tool.

I have longitudinal data, with 2 time points. A T1 and DWI data were acquired at each time point.

I ran qsiprep v0.19.1 through a singularity container using the following command:
```
singularity run --cleanenv \
    -B nifti:/data:ro \
    -B derivatives:/out \
    qsiprep-0.19.1.sif \
    /data /out participant \
    -w /out/qsiprep/tmp-cache_nobackup \
    --output-resolution 2 \
    --verbose \
    --anat-modality T1w \
    --longitudinal \
    --participant_label $subject
```

The average T1 found under sub-XYZ/anat/sub-XYZ_desc-preproc_T1w.nii is not great at all, as you can see below. It appears just as a crude average of both T1s, without further co-registration.

It seems as if the template creation is not complete. I noticed that the number of iterations in this case is set to only 2  in [here](https://github.com/PennLINC/qsiprep/blob/b719e7836cd080cc358f7fd3d4c7b641db1efdb2/qsiprep/workflows/anatomical/volume.py#L639C20-L639C20). 

Am I missing something? Thanks for your help.

Best,
David

![001](https://github.com/PennLINC/qsiprep/assets/9464571/f37fa3c7-b730-4df4-819a-4c9d5098d8ee)

**Comment by mattcieslak** [comment]
2 should be enough iterations - does this look any better if you remove the longitudinal flag?

**Comment by cookpa** [comment]
I think what is happening is that there are two images contributing to the average, each starts out aligned to the "shadow" of itself, and gets stuck in a local minimum there. I believe this is why the default is to not use this approach with less than 3 time points.
 
 @mattcieslak , in ANTs we try to get around this by doing a [center of mass alignment to the average](https://github.com/ANTsX/ANTs/blob/9516f51c9dcf92827a4daba48a039648c533bd72/Scripts/antsMultivariateTemplateConstruction2.sh#L1080-L1087), and then recomputing the average.

**Comment by dcoynel** [comment]
Thanks for your inputs.

@mattcieslak, @cookpa : It works without the flag, but my initial thought was to not favor one time point over the other when creating the T1w reference map. As it is by default, and as far as I can see, the reference T1w is the ACPC-aligned T1 of the first session. 

@cookpa : If I understand you correctly, there is no possibility to do the center of mass alignment in qsiprep?

**Comment by mattcieslak** [comment]
In a recent release I swapped FreeSurfers mri robust template with the workflow used to align b=0 volumes from the same dwi scan. That workflow doesn't do center of mass adjustment for the b=0 scans, but it can be added for the T1w alignment

**Comment by dcoynel** [comment]
Thanks for the proposition. Do you also think it would make sense to include this possibility when 2 T1 are acquired (creating a template that is the average of both)? I don't want to setup an option that is only valid in my scenario.

**Comment by mattcieslak** [comment]
If you skip the --longitudinal flag, the second T1w will be registered to the first. Ultimately, this averaged T1w will be reoriented to AC-PC alignment, so the --longitudinal flag doesn't make much sense in my opinion. In your situation I would either run without the longitudinal flag or use bids filter files to run each session separately
