### ISSUE TITLE
Which T1w is in the /anat folder?

### ISSUE THREAD

**Issue by suneelbanerjee** [PennLINC/qsiprep#654]
Hi guys, 

I've just preprocessed some data, for which some subjects have multiple sessions (and multiple anatomical scans). In the /anat subfolder, I only see one preprocessed T1w image. Which session does this correspond to? Is there a way to generate preprocessed T1w's for both sessions independently?

[I am not using the longitudinal flag](https://github.com/PennLINC/qsiprep/issues/647). Please let me know if file trees or any other information would be helpful. Thanks!

**Comment by smeisler** [comment]
Hi @suneelbanerjee,

This is explained in the documentation here: https://qsiprep.readthedocs.io/en/latest/preprocessing.html?highlight=longitudinal#longitudinal-t1w-processing

QSIPrep by default will always produce a single T1w image using all T1w images available. The `--longitudinal` flag just changes whether the template is based on the first T1w image (`--longitudinal` off) or is an unbiased template of all images available (`--longitudinal` on). If you want to work with sessions independently, you can use a `--bids-filter-file` as described in the documentation here: https://qsiprep.readthedocs.io/en/latest/preprocessing.html?highlight=filter#using-bids-filters. Keep in mind this can have important implications for longitudinal data anlaysis.

For future questions like this (that are not software bugs), please ask them in the [Neurostars.org](Neurostars.org) support forum, under the Software Support category, using the `qsiprep` tag.

Best,
Steven
