### ISSUE TITLE
Tian subcortical atlas

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsiprep#655]
Hi @mattcieslak,

I have some analyses for which subcortical parcellation that includes the hippocampus would be invaluable. Schaefer atlases are my general preference, but the CIT168 atlas doesn't include the hippocampus.

I realize that not everyone needs every atlas in the universe so what would I need to do locally to use the Tian atlas (https://github.com/yetianmed/subcortex/tree/master) in recon workflows?

Thanks

**Comment by araikes** [comment]
Alternatively, is there a way to utilize the updated Schaefer atlases currently in AtlasPack (just saw the commits with the inclusion of the hippocampal nodes)

**Comment by smeisler** [comment]
Does this page help? https://qsiprep.readthedocs.io/en/latest/reconstruction.html?highlight=atlas#using-custom-atlases

**Comment by araikes** [comment]
Yep... knew that was somewhere...
