### ISSUE TITLE
QSIprep not picking up lesion masks

### ISSUE THREAD

**Issue by psadil** [PennLINC/qsiprep#657]
I have a bids dataset like the following

``` bash
.
├── dataset_description.json
├── README
└── sub-01
   └── ses-1
      ├── anat
      │  ├── sub-01_ses-1_desc-lesion_roi.nii.gz
      │  ├── sub-01_ses-1_T1w.json
      │  └── sub-01_ses-1_T1w.nii.gz
      └── dwi
         ├── sub-01_ses-1_dwi.bval
         ├── sub-01_ses-1_dwi.bvec
         ├── sub-01_ses-1_dwi.json
         ├── sub-01_ses-1_dwi.nii.gz
```
When trying to process this with `qsiprep`

``` bash
ROOT=#path
SCRATCH=#path

singularity run   -e  \ 
  --bind $ROOT:/ds   \
  --bind $SCRATCH:/scratch \
  docker://pennbbl/qsiprep:0.19.1 \
  --fs-license-file  /ds/qsiprep/code/license \
  -w /scratch/work \
  --participant-label 01 \
  --output-resolution 2.0 \
  /ds/bids/rawdata /scratch/work participant 
```

the lesion is absent from the `bidssrc` node

``` bash
$ grep "roi :" $SCRATCH/work/qsiprep_wf/single_subject_01_wf/bidssrc/_report/report.rst 
* roi : <undefined>
```

The issue is in how data are collected: https://github.com/PennLINC/qsiprep/blob/b719e7836cd080cc358f7fd3d4c7b641db1efdb2/qsiprep/utils/bids.py#L137-L145

The function [`collect_data` is called with the defaults](https://github.com/PennLINC/qsiprep/blob/b719e7836cd080cc358f7fd3d4c7b641db1efdb2/qsiprep/workflows/base.py#L481), and `bids_dir` as a string, meaning that the layout is created with `validate=True`. But when `validate=True`, the layout excludes files that do not adhere to the BIDS standard, which currently doesn't include the roi suffix. For example:

``` python
In [1]: import bids

In [2]: layout=bids.BIDSLayout("/ds/bids/rawdata")

In [3]: layout.get(subject="01", suffix="roi")
Out[3]: []

In [4]: layout=bids.BIDSLayout("/ds/bids/rawdata", validate=False)

In [5]: layout.get(subject="01", suffix="roi")
Out[5]: [<BIDSImageFile filename='/ds/bids/rawdata/sub-01/ses-1/anat/sub-01_ses-1_desc-lesion_roi.nii.gz'>]

In [6]: bids.__version__
Out[6]: '0.16.3'

```

Note that the same lesion roi is picked up by `smriprep`, a pipeline that [imports a version of `collect_data` from `niworkflows`](https://github.com/nipreps/smriprep/blob/93b0f3f70eecc22890a457d326b2d7282815f4db/smriprep/workflows/base.py#L35C6-L35C6) and passes in a [`layout` that was created with `validate=False`](https://github.com/nipreps/smriprep/blob/93b0f3f70eecc22890a457d326b2d7282815f4db/smriprep/cli/run.py#L460).

**Comment by psadil** [comment]
If pull requests are welcome, I'd be happy to submit one

**Comment by mattcieslak** [comment]
Pull requests are always welcome! I may not be able to review in for a few weeks though
