### ISSUE TITLE
Leverage phase data, when available, at denoising stage

### ISSUE THREAD

**Issue by tsalo** [PennLINC/qsiprep#677]
`dwidenoise` (MRTRIX3 >= 3.0.0) can handle complex-valued data, which improves the denoising.

Here's what the documentation says:

>Note that dwidenoise does not correct for non-Gaussian noise biases present in magnitude-reconstructed MRI images. Including MRI phase images can reduce such Rician bias [[CorderoGrande2019]](https://mrtrix.readthedocs.io/en/latest/reference/references.html#corderogrande2019), and the command now supports complex input data. To this end, users can run:
>
> ```
> mrcalc dwi_magnitude.mif dwi_phase_rad.mif -polar dwi_complex.mif
> dwidenoise dwi_complex.mif out.mif -noise noise.mif
> mrcalc out.mif -abs out_magnitude.mif
> ```
>
> Where dwi_magnitude.mif and dwi_phase_rad.mif are the magnitude and phase images respectively. Note that the code above assumes that the phase is scaled in radians.
>
>Whilst using complex data can effectively reduce Rician noise bias, dwidenoise currently does not account for spatial noise correlations introduced due to in-plane accelleration. [[CorderoGrande2019]](https://mrtrix.readthedocs.io/en/latest/reference/references.html#corderogrande2019) addresses these additional effects at reconstruction, but this is not implemented in MRtrix3.

On QSIPrep's side, I think it would need to (1) collect the phase data when available, (2) create the complex-valued files from the magnitude and phase data, (3) run `dwidenoise` on the complex files, and (4) split out the magnitude data from the denoised complex files.

**Comment by mattcieslak** [comment]
This actually seems pretty doable! The denoising happens at the very beginning of the processing stream so we can run these commands and pass the denoised magnitude data to the rest of the pipeline

**Comment by tsalo** [comment]
Is anyone aware of any other uses for phase data with DWI? In fMRI, there are complex-valued modeling approaches and phase regression denoising methods, though neither is widely used.
