### ISSUE TITLE
Restructure CLI to bring in line with nipreps

### ISSUE THREAD

**Issue by tsalo** [PennLINC/qsiprep#697]
## Summary

I have a few thoughts about how the QSIPrep CLI could be brought in line with the other preps a bit more.

1. Split QSIRecon out of QSIPrep. It could still be in the same package, but with a separate command.
2. Combine `--recon-input` and `--freesurfer-input` into a `--derivatives` that accepts a list of paths.
3. Add `--level` parameter to preprocessing workflow.
    - I don't know what specifically this would entail- I imagine it's different for each modality, depending on what kind of preprocesing is involved, but the `minimal` option in fMRIPrep and ASLPrep involves outputting transform files, but not resampled imaging files.

This is related to #696.

## Additional details

1. Simpler command-line interfaces.
2. Better synergy with other tools.
3. Easier for users to mix and match pipelines if QSIPrep is treated as a preprocessing pipeline and QSIRecon is treated as a postprocessing recon (like XCP-D, fMRIPost-AROMA, fMRIPost-tedana, and fMRIPost-rapidtide).

### Drawbacks

1. The full combination of preprocessing and reconstruction would take two commands instead of one.

**Comment by mattcieslak** [comment]
This all looks good, except for `--level`, which isn't possible for qsiprep for now. The reason is that eddy and many of its advanced features can't be split up into transforms. For example, the outlier replacement and slice to volume motion correction can't be delayed until the end of the pipeline by simply keeping transform files around.

I think you're totally right about (1) too. They don't share very much code and having both of their commandline options intermingled makes use of either more confusing. It might even be a good chance to start qsirecon in a clean repo

**Comment by cookpa** [comment]
+1 on a standalone qsirecon with standalone documentation.

**Comment by mattcieslak** [comment]
I've been thinking about this one - there isn't a ton of overlap between the two workflows, but there definitely is some. I have a hunch that almost all of the overlap could be replaced by things already in nipreps.

**Comment by mattcieslak** [comment]
I'm on board - would you recommend forking qsiprep to start? Or starting with a fresh repo and copying as needed?

**Comment by tsalo** [comment]
I think we can just work within qsiprep for the initial CLI split. If we want to move forward with a full repo split, we can do that later.

**Comment by tsalo** [comment]
Then again... it's probably just easier to create a new repo and make QSIPrep a dependency of QSIRecon. Otherwise I have to create multiple versions of a bunch of files in the repo for the two pipelines.

**Comment by mattcieslak** [comment]
Going through the workflows now, the overlap isn't as big as I was initially worried about. We might not even need a dependency on a qsiprep

**Comment by mattcieslak** [comment]
the config object will also benefit from having 2 separate packages. it's currently not as straightforward as a config for a package that does only one main thing

**Comment by tsalo** [comment]
Okay, I've got the QSIPost repo started up in [`pennlinc/qsipost`](https://github.com/PennLINC/qsipost).
