### ISSUE TITLE
Create a "slspec.txt" that can be used by eddy

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/qsiprep#706]
In order to use slice-to-volume, we need to create a slice spec file that Eddy can use.

 - [x] If more than 1 image is being corrected by eddy, make sure the slice order/timing are the same. How different is too different in slice timings?
 - [x] Format the slice times into slspec.txt

**Comment by cookpa** [comment]
Recent eddy can read the timings directly with the `--json` option, might be easier than making slspec

**Comment by mattcieslak** [comment]
excellent! That means the only action item is to figure out how big of a difference in slice timings we will allow if scans are being concatenated. Do you have a suggestion for a cutoff? I was thinking maybe 10 milliseconds?

**Comment by cookpa** [comment]
Eyeballing some HCP scans (MBA=4), I see variance of about 2.5ms within sessions, so 10ms seems reasonable.

**Comment by mattcieslak** [comment]
added in v0.21.0
