### ISSUE TITLE
Two desc-<value> pairs in qsirecon output

### ISSUE THREAD

**Issue by chiuhoward** [PennLINC/qsiprep#716]
## Summary

- QSIPrep version: 0.20.1.dev0+geda84d5.d20240112
- Docker version: NA
- Singularity version: apptainer version 1.2.5-1.el7

### What were you trying to do?
I was trying to run pyAFQ with qsirecon output as input for pyAFQ.

### What did you expect to happen?
I expected pyAFQ to pick up the ifod2.tck files.

### What actually happened?
pyAFQ ignored the files which were not compliant as there were two desc-<value> pairs
[qsirecon_errors.txt](https://github.com/PennLINC/qsiprep/files/14747172/qsirecon_errors.txt)
.

**Comment by tsalo** [comment]
It looks like the PyAFQ outputs still have duplicate entities, like two descs and two spaces in `sub-ABCD_acq-10per000_space-T1w_desc-preproc_dwimap/ROIs/sub-ABCD_acq-10per000_space-T1w_desc-preproc_dwi_space-subject_desc-ARCL1end_mask.nii.gz`

**Comment by chiuhoward** [comment]
Hi @tsalo, what version of pyAFQ are you running? the ARC abbreviation in the ROI mask leads me to believe that this is pyAFQ<1.3

**Comment by tsalo** [comment]
That's just one of the outputs from the integration tests in https://github.com/PennLINC/qsiprep/pull/763, so it's whatever PyAFQ version is bundled into the current unstable version of QSIPrep.

**Comment by chiuhoward** [comment]
@tsalo this should have been fixed in the current release of pyAFQ, if i’m reading the code correctly… [https://github.com/yeatmanlab/pyAFQ/blob/899d504c7b75cca7a41f3c48daed9c614754d762/AFQ/api/bundle_dict.py#L1071C1-L1081C40](url)

anecdotally, my outputs are also BIDS compliant

**Comment by arokem** [comment]
Looks like qsiprep is [pinning to `<=1.3.1`](https://github.com/PennLINC/qsiprep/blob/master/pyproject.toml#L35). Is there a reason to do that? Current pyAFQ is 1.3.2, which may fix this.

**Comment by tsalo** [comment]
Setting max versions makes it less likely that backwards-incompatible dependency releases will be merged in. I imagine @mattcieslak just hasn't gotten around to updating the pinned PyAFQ version.

**Comment by arokem** [comment]
OK - let's give it a try: https://github.com/PennLINC/qsiprep/pull/764
