### ISSUE TITLE
bug in mrtrix_multishell_msmt_ACT-hsvs recon? TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by DVSneuro** [PennLINC/qsiprep#731]
## Summary
When running the `mrtrix_multishell_msmt_ACT-hsvs` recon spec, the program crashes with `TypeError: expected str, bytes or os.PathLike object, not NoneType` before producing any output. Notably, there was recently a similar bug with MRIQC (https://github.com/nipreps/mriqc/issues/1282), but I don't know if they're related. Let us know if we can provide more information. Thanks for any help!

Best wishes,
David

## Additional details

- QSIPrep version: 0.20.0
- Docker version: n/a
- Singularity version: 3.6.3

### What were you trying to do?
I was trying to run the `mrtrix_multishell_msmt_ACT-hsvs` recon spec on data that has already passed through qsiprep. Note that other recon specs (`amico_noddi` and `mrtrix_multishell_msmt_pyafq_tractometry`) appear to work fine.

### What did you expect to happen?
I expected the program to complete and produce output, but we get the error below each time we run it.

### What actually happened?
Here's the error output. Let me know if there's anything else I can send along for debugging help. 

```
    Running qsirecon version 0.20.1.dev0+geda84d5.d20240112:
      * BIDS dataset path: /input.
      * Participant list: ['10418'].
      * Run identifier: 20240423-084821_0e96c7de-d9aa-4972-88b8-4c1b1e5aac51.
    
240423-08:50:35,661 nipype.workflow INFO:
	 found ['/base/derivatives/qsirecon-ACThsvs/qsiprep/sub-10418/dwi/sub-10418_space-T1w_desc-preproc_dwi.nii.gz'] in /base/derivatives/qsirecon-ACThsvs/qsiprep
240423-08:50:35,662 nipype.workflow INFO:
	 Found usable QSIPrep-preprocessed T1w image and mask.
240423-08:50:35,662 nipype.workflow INFO:
	 Found high-res anatomical data in preprocessed inputs for 10418.
Process Process-4:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.10/site-packages/qsiprep/cli/run.py", line 1198, in build_recon_workflow
    retval['workflow'] = init_qsirecon_wf(
  File "/usr/local/miniconda/lib/python3.10/site-packages/qsiprep/workflows/recon/base.py", line 99, in init_qsirecon_wf
    single_subject_wf = init_single_subject_wf(
  File "/usr/local/miniconda/lib/python3.10/site-packages/qsiprep/workflows/recon/base.py", line 208, in init_single_subject_wf
    anat_ingress_node, available_anatomical_data = init_highres_recon_anatomical_wf(
  File "/usr/local/miniconda/lib/python3.10/site-packages/qsiprep/workflows/recon/anatomical.py", line 133, in init_highres_recon_anatomical_wf
    missing_fs_hsvs_files = check_hsv_inputs(Path(subject_freesurfer_path))
  File "/usr/local/miniconda/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/local/miniconda/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/miniconda/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## Reproducing the bug
The code we used is below. We're working to get our data up on OpenNeuro, and I can hopefully follow up with a link to that in the next few days. 

```
TEMPLATEFLOW_DIR=/ZPOOL/data/tools/templateflow
export APPTAINERENV_TEMPLATEFLOW_HOME=/opt/templateflow

singularity run --cleanenv \
-B ${TEMPLATEFLOW_DIR}:/opt/templateflow \
-B $inputdata:/input \
-B $maindir:/base \
-B /ZPOOL/data/tools/licenses:/opts \
-B $scratchdir:/scratch \
/ZPOOL/data/tools/qsiprep-0.20.0.simg \
/input /base/derivatives/qsirecon-ACThsvs \
participant --participant_label $sub \
--output-resolution 2 \
--recon_input /base/derivatives/qsiprep \
--recon_spec mrtrix_multishell_msmt_ACT-hsvs \
--fs-license-file /opts/fs_license.txt \
-w /scratch
```

**Comment by mattcieslak** [comment]
Thanks for reporting! Is your data in datalad? and if so have you made sure the data is available locally?

**Comment by araikes** [comment]
You're using `ACT-hsvs` but it doesn't appear that you're specifying a location for freesurfer inputs.

**Comment by DVSneuro** [comment]
Ah, sorry I missed that and thanks for catching it, @araikes! The issue here was indeed due to not having `--freesurfer-input /base/derivatives/fmriprep/sourcedata/freesurfer` in the command.

Also, @mattcieslak these data were local (not datalad). We'll still end up posting the dataset soon and hopefully others can use it! Looking forward to working more with QSIprep, and thanks for providing a great tool for the community!
