### ISSUE TITLE
Request for option to include ses-<label> entity in all files when a session is present

### ISSUE THREAD

**Issue by psadil** [PennLINC/qsiprep#757]
## Summary

I am helping process a dataset that involves multiple subjects, some of whom where scanned in multiple sessions. The workflow involves creating a bids dataset for each distinct subject and session and then passing these to qsiprep. This works great for processing, but the outputs are difficult to aggregate. The difficulty is because qsiprep only uses the `ses-<label>` entity in files that are underneath the `ses-<label>/` subfolder. For example, qsiprep produced these top-level anat files

```shell
$ tree sub-10042 | head
sub-10042
├── anat
│   ├── sub-10042_desc-aseg_dseg.nii.gz
│   ├── sub-10042_desc-brain_mask.nii.gz
│   ├── sub-10042_desc-preproc_T1w.nii.gz
│   ├── sub-10042_dseg.nii.gz
```
Aggregating the folders produced by qsiprep would cause one sessions' anat files to overwrite the other. 

Contrast that with cases like fmriprep, which produces outputs that can be merged because files always include the session entity. For example

```shell
$ tree sub-10003 | head
sub-10003
├── figures
│   ├── sub-10003_ses-V1_desc-about_T1w.html 
│   ├── sub-10003_ses-V1_desc-conform_T1w.html 
│   ├── sub-10003_ses-V1_desc-reconall_T1w.svg 
│   ├── sub-10003_ses-V1_desc-summary_T1w.html
```

## Additional details

I'm not sure if one approach is more BIDS compliant than the other. This part of the BIDS spec may be relevant: https://bids-specification.readthedocs.io/en/v1.9.0/common-principles.html#filenames

> For a data file that was collected in a given session from a given subject, the filename MUST begin with the string sub-<label>_ses-<label>. Conversely, if the session level is omitted in the directory structure, the file name MUST begin with the string sub-<label>, without ses-<label>.

So, that could be taken to mean that if there is a session level directory present anywhere, then the `ses-<label>` entity should be included in all files.

Edit:

Also, a relevant passage from the Derivatives spec: https://bids-specification.readthedocs.io/en/v1.9.0/derivatives/introduction.html#file-naming-conventions

> Each Derivatives filename MUST be of the form: <source_entities>[_keyword-<value>]_<suffix>.<extension> (where <value> could either be an <index> or a <label> depending on the keyword; see [Definitions](https://bids-specification.readthedocs.io/en/v1.9.0/common-principles.html#definitions))

**Comment by araikes** [comment]
Given that the `anat` folder is a top level folder and is essentially a subject specific template space (rather than reflecting a specific session), how would you envision this?

Also, your tree examples contrast the `anat` folder with the `figures` folder where the figures are relevant to the reports and need session naming to be attached to the correct location in the report. The current top-level fmriprep `anat` folder does not contain any session indicators (for the same reason mentioned above).

**Comment by psadil** [comment]
The current layout makes sense to me, it's just inconvenient in the circumstance that I was describing (aggregating across sessions and wanting to keep information about the specific anatomicals that were used in each session)

FWIW, I see that both of these folders can pass bids (1.9.0) validation

A)
```shell
.
├── dataset_description.json
└── sub-1
   ├── anat
   │  └── sub-1_T1w.nii.gz
   └── ses-1
      └── anat
         └── sub-1_ses-1_T1w.nii.gz
```
B)
```shell
.
├── dataset_description.json
└── sub-1
   └── ses-1
      └── anat
         └── sub-1_ses-1_T1w.nii.gz
```
and this does not

C)
```shell
.
├── dataset_description.json
└── sub-1
   ├── anat
   │  └── sub-1_ses-1_T1w.nii.gz
   └── ses-1
      └── anat
         └── sub-1_ses-1_T1w.nii.gz
```

So, the request would be for an option that matches the organization of smriprep/fmriprep, which entails nixing the top-level anat folder altogether and placing those files inside the `ses-<label>` directory (with appropriate ses entities in the filenames). This happens even when there is only a single `ses-<label>`.

To be explicit, given organization (A), above, smriprep produces the following
```shell
.
├── dataset_description.json
├── logs/
├── sub-1
│  ├── figures/
│  └── ses-1
│     └── anat
│        ├── sub-1_ses-1_desc-brain_mask.json
│        ├── sub-1_ses-1_desc-brain_mask.nii.gz
│        ├── sub-1_ses-1_desc-preproc_T1w.json
│        ├── sub-1_ses-1_desc-preproc_T1w.nii.gz
│        ├── sub-1_ses-1_dseg.nii.gz
│        ├── sub-1_ses-1_label-CSF_probseg.nii.gz
│        ├── sub-1_ses-1_label-GM_probseg.nii.gz
│        └── sub-1_ses-1_label-WM_probseg.nii.gz
└── sub-1.html
```

**Comment by psadil** [comment]
Another option could be to have something like a `--ses-label` argument, which when used causes sessions within a dataset to be processed individually (e.g., if the bids dataset has multiple sessions, use of `--ses-label` would cause creation of a template for each session separately)

**Comment by araikes** [comment]
The ability to process sessions independently might address what you're looking for, though that may be available through the `bids-filter-file` option.


Regarding your point about wanting to provenance what specific anatomicals were used, is the transform file in the session-specific anatomical folder not specific enough? This retains the source information and includes the derivative target information as part of the file name:
`sub-02_ses-01_run-001_from-orig_to-T1w_mode-image_xfm.mat`

I do want to point out that your assessment doesn't appear to be 100% accurate regarding s/fMRIPrep. I have a multisession dataset processed through fMRIPrep (not running in `longitudinal` mode) and it definitely consolidates down to a single top level `anat` folder and just the transform file from the session T1 to the subject-specific template in the session folders. I'm running sMRIPrep (v 0.15.0) as a check and can confirm that it is generating the same kind of structure, rather than what you showed above as an exemplar sMRIPrep output. See below. 

```
[adamraikes@r2u15n1 fmriprep_23.2.1]$ tree sub-01
sub-01
|-- anat
|   |-- sub-01_run-001_desc-brain_mask.json
|   |-- sub-01_run-001_desc-brain_mask.nii.gz
|   |-- sub-01_run-001_desc-preproc_T1w.json
|   |-- sub-01_run-001_desc-preproc_T1w.nii.gz
|   |-- sub-01_run-001_desc-preproc_T2w.json
|   |-- sub-01_run-001_desc-preproc_T2w.nii.gz
|   |-- sub-01_run-001_desc-ribbon_mask.json
|   |-- sub-01_run-001_desc-ribbon_mask.nii.gz
|   |-- sub-01_run-001_dseg.nii.gz
|   |-- sub-01_run-001_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
|   |-- sub-01_run-001_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
|   |-- sub-01_run-001_from-T1w_to-fsnative_mode-image_xfm.txt
|   |-- sub-01_run-001_from-fsnative_to-T1w_mode-image_xfm.txt
|   |-- sub-01_run-001_hemi-L_desc-reg_sphere.surf.gii
|   |-- sub-01_run-001_hemi-L_midthickness.surf.gii
|   |-- sub-01_run-001_hemi-L_pial.surf.gii
|   |-- sub-01_run-001_hemi-L_space-fsLR_desc-msmsulc_sphere.surf.gii
|   |-- sub-01_run-001_hemi-L_space-fsLR_desc-reg_sphere.surf.gii
|   |-- sub-01_run-001_hemi-L_sphere.surf.gii
|   |-- sub-01_run-001_hemi-L_sulc.shape.gii
|   |-- sub-01_run-001_hemi-L_thickness.shape.gii
|   |-- sub-01_run-001_hemi-L_white.surf.gii
|   |-- sub-01_run-001_hemi-R_desc-reg_sphere.surf.gii
|   |-- sub-01_run-001_hemi-R_midthickness.surf.gii
|   |-- sub-01_run-001_hemi-R_pial.surf.gii
|   |-- sub-01_run-001_hemi-R_space-fsLR_desc-msmsulc_sphere.surf.gii
|   |-- sub-01_run-001_hemi-R_space-fsLR_desc-reg_sphere.surf.gii
|   |-- sub-01_run-001_hemi-R_sphere.surf.gii
|   |-- sub-01_run-001_hemi-R_sulc.shape.gii
|   |-- sub-01_run-001_hemi-R_thickness.shape.gii
|   |-- sub-01_run-001_hemi-R_white.surf.gii
|   |-- sub-01_run-001_label-CSF_probseg.nii.gz
|   |-- sub-01_run-001_label-GM_probseg.nii.gz
|   |-- sub-01_run-001_label-WM_probseg.nii.gz
|   |-- sub-01_run-001_space-MNI152NLin2009cAsym_desc-brain_mask.json
|   |-- sub-01_run-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
|   |-- sub-01_run-001_space-MNI152NLin2009cAsym_desc-preproc_T1w.json
|   |-- sub-01_run-001_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz
|   |-- sub-01_run-001_space-MNI152NLin2009cAsym_dseg.nii.gz
|   |-- sub-01_run-001_space-MNI152NLin2009cAsym_label-CSF_probseg.nii.gz
|   |-- sub-01_run-001_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz
|   `-- sub-01_run-001_space-MNI152NLin2009cAsym_label-WM_probseg.nii.gz
|-- figures
|   |-- sub-01_run-001_desc-conform_T1w.html
|   |-- sub-01_run-001_desc-reconall_T1w.svg
|   |-- sub-01_run-001_dseg.svg
|   |-- sub-01_run-001_space-MNI152NLin2009cAsym_T1w.svg
|   |-- sub-01_ses-01_desc-about_T1w.html
|   |-- sub-01_ses-01_desc-summary_T1w.html
|   |-- sub-01_ses-01_run-001_fmapid-auto00000_desc-phasediff_fieldmap.svg
|   |-- sub-01_ses-01b_task-rest_run-001_desc-carpetplot_bold.svg
|   |-- sub-01_ses-01b_task-rest_run-001_desc-compcorvar_bold.svg
|   |-- sub-01_ses-01b_task-rest_run-001_desc-confoundcorr_bold.svg
|   |-- sub-01_ses-01b_task-rest_run-001_desc-coreg_bold.svg
|   |-- sub-01_ses-01b_task-rest_run-001_desc-fmapCoreg_bold.svg
|   |-- sub-01_ses-01b_task-rest_run-001_desc-rois_bold.svg
|   |-- sub-01_ses-01b_task-rest_run-001_desc-sdc_bold.svg
|   |-- sub-01_ses-01b_task-rest_run-001_desc-summary_bold.html
|   |-- sub-01_ses-01b_task-rest_run-001_desc-validation_bold.html
|   |-- sub-01_ses-02_run-001_fmapid-auto00001_desc-phasediff_fieldmap.svg
|   |-- sub-01_ses-02_task-rest_run-001_desc-carpetplot_bold.svg
|   |-- sub-01_ses-02_task-rest_run-001_desc-compcorvar_bold.svg
|   |-- sub-01_ses-02_task-rest_run-001_desc-confoundcorr_bold.svg
|   |-- sub-01_ses-02_task-rest_run-001_desc-coreg_bold.svg
|   |-- sub-01_ses-02_task-rest_run-001_desc-fmapCoreg_bold.svg
|   |-- sub-01_ses-02_task-rest_run-001_desc-rois_bold.svg
|   |-- sub-01_ses-02_task-rest_run-001_desc-sdc_bold.svg
|   |-- sub-01_ses-02_task-rest_run-001_desc-summary_bold.html
|   `-- sub-01_ses-02_task-rest_run-001_desc-validation_bold.html
|-- log
|   `-- 20240417-160843_04f92473-c911-4f79-b6b2-3c9b570d5546
|       `-- fmriprep.toml
|-- ses-01
|   |-- anat
|   |   `-- sub-01_ses-01_run-001_from-orig_to-T1w_mode-image_xfm.txt
|   `-- fmap
|       |-- sub-01_ses-01_run-001_fmapid-auto00000_desc-coeff0_fieldmap.nii.gz
|       |-- sub-01_ses-01_run-001_fmapid-auto00000_desc-coeff1_fieldmap.nii.gz
|       |-- sub-01_ses-01_run-001_fmapid-auto00000_desc-magnitude_fieldmap.nii.gz
|       |-- sub-01_ses-01_run-001_fmapid-auto00000_desc-preproc_fieldmap.json
|       `-- sub-01_ses-01_run-001_fmapid-auto00000_desc-preproc_fieldmap.nii.gz
|-- ses-01b
|   |-- anat
|   |   `-- sub-01_ses-01b_run-001_from-orig_to-T1w_mode-image_xfm.txt
|   `-- func
|       |-- sub-01_ses-01b_task-rest_run-001_desc-confounds_timeseries.json
|       |-- sub-01_ses-01b_task-rest_run-001_desc-confounds_timeseries.tsv
|       |-- sub-01_ses-01b_task-rest_run-001_desc-coreg_boldref.json
|       |-- sub-01_ses-01b_task-rest_run-001_desc-coreg_boldref.nii.gz
|       |-- sub-01_ses-01b_task-rest_run-001_desc-hmc_boldref.json
|       |-- sub-01_ses-01b_task-rest_run-001_desc-hmc_boldref.nii.gz
|       |-- sub-01_ses-01b_task-rest_run-001_from-boldref_to-T1w_mode-image_desc-coreg_xfm.json
|       |-- sub-01_ses-01b_task-rest_run-001_from-boldref_to-T1w_mode-image_desc-coreg_xfm.txt
|       |-- sub-01_ses-01b_task-rest_run-001_from-boldref_to-auto00000_mode-image_xfm.json
|       |-- sub-01_ses-01b_task-rest_run-001_from-boldref_to-auto00000_mode-image_xfm.txt
|       |-- sub-01_ses-01b_task-rest_run-001_from-orig_to-boldref_mode-image_desc-hmc_xfm.json
|       |-- sub-01_ses-01b_task-rest_run-001_from-orig_to-boldref_mode-image_desc-hmc_xfm.txt
|       |-- sub-01_ses-01b_task-rest_run-001_space-MNI152NLin2009cAsym_boldref.nii.gz
|       |-- sub-01_ses-01b_task-rest_run-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
|       |-- sub-01_ses-01b_task-rest_run-001_space-MNI152NLin2009cAsym_desc-preproc_bold.json
|       `-- sub-01_ses-01b_task-rest_run-001_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
`-- ses-02
    |-- anat
    |   `-- sub-01_ses-02_run-001_from-orig_to-T1w_mode-image_xfm.txt
    |-- fmap
    |   |-- sub-01_ses-02_run-001_fmapid-auto00001_desc-coeff0_fieldmap.nii.gz
    |   |-- sub-01_ses-02_run-001_fmapid-auto00001_desc-coeff1_fieldmap.nii.gz
    |   |-- sub-01_ses-02_run-001_fmapid-auto00001_desc-magnitude_fieldmap.nii.gz
    |   |-- sub-01_ses-02_run-001_fmapid-auto00001_desc-preproc_fieldmap.json
    |   `-- sub-01_ses-02_run-001_fmapid-auto00001_desc-preproc_fieldmap.nii.gz
    `-- func
        |-- sub-01_ses-02_task-rest_run-001_desc-confounds_timeseries.json
        |-- sub-01_ses-02_task-rest_run-001_desc-confounds_timeseries.tsv
        |-- sub-01_ses-02_task-rest_run-001_desc-coreg_boldref.json
        |-- sub-01_ses-02_task-rest_run-001_desc-coreg_boldref.nii.gz
        |-- sub-01_ses-02_task-rest_run-001_desc-hmc_boldref.json
        |-- sub-01_ses-02_task-rest_run-001_desc-hmc_boldref.nii.gz
        |-- sub-01_ses-02_task-rest_run-001_from-boldref_to-T1w_mode-image_desc-coreg_xfm.json
        |-- sub-01_ses-02_task-rest_run-001_from-boldref_to-T1w_mode-image_desc-coreg_xfm.txt
        |-- sub-01_ses-02_task-rest_run-001_from-boldref_to-auto00001_mode-image_xfm.json
        |-- sub-01_ses-02_task-rest_run-001_from-boldref_to-auto00001_mode-image_xfm.txt
        |-- sub-01_ses-02_task-rest_run-001_from-orig_to-boldref_mode-image_desc-hmc_xfm.json
        |-- sub-01_ses-02_task-rest_run-001_from-orig_to-boldref_mode-image_desc-hmc_xfm.txt
        |-- sub-01_ses-02_task-rest_run-001_space-MNI152NLin2009cAsym_boldref.nii.gz
        |-- sub-01_ses-02_task-rest_run-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
        |-- sub-01_ses-02_task-rest_run-001_space-MNI152NLin2009cAsym_desc-preproc_bold.json
        `-- sub-01_ses-02_task-rest_run-001_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
```

**Comment by araikes** [comment]
I went back and reread the context....

Is this a paradigm in which you expect the overall brain structure to change substantially from time point to time point to where it would make a difference whether individuals are session-registered or template registered (e.g. atrophy)?

**Comment by psadil** [comment]
It's a study looking at healing trajectories following surgery. One session is collected before surgery and the other after (closer to the endpoint). One of the main analyses involves predicting those trajectories from pre-surgical data alone, with the specific aim of assessing the informativeness of the pre-surgical data alone. There will also be longitudinal analyses (for which the current layout with one anatomical template covering all session is great), but the session-specific analyses are also needed.

**Comment by araikes** [comment]
In that case, being that you don't necessarily need combined reports either, then using `--bids-filter-file` to subset the dataset and creating two output directories (one for pre-treatment and one for post-treatment) would maintain the separability that you're looking for.

**Comment by psadil** [comment]
That's more-or-less how our workflow is proceeding. We are storing these session-level results as separate datasets (e.g., `qsiprep_ses-1`, `qsiprep_ses-2`), but our inputs were already being sent to qsiprep a session at a time, so there hasn't been a need for the `--bids-filter-file` argument. It's just less convenient for us to maintain two outputs folders.

If the feature request sounds outside the scope of qsiprep, feel free to close this issue.

**Comment by mattcieslak** [comment]
I've wanted to update how sessions are handled for a long time. Our group also processes sessions separately and store the results separate from one another, but there's no reason it has to be that way.

**Comment by tsalo** [comment]
@mattcieslak recently added the ability to process each session's anatomical data separately, so I think we can close this.
