### ISSUE TITLE
SIFT2 parameters

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsiprep#765]
This is a question, not a bug, but I can't change the type.

If I have a recon pipeline with "sift: {}", I know that it's using SIFT2 to filter the streamlines (using the streamlines, the normalized FOD image, and outputting the CSV with streamline weights).  What parameters/options is SIFT2 using when called this way in the recon spec?

Thanks

**Comment by mattcieslak** [comment]
The parameters are named after the options defined [here](https://github.com/PennLINC/qsiprep/blob/65791db2bdcad38238746939a00675f23248ac02/qsiprep/interfaces/mrtrix.py#L517). Sift2 won't filter streamlines, but it will calculate weights for each. The original sift would delete steamlines, but we don't have that implemented in qsiprep for now
