### ISSUE TITLE
mrtrix_multishell_msmt_ACT-hsvs crashing

### ISSUE THREAD

**Issue by DVSneuro** [PennLINC/qsiprep#777]
## Summary
We're using `mrtrix_multishell_msmt_ACT-hsvs` as the recon spec, but it's crashing before producing any output. 

## Additional details

- QSIPrep version: 0.21.4
- Docker version: n/a
- Singularity version: apptainer version 1.2.4

### What were you trying to do?
We're trying to use `mrtrix_multishell_msmt_ACT-hsvs` reconstruction. We're providing it with QSIprep inputs and also freesurfer inputs. 

### What did you expect to happen?
Expected to see html output files and also images in the qsirecon subfolder, but minimal output there and I'm not seeing any other clues in the scratch directory. 

### What actually happened?
No output but the following exception shows up in the logs:
```
Traceback (most recent call last):
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/cli/run.py", line 1330, in build_recon_workflow
    retval["workflow"] = init_qsirecon_wf(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/workflows/recon/base.py", line 130, in init_qsirecon_wf
    single_subject_wf = init_single_subject_wf(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/workflows/recon/base.py", line 262, in init_single_subject_wf
    anat_ingress_node, available_anatomical_data = init_highres_recon_anatomical_wf(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/workflows/recon/anatomical.py", line 178, in init_highres_recon_anatomical_wf
    workflow.connect([
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/workflows.py", line 183, in connect
    raise Exception(
Exception: Trying to connect anat_ingress_wf.register_fs_to_qsiprep_wf:outputnode.brain to anat_ingress_wf.outputnode:brain but input 'brain' of node 'anat_ingress_wf.outputnode' is already
connected.
```

## Reproducing the bug
Here's our command:
```
singularity run --cleanenv --writable-tmpfs \
	-B ${TEMPLATEFLOW_DIR}:/opt/templateflow \
	-B ${MPLCONFIGDIR_DIR}:/opt/mplconfigdir \
	-B $maindir:/base \
	-B ~/work/tools/licenses:/opts \
	-B $scratchdir:/scratch \
	~/work/tools/qsiprep-0.21.4.sif \
	/base/bids /base/derivatives/qsirecon-ACThsvs \
	participant --participant_label $sub \
	--output-resolution 2 \
	--recon-input /base/derivatives/qsiprep \
	--recon-spec mrtrix_multishell_msmt_ACT-hsvs \
	--recon-only \
	--stop-on-first-crash \
	--freesurfer-input /base/derivatives/fmriprep/sourcedata/freesurfer \
	--fs-license-file /opts/fs_license.txt \
	--skip_bids_validation \
	--n-cpus 7 --omp-nthreads 6 \
	-w /scratch
```
Note that the dataset is BIDS valid. We are using the `--skip_bids_validation` because we were getting issues similar to this Neurostars post with a large dataset (https://neurostars.org/t/clarifying-file-reading-in-bids-validator-vs-fmriprep/5195/8).

Also, these data are on OpenNeuro: https://openneuro.org/datasets/ds005123/versions/1.0.1

Thanks for any help!

**Comment by araikes** [comment]
Hi @DVSneuro,

Known issue. See #718

**Comment by DVSneuro** [comment]
Oops, sorry I missed that and thanks for the reference! I'll close this duplicate and follow the other conversation.
