### ISSUE TITLE
qsiprep pennbbl/qsiprep:0.21.4 is linked to the development version v0.21.5.dev0+g36b93fe.d20240504

### ISSUE THREAD

**Issue by johnaeanderson** [PennLINC/qsiprep#806]
## Summary
the docker image of qsiprep for version 0.21.4 points to the wrong version (the development version) instead of the previous version. 

johnanderson@JohnAnderson-Lambda:~$ docker run --rm pennbbl/qsiprep:0.21.4 --version
qsiprep v0.21.5.dev0+g36b93fe.d20240504

**Comment by tsalo** [comment]
I'm pretty sure it's just an issue with resolving the version string. The actual version is still 0.21.4.

**Comment by mattcieslak** [comment]
yes, @tsalo is right. At some point our internal version number got messed up. As long as you are pulling from the tag on dockerhub you are definitely getting the intended version 0.21.4
