### ISSUE TITLE
traits.trait_errors.TraitError: The 'interpolation_method' trait of a _ChooseInterpolatorOutputSpec instance must be 'LanczosWindowedSinc' or 'BSpline' or 'NearestNeighbor', but a value of 'Linear' <class 'str'> was specified.

### ISSUE THREAD

**Issue by chiuhoward** [PennLINC/qsiprep#829]
## Summary
Interpolation fails downstream when upsampling my data by more than 10%.

## Additional details

- QSIPrep version: unstable (sha256:be42cbae975ed784ac020405b97bc363213ae446568e7d2ccfbf31c88208f3a8)
- Docker version:
- Singularity version: apptainer version 1.3.2-1.el7

### What were you trying to do?
My T1w data was obtained at a 1mm resolution, and my DWI images were obtained at a 2mm resolution. When I put output resolution at 1.7, the interpolation step failed. QSIprep completed successfully when I changed output resolution to 2.

### What did you expect to happen?
QSIprep to complete even at output resolution of 1.7.

### What actually happened?
"If you are upsampling your data by more than 10%, QSIPrep will use Linear interpolation instead of Lanczos windowed Sinc interpolation.” (https://github.com/PennLINC/qsiprep/blob/2967323a2e9634c18afa7a2b7e76048bed13a025/docs/quickstart.rst?plain=1#L97C24-L99C15) However, the ChooseInterpolatorOutputSpec step does not take Linear as a valid argument, but only 'LanczosWindowedSinc' or 'BSpline' or ‘NearestNeighbor’.

## Reproducing the bug

This completed running, but the exact same code with `—output-resolution 1.7` failed.

```
export APPTAINERENV_FS_LICENSE=$GROUP_HOME/freesurferlicense.txt
export APPTAINER_TMPDIR='/scratch/users/chiuh/tmp'
export APPTAINER_CACHEDIR='/scratch/users/chiuh/cache'

singularity run --cleanenv \
/home/groups/jyeatman/software/singularity_images/qsiprep-0.23.0-unstable-11Oct24.sif \
/scratch/groups/jyeatman/howard/DBPFullwT1Oct24/DBPFullwT1 \
/scratch/groups/jyeatman/howard/DBPFullwT1derivOct24/ participant --participant-label sub-$SLURM_ARRAY_TASK_ID \
-w /scratch/groups/jyeatman/howard/DBPFullwT1derivOct24-work/ \
--infant \
--nthreads 10 \
--omp-nthreads 8 \
--output-resolution 2 \
--unringing-method rpg \
--denoise-method dwidenoise \
--b1-biascorrect-stage none \
--pepolar-method TOPUP+DRBUDDI
```

**Comment by tsalo** [comment]
Closed by #832.
