### ISSUE TITLE
Is --subject-anatomical-reference available to test?

### ISSUE THREAD

**Issue by jhauneuro** [PennLINC/qsiprep#857]
## Summary
I noticed the new `--subject-anatomical-reference {first-alphabetically,unbiased,sessionwise}` option in the documentation for `0.23.0` and would like to use it on my data. I have built the QSIPrep v0.23.1dev docker image but get an error: `[unrecognized](qsiprep: error: unrecognized arguments: --subject-anatomical-reference sessionwise)`. Is that option available for testing?

**Comment by tsalo** [comment]
@jhauneuro that parameter isn't in a release yet, but you can grab the unstable version from DockerHub. FWIW, that parameter is documented in the latest version on RTD (which is the default landing page), but not in 0.23.0 (see https://qsiprep.readthedocs.io/en/0.23.0/usage.html#command-line-arguments).
