### ISSUE TITLE
FOR HBCD: publish on Zenodo to obtain DOI specifically linked to the current version of software 

### ISSUE THREAD

**Issue by LuciMoore** [PennLINC/qsiprep#882]
@mattcieslak - 

The MIDB team has submitted an initial NMIND checklist review for QSIPrep as part of efforts to standardize pipelines used for HBCD data processing (detailed [here](https://hbcd-docs.readthedocs.io/en/latest/processing/standards/))

QSIPrep hits all major requirements for HBCD  and was very highly rated otherwise! The only item remaining is to provide a DOI that specifically links to the current version of the software. Please self-publish on [Zenodo](https://cdnis-brain.readthedocs.io/zenodo/) and add the DOI to your webpage (it should be quick and easy)

Though not required, if you would like to view additional checklist items that QSIPrep did not meet in order to address them, you can make a copy of the json from [this issue](https://github.com/nmind/proceedings/issues/24) and import it to https://www.nmind.org/standards-checklist/

**Comment by tsalo** [comment]
We can add it, but version-specific DOIs aren't really useful. There's no good workflow (AFAIK) to generate a version-specific DOI and then put that DOI in the boilerplate (where most people get their reference list) or even the project documentation for that version.

**Comment by tsalo** [comment]
It's up now! https://zenodo.org/records/14187328

**Comment by LuciMoore** [comment]
@mattcieslak and @tsalo thank you both. Do you mind adding the Zenodo badge to your readthedocs page as well? Then you'll be ready for the NMIND team to perform the final review 

The same will need to be done for QSIRecon, I'll open a separate issue on the GitHub
